/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { addonsDeleteAddon } from "../../funcs/addonsDeleteAddon.js";
import { DeleteAddonRequest$zodSchema } from "../../models/deleteaddonop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteAddonRequest$zodSchema,
};

export const tool$addonsDeleteAddon: ToolDefinition<typeof args> = {
  name: "addons-delete-addon",
  description: `Delete addon

Use when retiring an addon (e.g. end-of-life). Returns 200 with success message.`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await addonsDeleteAddon(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
