/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { addonsUpdateAddon } from "../../funcs/addonsUpdateAddon.js";
import { UpdateAddonRequest$zodSchema } from "../../models/updateaddonop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateAddonRequest$zodSchema,
};

export const tool$addonsUpdateAddon: ToolDefinition<typeof args> = {
  name: "addons-update-addon",
  description: `Update addon

Use when changing addon details (e.g. name, pricing, or metadata).`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await addonsUpdateAddon(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
