/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { costsGetDetailedCostAnalyticsV2 } from "../../funcs/costsGetDetailedCostAnalyticsV2.js";
import { DtoGetCostAnalyticsRequest$zodSchema } from "../../models/dtogetcostanalyticsrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoGetCostAnalyticsRequest$zodSchema,
};

export const tool$costsGetDetailedCostAnalyticsV2: ToolDefinition<typeof args> =
  {
    name: "costs-get-detailed-cost-analytics-v2",
    description: `Get combined revenue and cost analytics (V2)

Use when you need the same revenue/cost/ROI analytics but computed from the costsheet usage-tracking pipeline (e.g. for consistency with usage-based cost data).`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await costsGetDetailedCostAnalyticsV2(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
