/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { costsDeleteCostsheet } from "../../funcs/costsDeleteCostsheet.js";
import { DeleteCostsheetRequest$zodSchema } from "../../models/deletecostsheetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteCostsheetRequest$zodSchema,
};

export const tool$costsDeleteCostsheet: ToolDefinition<typeof args> = {
  name: "costs-delete-costsheet",
  description: `Delete costsheet

Use when retiring a costsheet (e.g. end-of-life product). Soft-deletes; status set to deleted.`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await costsDeleteCostsheet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
