/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { costsGetActiveCostsheet } from "../../funcs/costsGetActiveCostsheet.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$costsGetActiveCostsheet: ToolDefinition = {
  name: "costs-get-active-costsheet",
  description: `Get active costsheet

Use when you need the tenant's default pricing configuration (e.g. for checkout or plan display). Returns the active costsheet for the environment.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result] = await costsGetActiveCostsheet(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
