/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { costsGetCostsheet } from "../../funcs/costsGetCostsheet.js";
import { GetCostsheetRequest$zodSchema } from "../../models/getcostsheetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCostsheetRequest$zodSchema,
};

export const tool$costsGetCostsheet: ToolDefinition<typeof args> = {
  name: "costs-get-costsheet",
  description: `Get costsheet

Use when you need to load a single costsheet (e.g. for editing or display). Supports optional expand for related prices.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await costsGetCostsheet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
