/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { costsGetDetailedCostAnalytics } from "../../funcs/costsGetDetailedCostAnalytics.js";
import { DtoGetCostAnalyticsRequest$zodSchema } from "../../models/dtogetcostanalyticsrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoGetCostAnalyticsRequest$zodSchema,
};

export const tool$costsGetDetailedCostAnalytics: ToolDefinition<typeof args> = {
  name: "costs-get-detailed-cost-analytics",
  description: `Get combined revenue and cost analytics

Use when building dashboards or reports that need revenue vs cost, ROI, and margin over a time period (e.g. finance views or executive summaries).`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await costsGetDetailedCostAnalytics(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
