/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { couponsQueryCoupon } from "../../funcs/couponsQueryCoupon.js";
import { TypesCouponFilter$zodSchema } from "../../models/typescouponfilter.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TypesCouponFilter$zodSchema,
};

export const tool$couponsQueryCoupon: ToolDefinition<typeof args> = {
  name: "coupons-query-coupon",
  description: `Query coupons

Use when listing or searching coupons (e.g. promo management). Returns a paginated list; supports filtering and sorting.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await couponsQueryCoupon(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
