/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { couponsUpdateCoupon } from "../../funcs/couponsUpdateCoupon.js";
import { UpdateCouponRequest$zodSchema } from "../../models/updatecouponop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateCouponRequest$zodSchema,
};

export const tool$couponsUpdateCoupon: ToolDefinition<typeof args> = {
  name: "coupons-update-coupon",
  description: `Update coupon

Use when changing coupon config (e.g. value, validity, or usage limits).`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await couponsUpdateCoupon(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
