/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { couponsGetCoupon } from "../../funcs/couponsGetCoupon.js";
import { GetCouponRequest$zodSchema } from "../../models/getcouponop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCouponRequest$zodSchema,
};

export const tool$couponsGetCoupon: ToolDefinition<typeof args> = {
  name: "coupons-get-coupon",
  description: `Get coupon

Use when you need to load a single coupon (e.g. for display or to validate a code).`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await couponsGetCoupon(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
