/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { creditGrantsGetPlanCreditGrants } from "../../funcs/creditGrantsGetPlanCreditGrants.js";
import { GetPlanCreditGrantsRequest$zodSchema } from "../../models/getplancreditgrantsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetPlanCreditGrantsRequest$zodSchema,
};

export const tool$creditGrantsGetPlanCreditGrants: ToolDefinition<typeof args> =
  {
    name: "credit-grants-get-plan-credit-grants",
    description: `Get plan credit grants

Use when listing credits attached to a plan (e.g. included prepaid or promo credits).`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await creditGrantsGetPlanCreditGrants(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
