/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { creditNotesVoidCreditNote } from "../../funcs/creditNotesVoidCreditNote.js";
import { VoidCreditNoteRequest$zodSchema } from "../../models/voidcreditnoteop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: VoidCreditNoteRequest$zodSchema,
};

export const tool$creditNotesVoidCreditNote: ToolDefinition<typeof args> = {
  name: "credit-notes-void-credit-note",
  description: `Void credit note

Use when cancelling a draft credit note (e.g. created by mistake). Only draft credit notes can be voided.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await creditNotesVoidCreditNote(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
