/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { creditGrantsGetCreditGrant } from "../../funcs/creditGrantsGetCreditGrant.js";
import { GetCreditGrantRequest$zodSchema } from "../../models/getcreditgrantop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCreditGrantRequest$zodSchema,
};

export const tool$creditGrantsGetCreditGrant: ToolDefinition<typeof args> = {
  name: "credit-grants-get-credit-grant",
  description: `Get credit grant

Use when you need to load a single credit grant (e.g. for display or to check balance).`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await creditGrantsGetCreditGrant(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
