/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { creditNotesProcessCreditNote } from "../../funcs/creditNotesProcessCreditNote.js";
import { ProcessCreditNoteRequest$zodSchema } from "../../models/processcreditnoteop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ProcessCreditNoteRequest$zodSchema,
};

export const tool$creditNotesProcessCreditNote: ToolDefinition<typeof args> = {
  name: "credit-notes-process-credit-note",
  description: `Finalize credit note

Use when locking a draft credit note and applying the credit (e.g. after approval). Once finalized, applied per billing provider.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await creditNotesProcessCreditNote(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
