/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { entityIntegrationMappingsDeleteEntityIntegrationMapping } from "../../funcs/entityIntegrationMappingsDeleteEntityIntegrationMapping.js";
import { DeleteEntityIntegrationMappingRequest$zodSchema } from "../../models/deleteentityintegrationmappingop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteEntityIntegrationMappingRequest$zodSchema,
};

export const tool$entityIntegrationMappingsDeleteEntityIntegrationMapping:
  ToolDefinition<typeof args> = {
    name: "entity-integration-mappings-delete-entity-a57",
    description: `Delete entity integration mapping

Use when unlinking a FlexPrice entity from an external system or cleaning up stale integration mappings.`,
    annotations: {
      "title": "",
      "destructiveHint": true,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await entityIntegrationMappingsDeleteEntityIntegrationMapping(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
