/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { entitlementsCreateEntitlementsBulk } from "../../funcs/entitlementsCreateEntitlementsBulk.js";
import { DtoCreateBulkEntitlementRequest$zodSchema } from "../../models/dtocreatebulkentitlementrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoCreateBulkEntitlementRequest$zodSchema,
};

export const tool$entitlementsCreateEntitlementsBulk: ToolDefinition<
  typeof args
> = {
  name: "entitlements-create-entitlements-bulk",
  description: `Create entitlements in bulk

Use when attaching many features to a plan or addon at once (e.g. initial plan setup or import). Bulk version of create entitlement.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await entitlementsCreateEntitlementsBulk(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
