/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { entitlementsGetPlanEntitlements } from "../../funcs/entitlementsGetPlanEntitlements.js";
import { GetPlanEntitlementsRequest$zodSchema } from "../../models/getplanentitlementsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetPlanEntitlementsRequest$zodSchema,
};

export const tool$entitlementsGetPlanEntitlements: ToolDefinition<typeof args> =
  {
    name: "entitlements-get-plan-entitlements",
    description: `Get plan entitlements

Use when checking what a plan includes (e.g. feature list or limits for display or gating).`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await entitlementsGetPlanEntitlements(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
