/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { entitlementsDeleteEntitlement } from "../../funcs/entitlementsDeleteEntitlement.js";
import { DeleteEntitlementRequest$zodSchema } from "../../models/deleteentitlementop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteEntitlementRequest$zodSchema,
};

export const tool$entitlementsDeleteEntitlement: ToolDefinition<typeof args> = {
  name: "entitlements-delete-entitlement",
  description: `Delete entitlement

Use when removing a feature from a plan or addon (e.g. deprecating a capability). Returns 200 with success message.`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await entitlementsDeleteEntitlement(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
