/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { entitlementsQueryEntitlement } from "../../funcs/entitlementsQueryEntitlement.js";
import { TypesEntitlementFilter$zodSchema } from "../../models/typesentitlementfilter.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TypesEntitlementFilter$zodSchema,
};

export const tool$entitlementsQueryEntitlement: ToolDefinition<typeof args> = {
  name: "entitlements-query-entitlement",
  description: `Query entitlements

Use when listing or searching entitlements (e.g. plan editor or audit). Returns a paginated list; supports filtering by plan, addon, feature.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await entitlementsQueryEntitlement(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
