/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { environmentsCreateEnvironment } from "../../funcs/environmentsCreateEnvironment.js";
import { DtoCreateEnvironmentRequest$zodSchema } from "../../models/dtocreateenvironmentrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoCreateEnvironmentRequest$zodSchema,
};

export const tool$environmentsCreateEnvironment: ToolDefinition<typeof args> = {
  name: "environments-create-environment",
  description: `Create environment

Use when setting up a new environment (e.g. production, staging) for the tenant. Ideal for separating billing or config per environment.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await environmentsCreateEnvironment(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
