/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { environmentsUpdateEnvironment } from "../../funcs/environmentsUpdateEnvironment.js";
import { UpdateEnvironmentRequest$zodSchema } from "../../models/updateenvironmentop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateEnvironmentRequest$zodSchema,
};

export const tool$environmentsUpdateEnvironment: ToolDefinition<typeof args> = {
  name: "environments-update-environment",
  description: `Update environment

Use when changing environment name or settings (e.g. renaming or updating metadata).`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await environmentsUpdateEnvironment(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
