/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsGetUsageAnalytics } from "../../funcs/eventsGetUsageAnalytics.js";
import { DtoGetUsageAnalyticsRequest$zodSchema } from "../../models/dtogetusageanalyticsrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoGetUsageAnalyticsRequest$zodSchema,
};

export const tool$eventsGetUsageAnalytics: ToolDefinition<typeof args> = {
  name: "events-get-usage-analytics",
  description: `Get usage analytics

Use when building analytics views (e.g. usage by feature or customer over time). Supports filtering, grouping, and time-series breakdown.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await eventsGetUsageAnalytics(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
