/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { featuresDeleteFeature } from "../../funcs/featuresDeleteFeature.js";
import { DeleteFeatureRequest$zodSchema } from "../../models/deletefeatureop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteFeatureRequest$zodSchema,
};

export const tool$featuresDeleteFeature: ToolDefinition<typeof args> = {
  name: "features-delete-feature",
  description: `Delete feature

Use when retiring a feature (e.g. deprecated capability). Returns 200 with success message.`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await featuresDeleteFeature(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
