/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { featuresUpdateFeature } from "../../funcs/featuresUpdateFeature.js";
import { UpdateFeatureRequest$zodSchema } from "../../models/updatefeatureop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateFeatureRequest$zodSchema,
};

export const tool$featuresUpdateFeature: ToolDefinition<typeof args> = {
  name: "features-update-feature",
  description: `Update feature

Use when changing feature definition (e.g. name, type, or meter). Request body contains the fields to update.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await featuresUpdateFeature(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
