/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { featuresQueryFeature } from "../../funcs/featuresQueryFeature.js";
import { TypesFeatureFilter$zodSchema } from "../../models/typesfeaturefilter.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TypesFeatureFilter$zodSchema,
};

export const tool$featuresQueryFeature: ToolDefinition<typeof args> = {
  name: "features-query-feature",
  description: `Query features

Use when listing or searching features (e.g. catalog or entitlement setup). Returns a paginated list; supports filtering and sorting.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await featuresQueryFeature(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
