/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { featuresCreateFeature } from "../../funcs/featuresCreateFeature.js";
import { DtoCreateFeatureRequest$zodSchema } from "../../models/dtocreatefeaturerequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoCreateFeatureRequest$zodSchema,
};

export const tool$featuresCreateFeature: ToolDefinition<typeof args> = {
  name: "features-create-feature",
  description: `Create feature

Use when defining a new feature or capability to gate or meter (e.g. feature flags or usage-based limits). Ideal for boolean or usage features.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await featuresCreateFeature(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
