/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { groupsQueryGroup } from "../../funcs/groupsQueryGroup.js";
import { TypesGroupFilter$zodSchema } from "../../models/typesgroupfilter.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TypesGroupFilter$zodSchema,
};

export const tool$groupsQueryGroup: ToolDefinition<typeof args> = {
  name: "groups-query-group",
  description: `Query groups

Use when listing or searching groups (e.g. admin catalog). Returns a paginated list; supports filtering and sorting.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await groupsQueryGroup(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
