/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { groupsCreateGroup } from "../../funcs/groupsCreateGroup.js";
import { DtoCreateGroupRequest$zodSchema } from "../../models/dtocreategrouprequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoCreateGroupRequest$zodSchema,
};

export const tool$groupsCreateGroup: ToolDefinition<typeof args> = {
  name: "groups-create-group",
  description: `Create group

Use when organizing entities into a group (e.g. for filtering prices or plans by product line or region).`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await groupsCreateGroup(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
