/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsCreateOrUpdateIntegration } from "../../funcs/integrationsCreateOrUpdateIntegration.js";
import { CreateOrUpdateIntegrationRequest$zodSchema } from "../../models/createorupdateintegrationop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateOrUpdateIntegrationRequest$zodSchema,
};

export const tool$integrationsCreateOrUpdateIntegration: ToolDefinition<
  typeof args
> = {
  name: "integrations-create-or-update-integration",
  description: `Create or update an integration

Use when storing or updating credentials for an external integration (e.g. Stripe, HubSpot). Secrets are encrypted at rest.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await integrationsCreateOrUpdateIntegration(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
