/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsGetIntegration } from "../../funcs/integrationsGetIntegration.js";
import { GetIntegrationRequest$zodSchema } from "../../models/getintegrationop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetIntegrationRequest$zodSchema,
};

export const tool$integrationsGetIntegration: ToolDefinition<typeof args> = {
  name: "integrations-get-integration",
  description: `Get integration details

Use when you need to check or display integration config (e.g. which provider is linked). Sensitive values may be redacted.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await integrationsGetIntegration(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
