/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesRecalculateInvoice } from "../../funcs/invoicesRecalculateInvoice.js";
import { RecalculateInvoiceRequest$zodSchema } from "../../models/recalculateinvoiceop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RecalculateInvoiceRequest$zodSchema,
};

export const tool$invoicesRecalculateInvoice: ToolDefinition<typeof args> = {
  name: "invoices-recalculate-invoice",
  description: `Recalculate invoice

Use when subscription or usage data changed and you need to refresh a draft invoice before finalizing. Optional finalize=true to lock after recalc.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await invoicesRecalculateInvoice(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
