/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paymentsDeletePayment } from "../../funcs/paymentsDeletePayment.js";
import { DeletePaymentRequest$zodSchema } from "../../models/deletepaymentop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeletePaymentRequest$zodSchema,
};

export const tool$paymentsDeletePayment: ToolDefinition<typeof args> = {
  name: "payments-delete-payment",
  description: `Delete payment

Use when removing or voiding a payment record (e.g. correcting erroneous entries). Returns 200 with success message.`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await paymentsDeletePayment(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
