/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paymentsUpdatePayment } from "../../funcs/paymentsUpdatePayment.js";
import { UpdatePaymentRequest$zodSchema } from "../../models/updatepaymentop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdatePaymentRequest$zodSchema,
};

export const tool$paymentsUpdatePayment: ToolDefinition<typeof args> = {
  name: "payments-update-payment",
  description: `Update payment

Use when updating payment status or metadata (e.g. after reconciliation or adding a reference).`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await paymentsUpdatePayment(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
