/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { plansUpdatePlan } from "../../funcs/plansUpdatePlan.js";
import { UpdatePlanRequest$zodSchema } from "../../models/updateplanop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdatePlanRequest$zodSchema,
};

export const tool$plansUpdatePlan: ToolDefinition<typeof args> = {
  name: "plans-update-plan",
  description: `Update plan

Use when changing plan details (e.g. name, interval, or metadata). Partial update supported.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await plansUpdatePlan(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
