/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { plansPostPlansIdClone } from "../../funcs/plansPostPlansIdClone.js";
import { PostPlansIdCloneRequest$zodSchema } from "../../models/postplansidcloneop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostPlansIdCloneRequest$zodSchema,
};

export const tool$plansPostPlansIdClone: ToolDefinition<typeof args> = {
  name: "plans-post-plans-id-clone",
  description: `Clone a plan

Clone an existing plan, copying its active prices, published entitlements, and published credit grants`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await plansPostPlansIdClone(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
