/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { rbacGetRBACRole } from "../../funcs/rbacGetRBACRole.js";
import { GetRbacRoleRequest$zodSchema } from "../../models/getrbacroleop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetRbacRoleRequest$zodSchema,
};

export const tool$rbacGetRBACRole: ToolDefinition<typeof args> = {
  name: "rbac-get-rbac-role",
  description: `Get a specific RBAC role

Use when you need to show or edit a single role (e.g. role detail page). Includes permissions, name, and description.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await rbacGetRBACRole(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
