/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { scheduledTasksListScheduledTasks } from "../../funcs/scheduledTasksListScheduledTasks.js";
import { ListScheduledTasksRequest$zodSchema } from "../../models/listscheduledtasksop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListScheduledTasksRequest$zodSchema.optional(),
};

export const tool$scheduledTasksListScheduledTasks: ToolDefinition<
  typeof args
> = {
  name: "scheduled-tasks-list-scheduled-tasks",
  description: `List scheduled tasks

Use when listing or managing scheduled tasks in an admin UI. Returns a list; supports filtering by status, type, and pagination.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await scheduledTasksListScheduledTasks(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
