/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { scheduledTasksUpdateScheduledTask } from "../../funcs/scheduledTasksUpdateScheduledTask.js";
import { UpdateScheduledTaskRequest$zodSchema } from "../../models/updatescheduledtaskop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateScheduledTaskRequest$zodSchema,
};

export const tool$scheduledTasksUpdateScheduledTask: ToolDefinition<
  typeof args
> = {
  name: "scheduled-tasks-update-scheduled-task",
  description: `Update a scheduled task

Use when pausing or resuming a scheduled task. Only the enabled field can be changed.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await scheduledTasksUpdateScheduledTask(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
