/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { scheduledTasksTriggerScheduledTaskRun } from "../../funcs/scheduledTasksTriggerScheduledTaskRun.js";
import { TriggerScheduledTaskRunRequest$zodSchema } from "../../models/triggerscheduledtaskrunop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TriggerScheduledTaskRunRequest$zodSchema,
};

export const tool$scheduledTasksTriggerScheduledTaskRun: ToolDefinition<
  typeof args
> = {
  name: "scheduled-tasks-trigger-scheduled-task-run",
  description: `Trigger force run

Use when you need to run a scheduled export immediately (e.g. on-demand report or catch-up). Supports optional custom time range.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await scheduledTasksTriggerScheduledTaskRun(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
