/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { scheduledTasksScheduleUpdateBillingPeriod } from "../../funcs/scheduledTasksScheduleUpdateBillingPeriod.js";
import { ScheduleUpdateBillingPeriodRequest$zodSchema } from "../../models/scheduleupdatebillingperiodop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ScheduleUpdateBillingPeriodRequest$zodSchema,
};

export const tool$scheduledTasksScheduleUpdateBillingPeriod: ToolDefinition<
  typeof args
> = {
  name: "scheduled-tasks-schedule-update-billing-period",
  description: `Schedule update billing period

Use when you need to trigger a billing-period update workflow (e.g. to recalculate or sync billing windows).`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await scheduledTasksScheduleUpdateBillingPeriod(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
