/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { scheduledTasksGetScheduledTask } from "../../funcs/scheduledTasksGetScheduledTask.js";
import { GetScheduledTaskRequest$zodSchema } from "../../models/getscheduledtaskop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetScheduledTaskRequest$zodSchema,
};

export const tool$scheduledTasksGetScheduledTask: ToolDefinition<typeof args> =
  {
    name: "scheduled-tasks-get-scheduled-task",
    description: `Get scheduled task

Use when you need to load a single scheduled task (e.g. to show details in a UI or check its configuration).`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await scheduledTasksGetScheduledTask(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
