/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsResumeSubscription } from "../../funcs/subscriptionsResumeSubscription.js";
import { ResumeSubscriptionRequest$zodSchema } from "../../models/resumesubscriptionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ResumeSubscriptionRequest$zodSchema,
};

export const tool$subscriptionsResumeSubscription: ToolDefinition<typeof args> =
  {
    name: "subscriptions-resume-subscription",
    description: `Resume a paused subscription

Use when reactivating a paused subscription (e.g. end of hold). Billing and access resume from the resume date.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await subscriptionsResumeSubscription(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
