/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsListSubscriptionPauses } from "../../funcs/subscriptionsListSubscriptionPauses.js";
import { ListSubscriptionPausesRequest$zodSchema } from "../../models/listsubscriptionpausesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListSubscriptionPausesRequest$zodSchema,
};

export const tool$subscriptionsListSubscriptionPauses: ToolDefinition<
  typeof args
> = {
  name: "subscriptions-list-subscription-pauses",
  description: `List all pauses for a subscription

Use when showing pause history for a subscription (e.g. support or audit). Returns all past and future pauses.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsListSubscriptionPauses(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
