/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tasksUpdateTaskStatus } from "../../funcs/tasksUpdateTaskStatus.js";
import { UpdateTaskStatusRequest$zodSchema } from "../../models/updatetaskstatusop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateTaskStatusRequest$zodSchema,
};

export const tool$tasksUpdateTaskStatus: ToolDefinition<typeof args> = {
  name: "tasks-update-task-status",
  description: `Update task status

Use when updating task status (e.g. marking complete or failed from a worker). Typically called by backend processors.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await tasksUpdateTaskStatus(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
