/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taxAssociationsDeleteTaxAssociation } from "../../funcs/taxAssociationsDeleteTaxAssociation.js";
import { DeleteTaxAssociationRequest$zodSchema } from "../../models/deletetaxassociationop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteTaxAssociationRequest$zodSchema,
};

export const tool$taxAssociationsDeleteTaxAssociation: ToolDefinition<
  typeof args
> = {
  name: "tax-associations-delete-tax-association",
  description: `Delete tax association

Use when removing a tax association (e.g. entity no longer subject to that rate).`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await taxAssociationsDeleteTaxAssociation(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
