/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taxAssociationsUpdateTaxAssociation } from "../../funcs/taxAssociationsUpdateTaxAssociation.js";
import { UpdateTaxAssociationRequest$zodSchema } from "../../models/updatetaxassociationop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateTaxAssociationRequest$zodSchema,
};

export const tool$taxAssociationsUpdateTaxAssociation: ToolDefinition<
  typeof args
> = {
  name: "tax-associations-update-tax-association",
  description: `Update tax association

Use when changing a tax association (e.g. switch rate or entity). Request body contains the fields to update.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await taxAssociationsUpdateTaxAssociation(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
