/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taxAssociationsGetTaxAssociation } from "../../funcs/taxAssociationsGetTaxAssociation.js";
import { GetTaxAssociationRequest$zodSchema } from "../../models/gettaxassociationop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetTaxAssociationRequest$zodSchema,
};

export const tool$taxAssociationsGetTaxAssociation: ToolDefinition<
  typeof args
> = {
  name: "tax-associations-get-tax-association",
  description: `Get Tax Association

Use when you need to load a single tax association (e.g. for display or editing).`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await taxAssociationsGetTaxAssociation(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
