/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taxRatesDeleteTaxRate } from "../../funcs/taxRatesDeleteTaxRate.js";
import { DeleteTaxRateRequest$zodSchema } from "../../models/deletetaxrateop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteTaxRateRequest$zodSchema,
};

export const tool$taxRatesDeleteTaxRate: ToolDefinition<typeof args> = {
  name: "tax-rates-delete-tax-rate",
  description: `Delete a tax rate

Use when retiring a tax rate (e.g. no longer applicable). Fails if still referenced by associations.`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await taxRatesDeleteTaxRate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
