/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taxRatesCreateTaxRate } from "../../funcs/taxRatesCreateTaxRate.js";
import { DtoCreateTaxRateRequest$zodSchema } from "../../models/dtocreatetaxraterequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoCreateTaxRateRequest$zodSchema,
};

export const tool$taxRatesCreateTaxRate: ToolDefinition<typeof args> = {
  name: "tax-rates-create-tax-rate",
  description: `Create a tax rate

Use when defining a new tax rate (e.g. VAT or sales tax) for use in invoices. Attach to customers or products via tax associations.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await taxRatesCreateTaxRate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
