/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taxRatesGetTaxRates } from "../../funcs/taxRatesGetTaxRates.js";
import { GetTaxRatesRequest$zodSchema } from "../../models/gettaxratesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetTaxRatesRequest$zodSchema.optional(),
};

export const tool$taxRatesGetTaxRates: ToolDefinition<typeof args> = {
  name: "tax-rates-get-tax-rates",
  description: `Get tax rates

Use when listing tax rates (e.g. tax config UI). Returns tax rates with optional filters.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await taxRatesGetTaxRates(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
