/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taxRatesUpdateTaxRate } from "../../funcs/taxRatesUpdateTaxRate.js";
import { UpdateTaxRateRequest$zodSchema } from "../../models/updatetaxrateop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateTaxRateRequest$zodSchema,
};

export const tool$taxRatesUpdateTaxRate: ToolDefinition<typeof args> = {
  name: "tax-rates-update-tax-rate",
  description: `Update a tax rate

Use when changing a tax rate (e.g. rate value or name). Request body contains the fields to update.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await taxRatesUpdateTaxRate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
