/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tenantsGetTenantBillingUsage } from "../../funcs/tenantsGetTenantBillingUsage.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$tenantsGetTenantBillingUsage: ToolDefinition = {
  name: "tenants-get-tenant-billing-usage",
  description: `Get billing usage for the current tenant

Use when showing the current tenant's billing usage (e.g. admin billing page or usage caps). Returns subscription and usage for the tenant.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result] = await tenantsGetTenantBillingUsage(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
