/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersCreateUser } from "../../funcs/usersCreateUser.js";
import { DtoCreateUserRequest$zodSchema } from "../../models/dtocreateuserrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DtoCreateUserRequest$zodSchema,
};

export const tool$usersCreateUser: ToolDefinition<typeof args> = {
  name: "users-create-user",
  description: `Create service account

Use when provisioning API access for automation, CI/CD pipelines, or headless integrations that need scoped API keys.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await usersCreateUser(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
