/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { walletsQueryWalletTransaction } from "../../funcs/walletsQueryWalletTransaction.js";
import { TypesWalletTransactionFilter$zodSchema } from "../../models/typeswallettransactionfilter.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TypesWalletTransactionFilter$zodSchema,
};

export const tool$walletsQueryWalletTransaction: ToolDefinition<typeof args> = {
  name: "wallets-query-wallet-transaction",
  description: `Query wallet transactions

Use when searching or reporting on wallet transactions (e.g. cross-wallet history or reconciliation). Returns a paginated list; supports filtering by wallet, customer, type, date range.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await walletsQueryWalletTransaction(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
