/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { walletsUpdateWallet } from "../../funcs/walletsUpdateWallet.js";
import { UpdateWalletRequest$zodSchema } from "../../models/updatewalletop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateWalletRequest$zodSchema,
};

export const tool$walletsUpdateWallet: ToolDefinition<typeof args> = {
  name: "wallets-update-wallet",
  description: `Update a wallet

Use when changing wallet settings (e.g. enabling or updating auto top-up thresholds).`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await walletsUpdateWallet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
