/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { walletsTopUpWallet } from "../../funcs/walletsTopUpWallet.js";
import { TopUpWalletRequest$zodSchema } from "../../models/topupwalletop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TopUpWalletRequest$zodSchema,
};

export const tool$walletsTopUpWallet: ToolDefinition<typeof args> = {
  name: "wallets-top-up-wallet",
  description: `Top up wallet

Use when adding funds to a wallet (e.g. top-up, refund, or manual credit). Supports optional idempotency via reference.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await walletsTopUpWallet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
