/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksHandleNomodWebhook } from "../../funcs/webhooksHandleNomodWebhook.js";
import { HandleNomodWebhookRequest$zodSchema } from "../../models/handlenomodwebhookop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: HandleNomodWebhookRequest$zodSchema,
};

export const tool$webhooksHandleNomodWebhook: ToolDefinition<typeof args> = {
  name: "webhooks-handle-nomod-webhook",
  description: `Handle Nomod webhook events

Use as the Nomod webhook endpoint URL. Receives payment and invoice events from Nomod to keep FlexPrice in sync.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await webhooksHandleNomodWebhook(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
