/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksHandleQuickbooksWebhook } from "../../funcs/webhooksHandleQuickbooksWebhook.js";
import { HandleQuickbooksWebhookRequest$zodSchema } from "../../models/handlequickbookswebhookop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: HandleQuickbooksWebhookRequest$zodSchema,
};

export const tool$webhooksHandleQuickbooksWebhook: ToolDefinition<typeof args> =
  {
    name: "webhooks-handle-quickbooks-webhook",
    description: `Handle QuickBooks webhook events

Use as the QuickBooks webhook endpoint URL. Receives payment events from QuickBooks to sync payment status into FlexPrice.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await webhooksHandleQuickbooksWebhook(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
