/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksHandleMoyasarWebhook } from "../../funcs/webhooksHandleMoyasarWebhook.js";
import { HandleMoyasarWebhookRequest$zodSchema } from "../../models/handlemoyasarwebhookop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: HandleMoyasarWebhookRequest$zodSchema,
};

export const tool$webhooksHandleMoyasarWebhook: ToolDefinition<typeof args> = {
  name: "webhooks-handle-moyasar-webhook",
  description: `Handle Moyasar webhook events

Use as the Moyasar webhook endpoint URL. Receives payment events from Moyasar to update payment status in FlexPrice.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await webhooksHandleMoyasarWebhook(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
