/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksHandleStripeWebhook } from "../../funcs/webhooksHandleStripeWebhook.js";
import { HandleStripeWebhookRequest$zodSchema } from "../../models/handlestripewebhookop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: HandleStripeWebhookRequest$zodSchema,
};

export const tool$webhooksHandleStripeWebhook: ToolDefinition<typeof args> = {
  name: "webhooks-handle-stripe-webhook",
  description: `Handle Stripe webhook events

Use as the Stripe webhook endpoint URL. Receives payment and customer events from Stripe to keep FlexPrice in sync (e.g. payment succeeded, customer created).`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await webhooksHandleStripeWebhook(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
