/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { FlexpriceCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool, registerDynamicTools } from "./tools.js";
import { tool$addonsCreateAddon } from "./tools/addonsCreateAddon.js";
import { tool$addonsDeleteAddon } from "./tools/addonsDeleteAddon.js";
import { tool$addonsGetAddon } from "./tools/addonsGetAddon.js";
import { tool$addonsGetAddonByLookupKey } from "./tools/addonsGetAddonByLookupKey.js";
import { tool$addonsQueryAddon } from "./tools/addonsQueryAddon.js";
import { tool$addonsUpdateAddon } from "./tools/addonsUpdateAddon.js";
import { tool$alertsQueryAlertLog } from "./tools/alertsQueryAlertLog.js";
import { tool$costsCreateCostsheet } from "./tools/costsCreateCostsheet.js";
import { tool$costsDeleteCostsheet } from "./tools/costsDeleteCostsheet.js";
import { tool$costsGetActiveCostsheet } from "./tools/costsGetActiveCostsheet.js";
import { tool$costsGetCostsheet } from "./tools/costsGetCostsheet.js";
import { tool$costsGetDetailedCostAnalytics } from "./tools/costsGetDetailedCostAnalytics.js";
import { tool$costsGetDetailedCostAnalyticsV2 } from "./tools/costsGetDetailedCostAnalyticsV2.js";
import { tool$costsQueryCostsheet } from "./tools/costsQueryCostsheet.js";
import { tool$costsUpdateCostsheet } from "./tools/costsUpdateCostsheet.js";
import { tool$couponsCreateCoupon } from "./tools/couponsCreateCoupon.js";
import { tool$couponsDeleteCoupon } from "./tools/couponsDeleteCoupon.js";
import { tool$couponsGetCoupon } from "./tools/couponsGetCoupon.js";
import { tool$couponsQueryCoupon } from "./tools/couponsQueryCoupon.js";
import { tool$couponsUpdateCoupon } from "./tools/couponsUpdateCoupon.js";
import { tool$creditGrantsCreateCreditGrant } from "./tools/creditGrantsCreateCreditGrant.js";
import { tool$creditGrantsDeleteCreditGrant } from "./tools/creditGrantsDeleteCreditGrant.js";
import { tool$creditGrantsGetCreditGrant } from "./tools/creditGrantsGetCreditGrant.js";
import { tool$creditGrantsGetPlanCreditGrants } from "./tools/creditGrantsGetPlanCreditGrants.js";
import { tool$creditGrantsUpdateCreditGrant } from "./tools/creditGrantsUpdateCreditGrant.js";
import { tool$creditNotesCreateCreditNote } from "./tools/creditNotesCreateCreditNote.js";
import { tool$creditNotesGetCreditNote } from "./tools/creditNotesGetCreditNote.js";
import { tool$creditNotesProcessCreditNote } from "./tools/creditNotesProcessCreditNote.js";
import { tool$creditNotesVoidCreditNote } from "./tools/creditNotesVoidCreditNote.js";
import { tool$customersCreateCustomer } from "./tools/customersCreateCustomer.js";
import { tool$customersDeleteCustomer } from "./tools/customersDeleteCustomer.js";
import { tool$customersGetCustomer } from "./tools/customersGetCustomer.js";
import { tool$customersGetCustomerByExternalId } from "./tools/customersGetCustomerByExternalId.js";
import { tool$customersGetCustomerEntitlements } from "./tools/customersGetCustomerEntitlements.js";
import { tool$customersGetCustomerUpcomingGrants } from "./tools/customersGetCustomerUpcomingGrants.js";
import { tool$customersGetCustomerUsageSummary } from "./tools/customersGetCustomerUsageSummary.js";
import { tool$customersQueryCustomer } from "./tools/customersQueryCustomer.js";
import { tool$customersUpdateCustomer } from "./tools/customersUpdateCustomer.js";
import { tool$entitlementsCreateEntitlement } from "./tools/entitlementsCreateEntitlement.js";
import { tool$entitlementsCreateEntitlementsBulk } from "./tools/entitlementsCreateEntitlementsBulk.js";
import { tool$entitlementsDeleteEntitlement } from "./tools/entitlementsDeleteEntitlement.js";
import { tool$entitlementsGetAddonEntitlements } from "./tools/entitlementsGetAddonEntitlements.js";
import { tool$entitlementsGetEntitlement } from "./tools/entitlementsGetEntitlement.js";
import { tool$entitlementsGetPlanEntitlements } from "./tools/entitlementsGetPlanEntitlements.js";
import { tool$entitlementsQueryEntitlement } from "./tools/entitlementsQueryEntitlement.js";
import { tool$entitlementsUpdateEntitlement } from "./tools/entitlementsUpdateEntitlement.js";
import { tool$entityIntegrationMappingsCreateEntityIntegrationMapping } from "./tools/entityIntegrationMappingsCreateEntityIntegrationMapping.js";
import { tool$entityIntegrationMappingsDeleteEntityIntegrationMapping } from "./tools/entityIntegrationMappingsDeleteEntityIntegrationMapping.js";
import { tool$environmentsCreateEnvironment } from "./tools/environmentsCreateEnvironment.js";
import { tool$environmentsUpdateEnvironment } from "./tools/environmentsUpdateEnvironment.js";
import { tool$eventsGetEvent } from "./tools/eventsGetEvent.js";
import { tool$eventsGetHuggingfaceInferenceData } from "./tools/eventsGetHuggingfaceInferenceData.js";
import { tool$eventsGetUsageAnalytics } from "./tools/eventsGetUsageAnalytics.js";
import { tool$eventsGetUsageByMeter } from "./tools/eventsGetUsageByMeter.js";
import { tool$eventsGetUsageStatistics } from "./tools/eventsGetUsageStatistics.js";
import { tool$eventsIngestEvent } from "./tools/eventsIngestEvent.js";
import { tool$eventsIngestEventsBulk } from "./tools/eventsIngestEventsBulk.js";
import { tool$eventsListRawEvents } from "./tools/eventsListRawEvents.js";
import { tool$featuresCreateFeature } from "./tools/featuresCreateFeature.js";
import { tool$featuresDeleteFeature } from "./tools/featuresDeleteFeature.js";
import { tool$featuresQueryFeature } from "./tools/featuresQueryFeature.js";
import { tool$featuresUpdateFeature } from "./tools/featuresUpdateFeature.js";
import { tool$groupsCreateGroup } from "./tools/groupsCreateGroup.js";
import { tool$groupsDeleteGroup } from "./tools/groupsDeleteGroup.js";
import { tool$groupsGetGroup } from "./tools/groupsGetGroup.js";
import { tool$groupsQueryGroup } from "./tools/groupsQueryGroup.js";
import { tool$integrationsCreateOrUpdateIntegration } from "./tools/integrationsCreateOrUpdateIntegration.js";
import { tool$integrationsDeleteIntegration } from "./tools/integrationsDeleteIntegration.js";
import { tool$integrationsGetIntegration } from "./tools/integrationsGetIntegration.js";
import { tool$integrationsListLinkedIntegrations } from "./tools/integrationsListLinkedIntegrations.js";
import { tool$invoicesAttemptInvoicePayment } from "./tools/invoicesAttemptInvoicePayment.js";
import { tool$invoicesCreateInvoice } from "./tools/invoicesCreateInvoice.js";
import { tool$invoicesFinalizeInvoice } from "./tools/invoicesFinalizeInvoice.js";
import { tool$invoicesGetCustomerInvoiceSummary } from "./tools/invoicesGetCustomerInvoiceSummary.js";
import { tool$invoicesGetInvoice } from "./tools/invoicesGetInvoice.js";
import { tool$invoicesGetInvoicePdf } from "./tools/invoicesGetInvoicePdf.js";
import { tool$invoicesGetInvoicePreview } from "./tools/invoicesGetInvoicePreview.js";
import { tool$invoicesQueryInvoice } from "./tools/invoicesQueryInvoice.js";
import { tool$invoicesRecalculateInvoice } from "./tools/invoicesRecalculateInvoice.js";
import { tool$invoicesTriggerInvoiceCommsWebhook } from "./tools/invoicesTriggerInvoiceCommsWebhook.js";
import { tool$invoicesUpdateInvoice } from "./tools/invoicesUpdateInvoice.js";
import { tool$invoicesUpdateInvoicePaymentStatus } from "./tools/invoicesUpdateInvoicePaymentStatus.js";
import { tool$invoicesVoidInvoice } from "./tools/invoicesVoidInvoice.js";
import { tool$paymentsCreatePayment } from "./tools/paymentsCreatePayment.js";
import { tool$paymentsDeletePayment } from "./tools/paymentsDeletePayment.js";
import { tool$paymentsGetPayment } from "./tools/paymentsGetPayment.js";
import { tool$paymentsListPayments } from "./tools/paymentsListPayments.js";
import { tool$paymentsProcessPayment } from "./tools/paymentsProcessPayment.js";
import { tool$paymentsUpdatePayment } from "./tools/paymentsUpdatePayment.js";
import { tool$plansCreatePlan } from "./tools/plansCreatePlan.js";
import { tool$plansDeletePlan } from "./tools/plansDeletePlan.js";
import { tool$plansGetPlan } from "./tools/plansGetPlan.js";
import { tool$plansPostPlansIdClone } from "./tools/plansPostPlansIdClone.js";
import { tool$plansQueryPlan } from "./tools/plansQueryPlan.js";
import { tool$plansSyncPlanPrices } from "./tools/plansSyncPlanPrices.js";
import { tool$plansUpdatePlan } from "./tools/plansUpdatePlan.js";
import { tool$pricesCreatePrice } from "./tools/pricesCreatePrice.js";
import { tool$pricesCreatePricesBulk } from "./tools/pricesCreatePricesBulk.js";
import { tool$pricesDeletePrice } from "./tools/pricesDeletePrice.js";
import { tool$pricesGetPrice } from "./tools/pricesGetPrice.js";
import { tool$pricesGetPriceByLookupKey } from "./tools/pricesGetPriceByLookupKey.js";
import { tool$pricesQueryPrice } from "./tools/pricesQueryPrice.js";
import { tool$pricesUpdatePrice } from "./tools/pricesUpdatePrice.js";
import { tool$priceUnitsCreatePriceUnit } from "./tools/priceUnitsCreatePriceUnit.js";
import { tool$priceUnitsDeletePriceUnit } from "./tools/priceUnitsDeletePriceUnit.js";
import { tool$priceUnitsGetPriceUnit } from "./tools/priceUnitsGetPriceUnit.js";
import { tool$priceUnitsGetPriceUnitByCode } from "./tools/priceUnitsGetPriceUnitByCode.js";
import { tool$priceUnitsListPriceUnits } from "./tools/priceUnitsListPriceUnits.js";
import { tool$priceUnitsQueryPriceUnit } from "./tools/priceUnitsQueryPriceUnit.js";
import { tool$priceUnitsUpdatePriceUnit } from "./tools/priceUnitsUpdatePriceUnit.js";
import { tool$rbacGetRBACRole } from "./tools/rbacGetRBACRole.js";
import { tool$rbacListRBACRoles } from "./tools/rbacListRBACRoles.js";
import { tool$scheduledTasksCreateScheduledTask } from "./tools/scheduledTasksCreateScheduledTask.js";
import { tool$scheduledTasksDeleteScheduledTask } from "./tools/scheduledTasksDeleteScheduledTask.js";
import { tool$scheduledTasksGetScheduledTask } from "./tools/scheduledTasksGetScheduledTask.js";
import { tool$scheduledTasksListScheduledTasks } from "./tools/scheduledTasksListScheduledTasks.js";
import { tool$scheduledTasksScheduleUpdateBillingPeriod } from "./tools/scheduledTasksScheduleUpdateBillingPeriod.js";
import { tool$scheduledTasksTriggerScheduledTaskRun } from "./tools/scheduledTasksTriggerScheduledTaskRun.js";
import { tool$scheduledTasksUpdateScheduledTask } from "./tools/scheduledTasksUpdateScheduledTask.js";
import { tool$secretsCreateApiKey } from "./tools/secretsCreateApiKey.js";
import { tool$secretsDeleteApiKey } from "./tools/secretsDeleteApiKey.js";
import { tool$secretsListApiKeys } from "./tools/secretsListApiKeys.js";
import { tool$subscriptionsActivateSubscription } from "./tools/subscriptionsActivateSubscription.js";
import { tool$subscriptionsAddSubscriptionAddon } from "./tools/subscriptionsAddSubscriptionAddon.js";
import { tool$subscriptionsCancelSubscription } from "./tools/subscriptionsCancelSubscription.js";
import { tool$subscriptionsCancelSubscriptionSchedule } from "./tools/subscriptionsCancelSubscriptionSchedule.js";
import { tool$subscriptionsCreateSubscription } from "./tools/subscriptionsCreateSubscription.js";
import { tool$subscriptionsCreateSubscriptionLineItem } from "./tools/subscriptionsCreateSubscriptionLineItem.js";
import { tool$subscriptionsDeleteSubscriptionLineItem } from "./tools/subscriptionsDeleteSubscriptionLineItem.js";
import { tool$subscriptionsExecuteSubscriptionChange } from "./tools/subscriptionsExecuteSubscriptionChange.js";
import { tool$subscriptionsGetSubscription } from "./tools/subscriptionsGetSubscription.js";
import { tool$subscriptionsGetSubscriptionAddonAssociations } from "./tools/subscriptionsGetSubscriptionAddonAssociations.js";
import { tool$subscriptionsGetSubscriptionEntitlements } from "./tools/subscriptionsGetSubscriptionEntitlements.js";
import { tool$subscriptionsGetSubscriptionSchedule } from "./tools/subscriptionsGetSubscriptionSchedule.js";
import { tool$subscriptionsGetSubscriptionUpcomingGrants } from "./tools/subscriptionsGetSubscriptionUpcomingGrants.js";
import { tool$subscriptionsGetSubscriptionUsage } from "./tools/subscriptionsGetSubscriptionUsage.js";
import { tool$subscriptionsGetSubscriptionV2 } from "./tools/subscriptionsGetSubscriptionV2.js";
import { tool$subscriptionsListAllSubscriptionSchedules } from "./tools/subscriptionsListAllSubscriptionSchedules.js";
import { tool$subscriptionsListSubscriptionPauses } from "./tools/subscriptionsListSubscriptionPauses.js";
import { tool$subscriptionsListSubscriptionSchedules } from "./tools/subscriptionsListSubscriptionSchedules.js";
import { tool$subscriptionsPauseSubscription } from "./tools/subscriptionsPauseSubscription.js";
import { tool$subscriptionsPreviewSubscriptionChange } from "./tools/subscriptionsPreviewSubscriptionChange.js";
import { tool$subscriptionsQuerySubscription } from "./tools/subscriptionsQuerySubscription.js";
import { tool$subscriptionsRemoveSubscriptionAddon } from "./tools/subscriptionsRemoveSubscriptionAddon.js";
import { tool$subscriptionsResumeSubscription } from "./tools/subscriptionsResumeSubscription.js";
import { tool$subscriptionsUpdateSubscription } from "./tools/subscriptionsUpdateSubscription.js";
import { tool$subscriptionsUpdateSubscriptionLineItem } from "./tools/subscriptionsUpdateSubscriptionLineItem.js";
import { tool$tasksCreateTask } from "./tools/tasksCreateTask.js";
import { tool$tasksDownloadTaskExport } from "./tools/tasksDownloadTaskExport.js";
import { tool$tasksGetTask } from "./tools/tasksGetTask.js";
import { tool$tasksGetTaskResult } from "./tools/tasksGetTaskResult.js";
import { tool$tasksListTasks } from "./tools/tasksListTasks.js";
import { tool$tasksUpdateTaskStatus } from "./tools/tasksUpdateTaskStatus.js";
import { tool$taxAssociationsCreateTaxAssociation } from "./tools/taxAssociationsCreateTaxAssociation.js";
import { tool$taxAssociationsDeleteTaxAssociation } from "./tools/taxAssociationsDeleteTaxAssociation.js";
import { tool$taxAssociationsGetTaxAssociation } from "./tools/taxAssociationsGetTaxAssociation.js";
import { tool$taxAssociationsListTaxAssociations } from "./tools/taxAssociationsListTaxAssociations.js";
import { tool$taxAssociationsUpdateTaxAssociation } from "./tools/taxAssociationsUpdateTaxAssociation.js";
import { tool$taxRatesCreateTaxRate } from "./tools/taxRatesCreateTaxRate.js";
import { tool$taxRatesDeleteTaxRate } from "./tools/taxRatesDeleteTaxRate.js";
import { tool$taxRatesGetTaxRate } from "./tools/taxRatesGetTaxRate.js";
import { tool$taxRatesGetTaxRates } from "./tools/taxRatesGetTaxRates.js";
import { tool$taxRatesUpdateTaxRate } from "./tools/taxRatesUpdateTaxRate.js";
import { tool$tenantsGetTenantBillingUsage } from "./tools/tenantsGetTenantBillingUsage.js";
import { tool$tenantsGetTenantById } from "./tools/tenantsGetTenantById.js";
import { tool$tenantsUpdateTenant } from "./tools/tenantsUpdateTenant.js";
import { tool$usersCreateUser } from "./tools/usersCreateUser.js";
import { tool$usersGetUserInfo } from "./tools/usersGetUserInfo.js";
import { tool$usersQueryUser } from "./tools/usersQueryUser.js";
import { tool$walletsCreateWallet } from "./tools/walletsCreateWallet.js";
import { tool$walletsGetCustomerWallets } from "./tools/walletsGetCustomerWallets.js";
import { tool$walletsGetWallet } from "./tools/walletsGetWallet.js";
import { tool$walletsGetWalletBalance } from "./tools/walletsGetWalletBalance.js";
import { tool$walletsGetWalletsByCustomerId } from "./tools/walletsGetWalletsByCustomerId.js";
import { tool$walletsGetWalletTransactions } from "./tools/walletsGetWalletTransactions.js";
import { tool$walletsQueryWallet } from "./tools/walletsQueryWallet.js";
import { tool$walletsQueryWalletTransaction } from "./tools/walletsQueryWalletTransaction.js";
import { tool$walletsTerminateWallet } from "./tools/walletsTerminateWallet.js";
import { tool$walletsTopUpWallet } from "./tools/walletsTopUpWallet.js";
import { tool$walletsUpdateWallet } from "./tools/walletsUpdateWallet.js";
import { tool$webhooksHandleChargebeeWebhook } from "./tools/webhooksHandleChargebeeWebhook.js";
import { tool$webhooksHandleHubspotWebhook } from "./tools/webhooksHandleHubspotWebhook.js";
import { tool$webhooksHandleMoyasarWebhook } from "./tools/webhooksHandleMoyasarWebhook.js";
import { tool$webhooksHandleNomodWebhook } from "./tools/webhooksHandleNomodWebhook.js";
import { tool$webhooksHandleQuickbooksWebhook } from "./tools/webhooksHandleQuickbooksWebhook.js";
import { tool$webhooksHandleRazorpayWebhook } from "./tools/webhooksHandleRazorpayWebhook.js";
import { tool$webhooksHandleStripeWebhook } from "./tools/webhooksHandleStripeWebhook.js";
import { tool$workflowsQueryWorkflow } from "./tools/workflowsQueryWorkflow.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  dynamic?: boolean | undefined;
  scopes?: MCPScope[] | undefined;
  getSDK?: () => FlexpriceCore;
  serverURL: string;
  security?: SDKOptions["security"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "Flexprice",
    version: "0.0.43",
  });

  const getClient = deps.getSDK || (() =>
    new FlexpriceCore({
      security: deps.security,
      serverURL: deps.serverURL,
      serverIdx: deps.serverIdx,
      debugLogger: deps.logger.level === "debug"
        ? {
          log: (...args) => console.log(...args),
          group: (...args) => console.group(...args),
          groupEnd: (...args) => console.groupEnd(...args),
        }
        : undefined,
    }));

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const [tool, tools, toolMap] = createRegisterTool(
    deps.logger,
    server,
    getClient,
    scopes,
    allowedTools,
    deps.dynamic,
  );
  const resource = createRegisterResource(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, getClient, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$addonsCreateAddon);
  tool(tool$addonsGetAddonByLookupKey);
  tool(tool$addonsQueryAddon);
  tool(tool$addonsGetAddon);
  tool(tool$addonsUpdateAddon);
  tool(tool$addonsDeleteAddon);
  tool(tool$entitlementsGetAddonEntitlements);
  tool(tool$entitlementsCreateEntitlement);
  tool(tool$entitlementsCreateEntitlementsBulk);
  tool(tool$entitlementsQueryEntitlement);
  tool(tool$entitlementsGetEntitlement);
  tool(tool$entitlementsUpdateEntitlement);
  tool(tool$entitlementsDeleteEntitlement);
  tool(tool$entitlementsGetPlanEntitlements);
  tool(tool$alertsQueryAlertLog);
  tool(tool$costsCreateCostsheet);
  tool(tool$costsGetActiveCostsheet);
  tool(tool$costsGetDetailedCostAnalytics);
  tool(tool$costsGetDetailedCostAnalyticsV2);
  tool(tool$costsQueryCostsheet);
  tool(tool$costsGetCostsheet);
  tool(tool$costsUpdateCostsheet);
  tool(tool$costsDeleteCostsheet);
  tool(tool$couponsCreateCoupon);
  tool(tool$couponsQueryCoupon);
  tool(tool$couponsGetCoupon);
  tool(tool$couponsUpdateCoupon);
  tool(tool$couponsDeleteCoupon);
  tool(tool$creditGrantsCreateCreditGrant);
  tool(tool$creditGrantsGetCreditGrant);
  tool(tool$creditGrantsUpdateCreditGrant);
  tool(tool$creditGrantsDeleteCreditGrant);
  tool(tool$creditGrantsGetPlanCreditGrants);
  tool(tool$creditNotesCreateCreditNote);
  tool(tool$creditNotesGetCreditNote);
  tool(tool$creditNotesProcessCreditNote);
  tool(tool$creditNotesVoidCreditNote);
  tool(tool$customersUpdateCustomer);
  tool(tool$customersCreateCustomer);
  tool(tool$customersGetCustomerByExternalId);
  tool(tool$customersQueryCustomer);
  tool(tool$customersGetCustomerUsageSummary);
  tool(tool$customersGetCustomer);
  tool(tool$customersDeleteCustomer);
  tool(tool$customersGetCustomerEntitlements);
  tool(tool$customersGetCustomerUpcomingGrants);
  tool(tool$walletsGetCustomerWallets);
  tool(tool$walletsGetWalletsByCustomerId);
  tool(tool$walletsCreateWallet);
  tool(tool$walletsQueryWallet);
  tool(tool$walletsQueryWalletTransaction);
  tool(tool$walletsGetWallet);
  tool(tool$walletsUpdateWallet);
  tool(tool$walletsGetWalletBalance);
  tool(tool$walletsTerminateWallet);
  tool(tool$walletsTopUpWallet);
  tool(tool$walletsGetWalletTransactions);
  tool(tool$invoicesGetCustomerInvoiceSummary);
  tool(tool$invoicesCreateInvoice);
  tool(tool$invoicesGetInvoicePreview);
  tool(tool$invoicesQueryInvoice);
  tool(tool$invoicesGetInvoice);
  tool(tool$invoicesUpdateInvoice);
  tool(tool$invoicesTriggerInvoiceCommsWebhook);
  tool(tool$invoicesFinalizeInvoice);
  tool(tool$invoicesUpdateInvoicePaymentStatus);
  tool(tool$invoicesAttemptInvoicePayment);
  tool(tool$invoicesGetInvoicePdf);
  tool(tool$invoicesRecalculateInvoice);
  tool(tool$invoicesVoidInvoice);
  tool(tool$entityIntegrationMappingsCreateEntityIntegrationMapping);
  tool(tool$entityIntegrationMappingsDeleteEntityIntegrationMapping);
  tool(tool$environmentsCreateEnvironment);
  tool(tool$environmentsUpdateEnvironment);
  tool(tool$eventsIngestEvent);
  tool(tool$eventsGetUsageAnalytics);
  tool(tool$eventsIngestEventsBulk);
  tool(tool$eventsGetHuggingfaceInferenceData);
  tool(tool$eventsListRawEvents);
  tool(tool$eventsGetUsageStatistics);
  tool(tool$eventsGetUsageByMeter);
  tool(tool$eventsGetEvent);
  tool(tool$featuresCreateFeature);
  tool(tool$featuresQueryFeature);
  tool(tool$featuresUpdateFeature);
  tool(tool$featuresDeleteFeature);
  tool(tool$groupsCreateGroup);
  tool(tool$groupsQueryGroup);
  tool(tool$groupsGetGroup);
  tool(tool$groupsDeleteGroup);
  tool(tool$paymentsListPayments);
  tool(tool$paymentsCreatePayment);
  tool(tool$paymentsGetPayment);
  tool(tool$paymentsUpdatePayment);
  tool(tool$paymentsDeletePayment);
  tool(tool$paymentsProcessPayment);
  tool(tool$plansCreatePlan);
  tool(tool$plansQueryPlan);
  tool(tool$plansGetPlan);
  tool(tool$plansUpdatePlan);
  tool(tool$plansDeletePlan);
  tool(tool$plansPostPlansIdClone);
  tool(tool$plansSyncPlanPrices);
  tool(tool$pricesCreatePrice);
  tool(tool$pricesCreatePricesBulk);
  tool(tool$pricesGetPriceByLookupKey);
  tool(tool$pricesQueryPrice);
  tool(tool$pricesGetPrice);
  tool(tool$pricesUpdatePrice);
  tool(tool$pricesDeletePrice);
  tool(tool$priceUnitsListPriceUnits);
  tool(tool$priceUnitsCreatePriceUnit);
  tool(tool$priceUnitsGetPriceUnitByCode);
  tool(tool$priceUnitsQueryPriceUnit);
  tool(tool$priceUnitsGetPriceUnit);
  tool(tool$priceUnitsUpdatePriceUnit);
  tool(tool$priceUnitsDeletePriceUnit);
  tool(tool$rbacListRBACRoles);
  tool(tool$rbacGetRBACRole);
  tool(tool$secretsListApiKeys);
  tool(tool$secretsCreateApiKey);
  tool(tool$secretsDeleteApiKey);
  tool(tool$integrationsGetIntegration);
  tool(tool$integrationsCreateOrUpdateIntegration);
  tool(tool$integrationsListLinkedIntegrations);
  tool(tool$integrationsDeleteIntegration);
  tool(tool$subscriptionsCreateSubscription);
  tool(tool$subscriptionsAddSubscriptionAddon);
  tool(tool$subscriptionsRemoveSubscriptionAddon);
  tool(tool$subscriptionsUpdateSubscriptionLineItem);
  tool(tool$subscriptionsDeleteSubscriptionLineItem);
  tool(tool$subscriptionsQuerySubscription);
  tool(tool$subscriptionsGetSubscriptionUsage);
  tool(tool$subscriptionsGetSubscription);
  tool(tool$subscriptionsUpdateSubscription);
  tool(tool$subscriptionsActivateSubscription);
  tool(tool$subscriptionsGetSubscriptionAddonAssociations);
  tool(tool$subscriptionsCancelSubscription);
  tool(tool$subscriptionsExecuteSubscriptionChange);
  tool(tool$subscriptionsPreviewSubscriptionChange);
  tool(tool$subscriptionsGetSubscriptionEntitlements);
  tool(tool$subscriptionsGetSubscriptionUpcomingGrants);
  tool(tool$subscriptionsCreateSubscriptionLineItem);
  tool(tool$subscriptionsPauseSubscription);
  tool(tool$subscriptionsListSubscriptionPauses);
  tool(tool$subscriptionsResumeSubscription);
  tool(tool$subscriptionsGetSubscriptionV2);
  tool(tool$subscriptionsListAllSubscriptionSchedules);
  tool(tool$subscriptionsGetSubscriptionSchedule);
  tool(tool$subscriptionsCancelSubscriptionSchedule);
  tool(tool$subscriptionsListSubscriptionSchedules);
  tool(tool$tasksListTasks);
  tool(tool$tasksCreateTask);
  tool(tool$tasksGetTaskResult);
  tool(tool$tasksGetTask);
  tool(tool$tasksDownloadTaskExport);
  tool(tool$tasksUpdateTaskStatus);
  tool(tool$scheduledTasksListScheduledTasks);
  tool(tool$scheduledTasksCreateScheduledTask);
  tool(tool$scheduledTasksScheduleUpdateBillingPeriod);
  tool(tool$scheduledTasksGetScheduledTask);
  tool(tool$scheduledTasksUpdateScheduledTask);
  tool(tool$scheduledTasksDeleteScheduledTask);
  tool(tool$scheduledTasksTriggerScheduledTaskRun);
  tool(tool$taxAssociationsListTaxAssociations);
  tool(tool$taxAssociationsCreateTaxAssociation);
  tool(tool$taxAssociationsGetTaxAssociation);
  tool(tool$taxAssociationsUpdateTaxAssociation);
  tool(tool$taxAssociationsDeleteTaxAssociation);
  tool(tool$taxRatesGetTaxRates);
  tool(tool$taxRatesCreateTaxRate);
  tool(tool$taxRatesGetTaxRate);
  tool(tool$taxRatesUpdateTaxRate);
  tool(tool$taxRatesDeleteTaxRate);
  tool(tool$tenantsGetTenantBillingUsage);
  tool(tool$tenantsUpdateTenant);
  tool(tool$tenantsGetTenantById);
  tool(tool$usersCreateUser);
  tool(tool$usersGetUserInfo);
  tool(tool$usersQueryUser);
  tool(tool$webhooksHandleChargebeeWebhook);
  tool(tool$webhooksHandleHubspotWebhook);
  tool(tool$webhooksHandleMoyasarWebhook);
  tool(tool$webhooksHandleNomodWebhook);
  tool(tool$webhooksHandleQuickbooksWebhook);
  tool(tool$webhooksHandleRazorpayWebhook);
  tool(tool$webhooksHandleStripeWebhook);
  tool(tool$workflowsQueryWorkflow);

  if (deps.dynamic) {
    registerDynamicTools(deps.logger, server, getClient, toolMap, scopes);
  }

  return { server, tools };
}
