/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoActivateDraftSubscriptionRequest,
  DtoActivateDraftSubscriptionRequest$zodSchema,
} from "./dtoactivatedraftsubscriptionrequest.js";
import {
  DtoSubscriptionResponse,
  DtoSubscriptionResponse$zodSchema,
} from "./dtosubscriptionresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type ActivateSubscriptionRequest = {
  id: string;
  body: DtoActivateDraftSubscriptionRequest;
};

export const ActivateSubscriptionRequest$zodSchema: z.ZodType<
  ActivateSubscriptionRequest
> = z.object({
  body: DtoActivateDraftSubscriptionRequest$zodSchema,
  id: z.string().describe("Subscription ID"),
});

export type ActivateSubscriptionResponse =
  | DtoSubscriptionResponse
  | ErrorsErrorResponse;

export const ActivateSubscriptionResponse$zodSchema: z.ZodType<
  ActivateSubscriptionResponse
> = z.union([
  DtoSubscriptionResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
