/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const AddonType = {
  Onetime: "onetime",
  MultipleInstance: "multiple_instance",
} as const;
export type AddonType = ClosedEnum<typeof AddonType>;

export const AddonType$zodSchema = z.enum([
  "onetime",
  "multiple_instance",
]);
