/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoInvoiceResponse,
  DtoInvoiceResponse$zodSchema,
} from "./dtoinvoiceresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type CreateInvoiceResponse = DtoInvoiceResponse | ErrorsErrorResponse;

export const CreateInvoiceResponse$zodSchema: z.ZodType<CreateInvoiceResponse> =
  z.union([
    DtoInvoiceResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
