/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCouponResponse,
  DtoCouponResponse$zodSchema,
} from "./dtocouponresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type CreateCouponResponse = DtoCouponResponse | ErrorsErrorResponse;

export const CreateCouponResponse$zodSchema: z.ZodType<CreateCouponResponse> = z
  .union([
    DtoCouponResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
