/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCreateAPIKeyResponse,
  DtoCreateAPIKeyResponse$zodSchema,
} from "./dtocreateapikeyresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type CreateApiKeyResponse =
  | DtoCreateAPIKeyResponse
  | ErrorsErrorResponse;

export const CreateApiKeyResponse$zodSchema: z.ZodType<CreateApiKeyResponse> = z
  .union([
    DtoCreateAPIKeyResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
