/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCreateAddonResponse,
  DtoCreateAddonResponse$zodSchema,
} from "./dtocreateaddonresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type CreateAddonResponse = DtoCreateAddonResponse | ErrorsErrorResponse;

export const CreateAddonResponse$zodSchema: z.ZodType<CreateAddonResponse> = z
  .union([
    DtoCreateAddonResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
