/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoFeatureResponse,
  DtoFeatureResponse$zodSchema,
} from "./dtofeatureresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type CreateFeatureResponse = DtoFeatureResponse | ErrorsErrorResponse;

export const CreateFeatureResponse$zodSchema: z.ZodType<CreateFeatureResponse> =
  z.union([
    DtoFeatureResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
