/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCustomerResponse,
  DtoCustomerResponse$zodSchema,
} from "./dtocustomerresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type CreateCustomerResponse = DtoCustomerResponse | ErrorsErrorResponse;

export const CreateCustomerResponse$zodSchema: z.ZodType<
  CreateCustomerResponse
> = z.union([
  DtoCustomerResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
