/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCreatePriceUnitResponse,
  DtoCreatePriceUnitResponse$zodSchema,
} from "./dtocreatepriceunitresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type CreatePriceUnitResponse =
  | DtoCreatePriceUnitResponse
  | ErrorsErrorResponse;

export const CreatePriceUnitResponse$zodSchema: z.ZodType<
  CreatePriceUnitResponse
> = z.union([
  DtoCreatePriceUnitResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
