/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";

export type CreditnoteCreditNoteLineItem = {
  amount?: string | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  credit_note_id?: string | undefined;
  currency?: string | undefined;
  display_name?: string | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  invoice_line_item_id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  status?: TypesStatus | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const CreditnoteCreditNoteLineItem$zodSchema: z.ZodType<
  CreditnoteCreditNoteLineItem
> = z.object({
  amount: z.string().optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  credit_note_id: z.string().optional(),
  currency: z.string().optional(),
  display_name: z.string().optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  invoice_line_item_id: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  status: TypesStatus$zodSchema.optional(),
  tenant_id: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
});
