/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoDeleteCreditGrantRequest,
  DtoDeleteCreditGrantRequest$zodSchema,
} from "./dtodeletecreditgrantrequest.js";
import {
  DtoSuccessResponse,
  DtoSuccessResponse$zodSchema,
} from "./dtosuccessresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type DeleteCreditGrantRequest = {
  id: string;
  body?: DtoDeleteCreditGrantRequest | undefined;
};

export const DeleteCreditGrantRequest$zodSchema: z.ZodType<
  DeleteCreditGrantRequest
> = z.object({
  body: DtoDeleteCreditGrantRequest$zodSchema.optional(),
  id: z.string().describe("Credit Grant ID"),
});

export type DeleteCreditGrantResponse =
  | DtoSuccessResponse
  | ErrorsErrorResponse;

export const DeleteCreditGrantResponse$zodSchema: z.ZodType<
  DeleteCreditGrantResponse
> = z.union([
  DtoSuccessResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
