/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteScheduledTaskRequest = { id: string };

export const DeleteScheduledTaskRequest$zodSchema: z.ZodType<
  DeleteScheduledTaskRequest
> = z.object({
  id: z.string().describe("Scheduled Task ID"),
});
