/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteIntegrationRequest = { id: string };

export const DeleteIntegrationRequest$zodSchema: z.ZodType<
  DeleteIntegrationRequest
> = z.object({
  id: z.string().describe("Integration ID"),
});
