/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoDeleteSubscriptionLineItemRequest,
  DtoDeleteSubscriptionLineItemRequest$zodSchema,
} from "./dtodeletesubscriptionlineitemrequest.js";
import {
  DtoSubscriptionLineItemResponse,
  DtoSubscriptionLineItemResponse$zodSchema,
} from "./dtosubscriptionlineitemresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type DeleteSubscriptionLineItemRequest = {
  id: string;
  body: DtoDeleteSubscriptionLineItemRequest;
};

export const DeleteSubscriptionLineItemRequest$zodSchema: z.ZodType<
  DeleteSubscriptionLineItemRequest
> = z.object({
  body: DtoDeleteSubscriptionLineItemRequest$zodSchema,
  id: z.string().describe("Line Item ID"),
});

export type DeleteSubscriptionLineItemResponse =
  | DtoSubscriptionLineItemResponse
  | ErrorsErrorResponse;

export const DeleteSubscriptionLineItemResponse$zodSchema: z.ZodType<
  DeleteSubscriptionLineItemResponse
> = z.union([
  DtoSubscriptionLineItemResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
