/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoTaxAssociationResponse,
  DtoTaxAssociationResponse$zodSchema,
} from "./dtotaxassociationresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type DeleteTaxAssociationRequest = { id: string };

export const DeleteTaxAssociationRequest$zodSchema: z.ZodType<
  DeleteTaxAssociationRequest
> = z.object({
  id: z.string().describe("Tax Config ID"),
});

export type DeleteTaxAssociationResponse =
  | DtoTaxAssociationResponse
  | ErrorsErrorResponse;

export const DeleteTaxAssociationResponse$zodSchema: z.ZodType<
  DeleteTaxAssociationResponse
> = z.union([
  DtoTaxAssociationResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
