/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoSuccessResponse,
  DtoSuccessResponse$zodSchema,
} from "./dtosuccessresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type DeletePriceUnitRequest = { id: string };

export const DeletePriceUnitRequest$zodSchema: z.ZodType<
  DeletePriceUnitRequest
> = z.object({
  id: z.string().describe("Price unit ID"),
});

export type DeletePriceUnitResponse = DtoSuccessResponse | ErrorsErrorResponse;

export const DeletePriceUnitResponse$zodSchema: z.ZodType<
  DeletePriceUnitResponse
> = z.union([
  DtoSuccessResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
