/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoDeleteCostsheetResponse,
  DtoDeleteCostsheetResponse$zodSchema,
} from "./dtodeletecostsheetresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type DeleteCostsheetRequest = { id: string };

export const DeleteCostsheetRequest$zodSchema: z.ZodType<
  DeleteCostsheetRequest
> = z.object({
  id: z.string().describe("Costsheet ID"),
});

export type DeleteCostsheetResponse =
  | DtoDeleteCostsheetResponse
  | ErrorsErrorResponse;

export const DeleteCostsheetResponse$zodSchema: z.ZodType<
  DeleteCostsheetResponse
> = z.union([
  DtoDeleteCostsheetResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
