/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoDeletePriceRequest,
  DtoDeletePriceRequest$zodSchema,
} from "./dtodeletepricerequest.js";
import {
  DtoSuccessResponse,
  DtoSuccessResponse$zodSchema,
} from "./dtosuccessresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type DeletePriceRequest = { id: string; body: DtoDeletePriceRequest };

export const DeletePriceRequest$zodSchema: z.ZodType<DeletePriceRequest> = z
  .object({
    body: DtoDeletePriceRequest$zodSchema,
    id: z.string().describe("Price ID"),
  });

export type DeletePriceResponse = DtoSuccessResponse | ErrorsErrorResponse;

export const DeletePriceResponse$zodSchema: z.ZodType<DeletePriceResponse> = z
  .union([
    DtoSuccessResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
