/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type DeleteCouponRequest = { id: string };

export const DeleteCouponRequest$zodSchema: z.ZodType<DeleteCouponRequest> = z
  .object({
    id: z.string().describe("Coupon ID"),
  });

export type DeleteCouponResponse =
  | { [k: string]: string }
  | ErrorsErrorResponse;

export const DeleteCouponResponse$zodSchema: z.ZodType<DeleteCouponResponse> = z
  .union([
    z.record(z.string(), z.string()).describe("OK"),
    ErrorsErrorResponse$zodSchema,
  ]);
