/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteTaxRateRequest = { id: string };

export const DeleteTaxRateRequest$zodSchema: z.ZodType<DeleteTaxRateRequest> = z
  .object({
    id: z.string().describe("Tax rate ID"),
  });
