/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type DownloadTaskExportRequest = { id: string };

export const DownloadTaskExportRequest$zodSchema: z.ZodType<
  DownloadTaskExportRequest
> = z.object({
  id: z.string().describe("Task ID"),
});

export type DownloadTaskExportResponse =
  | { [k: string]: string }
  | ErrorsErrorResponse;

export const DownloadTaskExportResponse$zodSchema: z.ZodType<
  DownloadTaskExportResponse
> = z.union([
  z.record(z.string(), z.string()).describe("OK"),
  ErrorsErrorResponse$zodSchema,
]);
