/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoActivateDraftSubscriptionRequest = { start_date: string };

export const DtoActivateDraftSubscriptionRequest$zodSchema: z.ZodType<
  DtoActivateDraftSubscriptionRequest
> = z.object({
  start_date: z.string(),
});
