/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoLineItemCommitmentConfig,
  DtoLineItemCommitmentConfig$zodSchema,
} from "./dtolineitemcommitmentconfig.js";

export type DtoAddAddonToSubscriptionRequest = {
  addon_id: string;
  line_item_commitments?:
    | { [k: string]: DtoLineItemCommitmentConfig }
    | undefined;
  metadata?: { [k: string]: any } | undefined;
  start_date?: string | undefined;
};

export const DtoAddAddonToSubscriptionRequest$zodSchema: z.ZodType<
  DtoAddAddonToSubscriptionRequest
> = z.object({
  addon_id: z.string(),
  line_item_commitments: z.record(
    z.string(),
    DtoLineItemCommitmentConfig$zodSchema,
  ).optional(),
  metadata: z.record(z.string(), z.any()).optional(),
  start_date: z.string().optional(),
});
