/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCustomerResponse,
  DtoCustomerResponse$zodSchema,
} from "./dtocustomerresponse.js";
import {
  DtoFeatureResponse,
  DtoFeatureResponse$zodSchema,
} from "./dtofeatureresponse.js";
import {
  DtoWalletResponse,
  DtoWalletResponse$zodSchema,
} from "./dtowalletresponse.js";
import {
  TypesAlertEntityType,
  TypesAlertEntityType$zodSchema,
} from "./typesalertentitytype.js";
import { TypesAlertInfo, TypesAlertInfo$zodSchema } from "./typesalertinfo.js";
import {
  TypesAlertState,
  TypesAlertState$zodSchema,
} from "./typesalertstate.js";
import { TypesAlertType, TypesAlertType$zodSchema } from "./typesalerttype.js";

export type DtoAlertLogResponse = {
  alert_info?: TypesAlertInfo | undefined;
  alert_status?: TypesAlertState | undefined;
  alert_type?: TypesAlertType | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  customer?: DtoCustomerResponse | undefined;
  customer_id?: string | undefined;
  entity_id?: string | undefined;
  entity_type?: TypesAlertEntityType | undefined;
  environment_id?: string | undefined;
  feature?: DtoFeatureResponse | undefined;
  id?: string | undefined;
  parent_entity_id?: string | undefined;
  parent_entity_type?: string | undefined;
  status?: string | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
  wallet?: DtoWalletResponse | undefined;
};

export const DtoAlertLogResponse$zodSchema: z.ZodType<DtoAlertLogResponse> = z
  .object({
    alert_info: TypesAlertInfo$zodSchema.optional(),
    alert_status: TypesAlertState$zodSchema.optional(),
    alert_type: TypesAlertType$zodSchema.optional(),
    created_at: z.string().optional(),
    created_by: z.string().optional(),
    customer: DtoCustomerResponse$zodSchema.optional(),
    customer_id: z.string().optional(),
    entity_id: z.string().optional(),
    entity_type: TypesAlertEntityType$zodSchema.optional(),
    environment_id: z.string().optional(),
    feature: DtoFeatureResponse$zodSchema.optional(),
    id: z.string().optional(),
    parent_entity_id: z.string().optional(),
    parent_entity_type: z.string().optional(),
    status: z.string().optional(),
    tenant_id: z.string().optional(),
    updated_at: z.string().optional(),
    updated_by: z.string().optional(),
    wallet: DtoWalletResponse$zodSchema.optional(),
  });
