/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesEntitlementUsageResetPeriod,
  TypesEntitlementUsageResetPeriod$zodSchema,
} from "./typesentitlementusageresetperiod.js";

export type DtoAggregatedEntitlement = {
  is_enabled?: boolean | undefined;
  is_soft_limit?: boolean | undefined;
  static_values?: Array<string> | undefined;
  usage_limit?: number | undefined;
  usage_reset_period?: TypesEntitlementUsageResetPeriod | undefined;
};

export const DtoAggregatedEntitlement$zodSchema: z.ZodType<
  DtoAggregatedEntitlement
> = z.object({
  is_enabled: z.boolean().optional(),
  is_soft_limit: z.boolean().optional(),
  static_values: z.array(z.string()).optional(),
  usage_limit: z.int().optional(),
  usage_reset_period: TypesEntitlementUsageResetPeriod$zodSchema.optional(),
});
