/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesBillingCadence,
  TypesBillingCadence$zodSchema,
} from "./typesbillingcadence.js";
import {
  TypesBillingPeriod,
  TypesBillingPeriod$zodSchema,
} from "./typesbillingperiod.js";

export type DtoBillingCycleInfo = {
  billing_anchor?: string | undefined;
  billing_cadence?: TypesBillingCadence | undefined;
  billing_period?: TypesBillingPeriod | undefined;
  billing_period_count?: number | undefined;
  period_end?: string | undefined;
  period_start?: string | undefined;
};

export const DtoBillingCycleInfo$zodSchema: z.ZodType<DtoBillingCycleInfo> = z
  .object({
    billing_anchor: z.string().optional(),
    billing_cadence: TypesBillingCadence$zodSchema.optional(),
    billing_period: TypesBillingPeriod$zodSchema.optional(),
    billing_period_count: z.int().optional(),
    period_end: z.string().optional(),
    period_start: z.string().optional(),
  });
