/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoIngestEventRequest,
  DtoIngestEventRequest$zodSchema,
} from "./dtoingesteventrequest.js";

export type DtoBulkIngestEventRequest = {
  events: Array<DtoIngestEventRequest>;
};

export const DtoBulkIngestEventRequest$zodSchema: z.ZodType<
  DtoBulkIngestEventRequest
> = z.object({
  events: z.array(DtoIngestEventRequest$zodSchema),
});
