/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesCouponCadence,
  TypesCouponCadence$zodSchema,
} from "./typescouponcadence.js";
import {
  TypesCouponType,
  TypesCouponType$zodSchema,
} from "./typescoupontype.js";

export type DtoCreateCouponRequest = {
  amount_off?: string | undefined;
  cadence: TypesCouponCadence;
  currency?: string | undefined;
  duration_in_periods?: number | undefined;
  max_redemptions?: number | undefined;
  metadata?: { [k: string]: string } | undefined;
  name: string;
  percentage_off?: string | undefined;
  redeem_after?: string | undefined;
  redeem_before?: string | undefined;
  rules?: { [k: string]: any } | undefined;
  type: TypesCouponType;
};

export const DtoCreateCouponRequest$zodSchema: z.ZodType<
  DtoCreateCouponRequest
> = z.object({
  amount_off: z.string().optional(),
  cadence: TypesCouponCadence$zodSchema,
  currency: z.string().optional(),
  duration_in_periods: z.int().optional(),
  max_redemptions: z.int().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  name: z.string(),
  percentage_off: z.string().optional(),
  redeem_after: z.string().optional(),
  redeem_before: z.string().optional(),
  rules: z.record(z.string(), z.any()).optional(),
  type: TypesCouponType$zodSchema,
});
