/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoAggregatedFeature,
  DtoAggregatedFeature$zodSchema,
} from "./dtoaggregatedfeature.js";

export type DtoCustomerEntitlementsResponse = {
  customer_id?: string | undefined;
  features?: Array<DtoAggregatedFeature> | undefined;
};

export const DtoCustomerEntitlementsResponse$zodSchema: z.ZodType<
  DtoCustomerEntitlementsResponse
> = z.object({
  customer_id: z.string().optional(),
  features: z.array(DtoAggregatedFeature$zodSchema).optional(),
});
