/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  MeterAggregation,
  MeterAggregation$zodSchema,
} from "./meteraggregation.js";
import { MeterFilter, MeterFilter$zodSchema } from "./meterfilter.js";
import {
  TypesResetUsage,
  TypesResetUsage$zodSchema,
} from "./typesresetusage.js";

export type DtoCreateMeterRequest = {
  aggregation: MeterAggregation;
  event_name: string;
  filters?: Array<MeterFilter> | undefined;
  name: string;
  reset_usage: TypesResetUsage;
};

export const DtoCreateMeterRequest$zodSchema: z.ZodType<DtoCreateMeterRequest> =
  z.object({
    aggregation: MeterAggregation$zodSchema,
    event_name: z.string(),
    filters: z.array(MeterFilter$zodSchema).optional(),
    name: z.string(),
    reset_usage: TypesResetUsage$zodSchema,
  });
