/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesSubscriptionScheduleChangeType,
  TypesSubscriptionScheduleChangeType$zodSchema,
} from "./typessubscriptionschedulechangetype.js";

/**
 * Request to cancel a subscription schedule (supports two modes)
 */
export type DtoCancelScheduleRequest = {
  schedule_id?: string | undefined;
  schedule_type?: TypesSubscriptionScheduleChangeType | undefined;
  subscription_id?: string | undefined;
};

export const DtoCancelScheduleRequest$zodSchema: z.ZodType<
  DtoCancelScheduleRequest
> = z.object({
  schedule_id: z.string().optional(),
  schedule_type: TypesSubscriptionScheduleChangeType$zodSchema.optional(),
  subscription_id: z.string().optional(),
}).describe("Request to cancel a subscription schedule (supports two modes)");
