/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCreateMeterRequest,
  DtoCreateMeterRequest$zodSchema,
} from "./dtocreatemeterrequest.js";
import {
  TypesAlertSettings,
  TypesAlertSettings$zodSchema,
} from "./typesalertsettings.js";
import {
  TypesFeatureType,
  TypesFeatureType$zodSchema,
} from "./typesfeaturetype.js";

export type DtoCreateFeatureRequest = {
  alert_settings?: TypesAlertSettings | undefined;
  description?: string | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  meter?: DtoCreateMeterRequest | undefined;
  meter_id?: string | undefined;
  name: string;
  type: TypesFeatureType;
  unit_plural?: string | undefined;
  unit_singular?: string | undefined;
};

export const DtoCreateFeatureRequest$zodSchema: z.ZodType<
  DtoCreateFeatureRequest
> = z.object({
  alert_settings: TypesAlertSettings$zodSchema.optional(),
  description: z.string().optional(),
  lookup_key: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  meter: DtoCreateMeterRequest$zodSchema.optional(),
  meter_id: z.string().optional(),
  name: z.string(),
  type: TypesFeatureType$zodSchema,
  unit_plural: z.string().optional(),
  unit_singular: z.string().optional(),
});
