/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCostsheetResponse,
  DtoCostsheetResponse$zodSchema,
} from "./dtocostsheetresponse.js";

export type DtoCreateCostsheetResponse = {
  costsheet?: DtoCostsheetResponse | undefined;
};

export const DtoCreateCostsheetResponse$zodSchema: z.ZodType<
  DtoCreateCostsheetResponse
> = z.object({
  costsheet: DtoCostsheetResponse$zodSchema.optional(),
});
