/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoPriceResponse,
  DtoPriceResponse$zodSchema,
} from "./dtopriceresponse.js";

export type DtoCreateBulkPriceResponse = {
  items?: Array<DtoPriceResponse> | undefined;
};

export const DtoCreateBulkPriceResponse$zodSchema: z.ZodType<
  DtoCreateBulkPriceResponse
> = z.object({
  items: z.array(DtoPriceResponse$zodSchema).optional(),
});
