/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCreateEntitlementRequest,
  DtoCreateEntitlementRequest$zodSchema,
} from "./dtocreateentitlementrequest.js";

export type DtoCreateBulkEntitlementRequest = {
  items: Array<DtoCreateEntitlementRequest>;
};

export const DtoCreateBulkEntitlementRequest$zodSchema: z.ZodType<
  DtoCreateBulkEntitlementRequest
> = z.object({
  items: z.array(DtoCreateEntitlementRequest$zodSchema),
});
