/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";

export type DtoCreatePriceUnitResponse = {
  base_currency?: string | undefined;
  code?: string | undefined;
  conversion_rate?: string | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  status?: TypesStatus | undefined;
  symbol?: string | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const DtoCreatePriceUnitResponse$zodSchema: z.ZodType<
  DtoCreatePriceUnitResponse
> = z.object({
  base_currency: z.string().optional(),
  code: z.string().optional(),
  conversion_rate: z.string().optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  name: z.string().optional(),
  status: TypesStatus$zodSchema.optional(),
  symbol: z.string().optional(),
  tenant_id: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
});
