/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoCreatePriceTier = {
  flat_amount?: string | undefined;
  unit_amount: string;
  up_to?: number | undefined;
};

export const DtoCreatePriceTier$zodSchema: z.ZodType<DtoCreatePriceTier> = z
  .object({
    flat_amount: z.string().optional(),
    unit_amount: z.string(),
    up_to: z.int().optional(),
  });
