/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoSubscriptionPriceCreateRequest,
  DtoSubscriptionPriceCreateRequest$zodSchema,
} from "./dtosubscriptionpricecreaterequest.js";
import {
  TypesBillingPeriod,
  TypesBillingPeriod$zodSchema,
} from "./typesbillingperiod.js";
import {
  TypesCommitmentType,
  TypesCommitmentType$zodSchema,
} from "./typescommitmenttype.js";

export type DtoCreateSubscriptionLineItemRequest = {
  commitment_amount?: number | undefined;
  commitment_duration?: TypesBillingPeriod | undefined;
  commitment_overage_factor?: number | undefined;
  commitment_quantity?: number | undefined;
  commitment_true_up_enabled?: boolean | undefined;
  commitment_type?: TypesCommitmentType | undefined;
  commitment_windowed?: boolean | undefined;
  display_name?: string | undefined;
  end_date?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  price?: DtoSubscriptionPriceCreateRequest | undefined;
  price_id?: string | undefined;
  quantity?: number | undefined;
  start_date?: string | undefined;
  subscription_phase_id?: string | undefined;
};

export const DtoCreateSubscriptionLineItemRequest$zodSchema: z.ZodType<
  DtoCreateSubscriptionLineItemRequest
> = z.object({
  commitment_amount: z.number().optional(),
  commitment_duration: TypesBillingPeriod$zodSchema.optional(),
  commitment_overage_factor: z.number().optional(),
  commitment_quantity: z.number().optional(),
  commitment_true_up_enabled: z.boolean().optional(),
  commitment_type: TypesCommitmentType$zodSchema.optional(),
  commitment_windowed: z.boolean().optional(),
  display_name: z.string().optional(),
  end_date: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  price: DtoSubscriptionPriceCreateRequest$zodSchema.optional(),
  price_id: z.string().optional(),
  quantity: z.number().optional(),
  start_date: z.string().optional(),
  subscription_phase_id: z.string().optional(),
});
