/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesCreditGrantCadence,
  TypesCreditGrantCadence$zodSchema,
} from "./typescreditgrantcadence.js";
import {
  TypesCreditGrantExpiryDurationUnit,
  TypesCreditGrantExpiryDurationUnit$zodSchema,
} from "./typescreditgrantexpirydurationunit.js";
import {
  TypesCreditGrantExpiryType,
  TypesCreditGrantExpiryType$zodSchema,
} from "./typescreditgrantexpirytype.js";
import {
  TypesCreditGrantPeriod,
  TypesCreditGrantPeriod$zodSchema,
} from "./typescreditgrantperiod.js";
import {
  TypesCreditGrantScope,
  TypesCreditGrantScope$zodSchema,
} from "./typescreditgrantscope.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";

export type DtoCreditGrantResponse = {
  cadence?: TypesCreditGrantCadence | undefined;
  conversion_rate?: string | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  credit_grant_anchor?: string | undefined;
  credits?: string | undefined;
  end_date?: string | undefined;
  environment_id?: string | undefined;
  expiration_duration?: number | undefined;
  expiration_duration_unit?: TypesCreditGrantExpiryDurationUnit | undefined;
  expiration_type?: TypesCreditGrantExpiryType | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  period?: TypesCreditGrantPeriod | undefined;
  period_count?: number | undefined;
  plan_id?: string | undefined;
  priority?: number | undefined;
  scope?: TypesCreditGrantScope | undefined;
  start_date?: string | undefined;
  status?: TypesStatus | undefined;
  subscription_id?: string | undefined;
  tenant_id?: string | undefined;
  topup_conversion_rate?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const DtoCreditGrantResponse$zodSchema: z.ZodType<
  DtoCreditGrantResponse
> = z.object({
  cadence: TypesCreditGrantCadence$zodSchema.optional(),
  conversion_rate: z.string().optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  credit_grant_anchor: z.string().optional(),
  credits: z.string().optional(),
  end_date: z.string().optional(),
  environment_id: z.string().optional(),
  expiration_duration: z.int().optional(),
  expiration_duration_unit: TypesCreditGrantExpiryDurationUnit$zodSchema
    .optional(),
  expiration_type: TypesCreditGrantExpiryType$zodSchema.optional(),
  id: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  name: z.string().optional(),
  period: TypesCreditGrantPeriod$zodSchema.optional(),
  period_count: z.int().optional(),
  plan_id: z.string().optional(),
  priority: z.int().optional(),
  scope: TypesCreditGrantScope$zodSchema.optional(),
  start_date: z.string().optional(),
  status: TypesStatus$zodSchema.optional(),
  subscription_id: z.string().optional(),
  tenant_id: z.string().optional(),
  topup_conversion_rate: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
});
