/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoEntitlementResponse,
  DtoEntitlementResponse$zodSchema,
} from "./dtoentitlementresponse.js";
import {
  DtoPriceResponse,
  DtoPriceResponse$zodSchema,
} from "./dtopriceresponse.js";
import { TypesAddonType, TypesAddonType$zodSchema } from "./typesaddontype.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";

export type DtoCreateAddonResponse = {
  created_at?: string | undefined;
  created_by?: string | undefined;
  description?: string | undefined;
  entitlements?: Array<DtoEntitlementResponse> | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  name?: string | undefined;
  prices?: Array<DtoPriceResponse> | undefined;
  status?: TypesStatus | undefined;
  tenant_id?: string | undefined;
  type?: TypesAddonType | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const DtoCreateAddonResponse$zodSchema: z.ZodType<
  DtoCreateAddonResponse
> = z.object({
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  description: z.string().optional(),
  entitlements: z.array(DtoEntitlementResponse$zodSchema).optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  lookup_key: z.string().optional(),
  metadata: z.record(z.string(), z.any()).optional(),
  name: z.string().optional(),
  prices: z.array(DtoPriceResponse$zodSchema).optional(),
  status: TypesStatus$zodSchema.optional(),
  tenant_id: z.string().optional(),
  type: TypesAddonType$zodSchema.optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
});
