/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { TypesAddonType, TypesAddonType$zodSchema } from "./typesaddontype.js";

export type DtoCreateAddonRequest = {
  description?: string | undefined;
  lookup_key: string;
  metadata?: { [k: string]: any } | undefined;
  name: string;
  type: TypesAddonType;
};

export const DtoCreateAddonRequest$zodSchema: z.ZodType<DtoCreateAddonRequest> =
  z.object({
    description: z.string().optional(),
    lookup_key: z.string(),
    metadata: z.record(z.string(), z.any()).optional(),
    name: z.string(),
    type: TypesAddonType$zodSchema,
  });
