/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoPriceResponse,
  DtoPriceResponse$zodSchema,
} from "./dtopriceresponse.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";

export type DtoCostsheetResponse = {
  created_at?: string | undefined;
  created_by?: string | undefined;
  description?: string | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  prices?: Array<DtoPriceResponse> | undefined;
  status?: TypesStatus | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const DtoCostsheetResponse$zodSchema: z.ZodType<DtoCostsheetResponse> = z
  .object({
    created_at: z.string().optional(),
    created_by: z.string().optional(),
    description: z.string().optional(),
    environment_id: z.string().optional(),
    id: z.string().optional(),
    lookup_key: z.string().optional(),
    metadata: z.record(z.string(), z.string()).optional(),
    name: z.string().optional(),
    prices: z.array(DtoPriceResponse$zodSchema).optional(),
    status: TypesStatus$zodSchema.optional(),
    tenant_id: z.string().optional(),
    updated_at: z.string().optional(),
    updated_by: z.string().optional(),
  });
