/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoCreateGroupRequest = {
  entity_type: string;
  lookup_key: string;
  name: string;
};

export const DtoCreateGroupRequest$zodSchema: z.ZodType<DtoCreateGroupRequest> =
  z.object({
    entity_type: z.string(),
    lookup_key: z.string(),
    name: z.string(),
  });
