/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesScheduleStatus,
  TypesScheduleStatus$zodSchema,
} from "./typesschedulestatus.js";

/**
 * Confirmation of schedule cancellation
 */
export type DtoCancelScheduleResponse = {
  message?: string | undefined;
  status?: TypesScheduleStatus | undefined;
};

export const DtoCancelScheduleResponse$zodSchema: z.ZodType<
  DtoCancelScheduleResponse
> = z.object({
  message: z.string().optional(),
  status: TypesScheduleStatus$zodSchema.optional(),
}).describe("Confirmation of schedule cancellation");
