/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoBillingPeriodInfo,
  DtoBillingPeriodInfo$zodSchema,
} from "./dtobillingperiodinfo.js";
import {
  DtoFeatureUsageSummary,
  DtoFeatureUsageSummary$zodSchema,
} from "./dtofeatureusagesummary.js";
import {
  TypesPaginationResponse,
  TypesPaginationResponse$zodSchema,
} from "./typespaginationresponse.js";

export type DtoCustomerUsageSummaryResponse = {
  customer_id?: string | undefined;
  features?: Array<DtoFeatureUsageSummary> | undefined;
  pagination?: TypesPaginationResponse | undefined;
  period?: DtoBillingPeriodInfo | undefined;
};

export const DtoCustomerUsageSummaryResponse$zodSchema: z.ZodType<
  DtoCustomerUsageSummaryResponse
> = z.object({
  customer_id: z.string().optional(),
  features: z.array(DtoFeatureUsageSummary$zodSchema).optional(),
  pagination: TypesPaginationResponse$zodSchema.optional(),
  period: DtoBillingPeriodInfo$zodSchema.optional(),
});
