/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesCommitmentInfo,
  TypesCommitmentInfo$zodSchema,
} from "./typescommitmentinfo.js";

export type DtoCreateInvoiceLineItemRequest = {
  amount: string;
  commitment_info?: TypesCommitmentInfo | undefined;
  display_name?: string | undefined;
  entity_id?: string | undefined;
  entity_type?: string | undefined;
  invoice_level_discount?: string | undefined;
  line_item_discount?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  meter_display_name?: string | undefined;
  meter_id?: string | undefined;
  period_end?: string | undefined;
  period_start?: string | undefined;
  plan_display_name?: string | undefined;
  plan_id?: string | undefined;
  prepaid_credits_applied?: string | undefined;
  price_id?: string | undefined;
  price_type?: string | undefined;
  price_unit?: string | undefined;
  price_unit_amount?: string | undefined;
  quantity: string;
};

export const DtoCreateInvoiceLineItemRequest$zodSchema: z.ZodType<
  DtoCreateInvoiceLineItemRequest
> = z.object({
  amount: z.string(),
  commitment_info: TypesCommitmentInfo$zodSchema.optional(),
  display_name: z.string().optional(),
  entity_id: z.string().optional(),
  entity_type: z.string().optional(),
  invoice_level_discount: z.string().optional(),
  line_item_discount: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  meter_display_name: z.string().optional(),
  meter_id: z.string().optional(),
  period_end: z.string().optional(),
  period_start: z.string().optional(),
  plan_display_name: z.string().optional(),
  plan_id: z.string().optional(),
  prepaid_credits_applied: z.string().optional(),
  price_id: z.string().optional(),
  price_type: z.string().optional(),
  price_unit: z.string().optional(),
  price_unit_amount: z.string().optional(),
  quantity: z.string(),
});
