/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";

/**
 * Customer response object containing all customer information
 */
export type DtoCustomerResponse = {
  address_city?: string | undefined;
  address_country?: string | undefined;
  address_line1?: string | undefined;
  address_line2?: string | undefined;
  address_postal_code?: string | undefined;
  address_state?: string | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  email?: string | undefined;
  environment_id?: string | undefined;
  external_id?: string | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  parent_customer?: DtoCustomerResponse | undefined;
  parent_customer_id?: string | undefined;
  status?: TypesStatus | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const DtoCustomerResponse$zodSchema: z.ZodType<DtoCustomerResponse> = z
  .object({
    address_city: z.string().optional(),
    address_country: z.string().optional(),
    address_line1: z.string().optional(),
    address_line2: z.string().optional(),
    address_postal_code: z.string().optional(),
    address_state: z.string().optional(),
    created_at: z.string().optional(),
    created_by: z.string().optional(),
    email: z.string().optional(),
    environment_id: z.string().optional(),
    external_id: z.string().optional(),
    id: z.string().optional(),
    metadata: z.record(z.string(), z.string()).optional(),
    name: z.string().optional(),
    parent_customer: z.lazy(() => DtoCustomerResponse$zodSchema).optional(),
    parent_customer_id: z.string().optional(),
    status: TypesStatus$zodSchema.optional(),
    tenant_id: z.string().optional(),
    updated_at: z.string().optional(),
    updated_by: z.string().optional(),
  }).describe("Customer response object containing all customer information");
