/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesTaxRateEntityType,
  TypesTaxRateEntityType$zodSchema,
} from "./typestaxrateentitytype.js";

export type DtoCreateTaxAssociationRequest = {
  auto_apply?: boolean | undefined;
  currency?: string | undefined;
  entity_id: string;
  entity_type: TypesTaxRateEntityType;
  metadata?: { [k: string]: string } | undefined;
  priority?: number | undefined;
  tax_rate_code: string;
};

export const DtoCreateTaxAssociationRequest$zodSchema: z.ZodType<
  DtoCreateTaxAssociationRequest
> = z.object({
  auto_apply: z.boolean().optional(),
  currency: z.string().optional(),
  entity_id: z.string(),
  entity_type: TypesTaxRateEntityType$zodSchema,
  metadata: z.record(z.string(), z.string()).optional(),
  priority: z.int().optional(),
  tax_rate_code: z.string(),
});
