/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoCreateCostsheetRequest = {
  description?: string | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name: string;
};

export const DtoCreateCostsheetRequest$zodSchema: z.ZodType<
  DtoCreateCostsheetRequest
> = z.object({
  description: z.string().optional(),
  lookup_key: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  name: z.string(),
});
