/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";
import {
  GithubComFlexpriceFlexpriceInternalDomainCustomerCustomer,
  GithubComFlexpriceFlexpriceInternalDomainCustomerCustomer$zodSchema,
} from "./githubcomflexpriceflexpriceinternaldomaincustomercustomer.js";
import {
  TypesDebugTrackerStatus,
  TypesDebugTrackerStatus$zodSchema,
} from "./typesdebugtrackerstatus.js";

export type DtoCustomerLookupResult = {
  customer?:
    | GithubComFlexpriceFlexpriceInternalDomainCustomerCustomer
    | undefined;
  error?: ErrorsErrorResponse | undefined;
  status?: TypesDebugTrackerStatus | undefined;
};

export const DtoCustomerLookupResult$zodSchema: z.ZodType<
  DtoCustomerLookupResult
> = z.object({
  customer: GithubComFlexpriceFlexpriceInternalDomainCustomerCustomer$zodSchema
    .optional(),
  error: ErrorsErrorResponse$zodSchema.optional(),
  status: TypesDebugTrackerStatus$zodSchema.optional(),
});
