/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesCancelImmediatelyInvoicePolicy,
  TypesCancelImmediatelyInvoicePolicy$zodSchema,
} from "./typescancelimmediatelyinvoicepolicy.js";
import {
  TypesCancellationType,
  TypesCancellationType$zodSchema,
} from "./typescancellationtype.js";
import {
  TypesProrationBehavior,
  TypesProrationBehavior$zodSchema,
} from "./typesprorationbehavior.js";

export type DtoCancelSubscriptionRequest = {
  cancel_immediately_inovice_policy?:
    | TypesCancelImmediatelyInvoicePolicy
    | undefined;
  cancellation_type: TypesCancellationType;
  proration_behavior?: TypesProrationBehavior | undefined;
  reason?: string | undefined;
};

export const DtoCancelSubscriptionRequest$zodSchema: z.ZodType<
  DtoCancelSubscriptionRequest
> = z.object({
  cancel_immediately_inovice_policy:
    TypesCancelImmediatelyInvoicePolicy$zodSchema.optional(),
  cancellation_type: TypesCancellationType$zodSchema,
  proration_behavior: TypesProrationBehavior$zodSchema.optional(),
  reason: z.string().optional(),
});
