/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoEntitlementResponse,
  DtoEntitlementResponse$zodSchema,
} from "./dtoentitlementresponse.js";

export type DtoCreateBulkEntitlementResponse = {
  items?: Array<DtoEntitlementResponse> | undefined;
};

export const DtoCreateBulkEntitlementResponse$zodSchema: z.ZodType<
  DtoCreateBulkEntitlementResponse
> = z.object({
  items: z.array(DtoEntitlementResponse$zodSchema).optional(),
});
