/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoCreatePriceUnitRequest = {
  base_currency: string;
  code: string;
  conversion_rate: string;
  metadata?: { [k: string]: string } | undefined;
  name: string;
  symbol: string;
};

export const DtoCreatePriceUnitRequest$zodSchema: z.ZodType<
  DtoCreatePriceUnitRequest
> = z.object({
  base_currency: z.string(),
  code: z.string(),
  conversion_rate: z.string(),
  metadata: z.record(z.string(), z.string()).optional(),
  name: z.string(),
  symbol: z.string(),
});
