/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCreatePriceRequest,
  DtoCreatePriceRequest$zodSchema,
} from "./dtocreatepricerequest.js";

export type DtoCreateBulkPriceRequest = { items: Array<DtoCreatePriceRequest> };

export const DtoCreateBulkPriceRequest$zodSchema: z.ZodType<
  DtoCreateBulkPriceRequest
> = z.object({
  items: z.array(DtoCreatePriceRequest$zodSchema),
});
