/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesApplicationStatus,
  TypesApplicationStatus$zodSchema,
} from "./typesapplicationstatus.js";
import {
  TypesCreditGrantApplicationReason,
  TypesCreditGrantApplicationReason$zodSchema,
} from "./typescreditgrantapplicationreason.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";
import {
  TypesSubscriptionStatus,
  TypesSubscriptionStatus$zodSchema,
} from "./typessubscriptionstatus.js";

export type DtoCreditGrantApplicationResponse = {
  application_reason?: TypesCreditGrantApplicationReason | undefined;
  application_status?: TypesApplicationStatus | undefined;
  applied_at?: string | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  credit_grant_id?: string | undefined;
  credits?: number | undefined;
  environment_id?: string | undefined;
  failure_reason?: string | undefined;
  id?: string | undefined;
  idempotency_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  period_end?: string | undefined;
  period_start?: string | undefined;
  retry_count?: number | undefined;
  scheduled_for?: string | undefined;
  status?: TypesStatus | undefined;
  subscription_id?: string | undefined;
  subscription_status_at_application?: TypesSubscriptionStatus | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const DtoCreditGrantApplicationResponse$zodSchema: z.ZodType<
  DtoCreditGrantApplicationResponse
> = z.object({
  application_reason: TypesCreditGrantApplicationReason$zodSchema.optional(),
  application_status: TypesApplicationStatus$zodSchema.optional(),
  applied_at: z.string().optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  credit_grant_id: z.string().optional(),
  credits: z.number().optional(),
  environment_id: z.string().optional(),
  failure_reason: z.string().optional(),
  id: z.string().optional(),
  idempotency_key: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  period_end: z.string().optional(),
  period_start: z.string().optional(),
  retry_count: z.int().optional(),
  scheduled_for: z.string().optional(),
  status: TypesStatus$zodSchema.optional(),
  subscription_id: z.string().optional(),
  subscription_status_at_application: TypesSubscriptionStatus$zodSchema
    .optional(),
  tenant_id: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
});
