/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesCouponCadence,
  TypesCouponCadence$zodSchema,
} from "./typescouponcadence.js";
import {
  TypesCouponType,
  TypesCouponType$zodSchema,
} from "./typescoupontype.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";

export type DtoCouponResponse = {
  amount_off?: string | undefined;
  cadence?: TypesCouponCadence | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  currency?: string | undefined;
  duration_in_periods?: number | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  max_redemptions?: number | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  percentage_off?: string | undefined;
  redeem_after?: string | undefined;
  redeem_before?: string | undefined;
  rules?: { [k: string]: any } | undefined;
  status?: TypesStatus | undefined;
  tenant_id?: string | undefined;
  total_redemptions?: number | undefined;
  type?: TypesCouponType | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const DtoCouponResponse$zodSchema: z.ZodType<DtoCouponResponse> = z
  .object({
    amount_off: z.string().optional(),
    cadence: TypesCouponCadence$zodSchema.optional(),
    created_at: z.string().optional(),
    created_by: z.string().optional(),
    currency: z.string().optional(),
    duration_in_periods: z.int().optional(),
    environment_id: z.string().optional(),
    id: z.string().optional(),
    max_redemptions: z.int().optional(),
    metadata: z.record(z.string(), z.string()).optional(),
    name: z.string().optional(),
    percentage_off: z.string().optional(),
    redeem_after: z.string().optional(),
    redeem_before: z.string().optional(),
    rules: z.record(z.string(), z.any()).optional(),
    status: TypesStatus$zodSchema.optional(),
    tenant_id: z.string().optional(),
    total_redemptions: z.int().optional(),
    type: TypesCouponType$zodSchema.optional(),
    updated_at: z.string().optional(),
    updated_by: z.string().optional(),
  });
