/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesPaymentDestinationType,
  TypesPaymentDestinationType$zodSchema,
} from "./typespaymentdestinationtype.js";
import {
  TypesPaymentGatewayType,
  TypesPaymentGatewayType$zodSchema,
} from "./typespaymentgatewaytype.js";
import {
  TypesPaymentMethodType,
  TypesPaymentMethodType$zodSchema,
} from "./typespaymentmethodtype.js";

export type DtoCreatePaymentRequest = {
  amount: string;
  cancel_url?: string | undefined;
  currency: string;
  destination_id: string;
  destination_type: TypesPaymentDestinationType;
  idempotency_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  payment_gateway?: TypesPaymentGatewayType | undefined;
  payment_method_id?: string | undefined;
  payment_method_type: TypesPaymentMethodType;
  process_payment?: boolean | undefined;
  save_card_and_make_default?: boolean | undefined;
  success_url?: string | undefined;
};

export const DtoCreatePaymentRequest$zodSchema: z.ZodType<
  DtoCreatePaymentRequest
> = z.object({
  amount: z.string(),
  cancel_url: z.string().optional(),
  currency: z.string(),
  destination_id: z.string(),
  destination_type: TypesPaymentDestinationType$zodSchema,
  idempotency_key: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  payment_gateway: TypesPaymentGatewayType$zodSchema.optional(),
  payment_method_id: z.string().optional(),
  payment_method_type: TypesPaymentMethodType$zodSchema,
  process_payment: z.boolean().default(true),
  save_card_and_make_default: z.boolean().default(false),
  success_url: z.string().optional(),
});
