/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCustomerInvoiceSummary,
  DtoCustomerInvoiceSummary$zodSchema,
} from "./dtocustomerinvoicesummary.js";

export type DtoCustomerMultiCurrencyInvoiceSummary = {
  customer_id?: string | undefined;
  default_currency?: string | undefined;
  summaries?: Array<DtoCustomerInvoiceSummary> | undefined;
};

export const DtoCustomerMultiCurrencyInvoiceSummary$zodSchema: z.ZodType<
  DtoCustomerMultiCurrencyInvoiceSummary
> = z.object({
  customer_id: z.string().optional(),
  default_currency: z.string().optional(),
  summaries: z.array(DtoCustomerInvoiceSummary$zodSchema).optional(),
});
