/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesCreditGrantCadence,
  TypesCreditGrantCadence$zodSchema,
} from "./typescreditgrantcadence.js";
import {
  TypesCreditGrantExpiryDurationUnit,
  TypesCreditGrantExpiryDurationUnit$zodSchema,
} from "./typescreditgrantexpirydurationunit.js";
import {
  TypesCreditGrantExpiryType,
  TypesCreditGrantExpiryType$zodSchema,
} from "./typescreditgrantexpirytype.js";
import {
  TypesCreditGrantPeriod,
  TypesCreditGrantPeriod$zodSchema,
} from "./typescreditgrantperiod.js";
import {
  TypesCreditGrantScope,
  TypesCreditGrantScope$zodSchema,
} from "./typescreditgrantscope.js";

export type DtoCreateCreditGrantRequest = {
  cadence: TypesCreditGrantCadence;
  conversion_rate?: string | undefined;
  credits: string;
  end_date?: string | undefined;
  expiration_duration?: number | undefined;
  expiration_duration_unit?: TypesCreditGrantExpiryDurationUnit | undefined;
  expiration_type?: TypesCreditGrantExpiryType | undefined;
  metadata?: { [k: string]: string } | undefined;
  name: string;
  period?: TypesCreditGrantPeriod | undefined;
  period_count?: number | undefined;
  plan_id?: string | undefined;
  priority?: number | undefined;
  scope: TypesCreditGrantScope;
  start_date?: string | undefined;
  subscription_id?: string | undefined;
  topup_conversion_rate?: string | undefined;
};

export const DtoCreateCreditGrantRequest$zodSchema: z.ZodType<
  DtoCreateCreditGrantRequest
> = z.object({
  cadence: TypesCreditGrantCadence$zodSchema,
  conversion_rate: z.string().optional(),
  credits: z.string(),
  end_date: z.string().optional(),
  expiration_duration: z.int().optional(),
  expiration_duration_unit: TypesCreditGrantExpiryDurationUnit$zodSchema
    .optional(),
  expiration_type: TypesCreditGrantExpiryType$zodSchema.optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  name: z.string(),
  period: TypesCreditGrantPeriod$zodSchema.optional(),
  period_count: z.int().optional(),
  plan_id: z.string().optional(),
  priority: z.int().optional(),
  scope: TypesCreditGrantScope$zodSchema,
  start_date: z.string().optional(),
  subscription_id: z.string().optional(),
  topup_conversion_rate: z.string().optional(),
});
