/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoCostPoint = {
  cost?: string | undefined;
  event_count?: number | undefined;
  quantity?: string | undefined;
  timestamp?: string | undefined;
};

export const DtoCostPoint$zodSchema: z.ZodType<DtoCostPoint> = z.object({
  cost: z.string().optional(),
  event_count: z.int().optional(),
  quantity: z.string().optional(),
  timestamp: z.string().optional(),
});
