/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoDeleteCreditGrantRequest = {
  effective_date?: string | undefined;
};

export const DtoDeleteCreditGrantRequest$zodSchema: z.ZodType<
  DtoDeleteCreditGrantRequest
> = z.object({
  effective_date: z.string().optional(),
});
