/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCustomerLookupResult,
  DtoCustomerLookupResult$zodSchema,
} from "./dtocustomerlookupresult.js";
import {
  DtoMeterMatchingResult,
  DtoMeterMatchingResult$zodSchema,
} from "./dtometermatchingresult.js";
import {
  DtoPriceLookupResult,
  DtoPriceLookupResult$zodSchema,
} from "./dtopricelookupresult.js";
import {
  DtoSubscriptionLineItemLookupResult,
  DtoSubscriptionLineItemLookupResult$zodSchema,
} from "./dtosubscriptionlineitemlookupresult.js";
import {
  TypesFailurePoint,
  TypesFailurePoint$zodSchema,
} from "./typesfailurepoint.js";

export type DtoDebugTracker = {
  customer_lookup?: DtoCustomerLookupResult | undefined;
  failure_point?: TypesFailurePoint | undefined;
  meter_matching?: DtoMeterMatchingResult | undefined;
  price_lookup?: DtoPriceLookupResult | undefined;
  subscription_line_item_lookup?:
    | DtoSubscriptionLineItemLookupResult
    | undefined;
};

export const DtoDebugTracker$zodSchema: z.ZodType<DtoDebugTracker> = z.object({
  customer_lookup: DtoCustomerLookupResult$zodSchema.optional(),
  failure_point: TypesFailurePoint$zodSchema.optional(),
  meter_matching: DtoMeterMatchingResult$zodSchema.optional(),
  price_lookup: DtoPriceLookupResult$zodSchema.optional(),
  subscription_line_item_lookup: DtoSubscriptionLineItemLookupResult$zodSchema
    .optional(),
});
