/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoDeleteCostsheetResponse = {
  id?: string | undefined;
  message?: string | undefined;
};

export const DtoDeleteCostsheetResponse$zodSchema: z.ZodType<
  DtoDeleteCostsheetResponse
> = z.object({
  id: z.string().optional(),
  message: z.string().optional(),
});
