/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoEventCostInfo = {
  costNanoUsd?: string | undefined;
  requestId?: string | undefined;
};

export const DtoEventCostInfo$zodSchema: z.ZodType<DtoEventCostInfo> = z.object(
  {
    costNanoUsd: z.string().optional(),
    requestId: z.string().optional(),
  },
);
