/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoEnvironmentResponse = {
  created_at?: string | undefined;
  id?: string | undefined;
  name?: string | undefined;
  type?: string | undefined;
  updated_at?: string | undefined;
};

export const DtoEnvironmentResponse$zodSchema: z.ZodType<
  DtoEnvironmentResponse
> = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
  type: z.string().optional(),
  updated_at: z.string().optional(),
});
