/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoEntitlementSourceEntityType,
  DtoEntitlementSourceEntityType$zodSchema,
} from "./dtoentitlementsourceentitytype.js";
import {
  TypesBillingPeriod,
  TypesBillingPeriod$zodSchema,
} from "./typesbillingperiod.js";

export type DtoEntitlementSource = {
  entitlement_id?: string | undefined;
  entity_id?: string | undefined;
  entity_name?: string | undefined;
  entity_type?: DtoEntitlementSourceEntityType | undefined;
  is_enabled?: boolean | undefined;
  quantity?: number | undefined;
  static_value?: string | undefined;
  subscription_id?: string | undefined;
  usage_limit?: number | undefined;
  usage_reset_period?: TypesBillingPeriod | undefined;
};

export const DtoEntitlementSource$zodSchema: z.ZodType<DtoEntitlementSource> = z
  .object({
    entitlement_id: z.string().optional(),
    entity_id: z.string().optional(),
    entity_name: z.string().optional(),
    entity_type: DtoEntitlementSourceEntityType$zodSchema.optional(),
    is_enabled: z.boolean().optional(),
    quantity: z.int().optional(),
    static_value: z.string().optional(),
    subscription_id: z.string().optional(),
    usage_limit: z.int().optional(),
    usage_reset_period: TypesBillingPeriod$zodSchema.optional(),
  });
