/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoAddonResponse,
  DtoAddonResponse$zodSchema,
} from "./dtoaddonresponse.js";
import {
  DtoFeatureResponse,
  DtoFeatureResponse$zodSchema,
} from "./dtofeatureresponse.js";
import {
  DtoPlanResponse,
  DtoPlanResponse$zodSchema,
} from "./dtoplanresponse.js";
import {
  EntitlementEntityType,
  EntitlementEntityType$zodSchema,
} from "./entitlemententitytype.js";
import {
  EntitlementUsageResetPeriod,
  EntitlementUsageResetPeriod$zodSchema,
} from "./entitlementusageresetperiod.js";
import { FeatureType, FeatureType$zodSchema } from "./featuretype.js";
import { Status, Status$zodSchema } from "./status.js";

export type DtoEntitlementResponse = {
  addon?: DtoAddonResponse | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  display_order?: number | undefined;
  end_date?: string | undefined;
  entity_id?: string | undefined;
  entity_type?: EntitlementEntityType | undefined;
  environment_id?: string | undefined;
  feature?: DtoFeatureResponse | undefined;
  feature_id?: string | undefined;
  feature_type?: FeatureType | undefined;
  id?: string | undefined;
  is_enabled?: boolean | undefined;
  is_soft_limit?: boolean | undefined;
  parent_entitlement_id?: string | undefined;
  plan?: DtoPlanResponse | undefined;
  plan_id?: string | undefined;
  start_date?: string | undefined;
  static_value?: string | undefined;
  status?: Status | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
  usage_limit?: number | undefined;
  usage_reset_period?: EntitlementUsageResetPeriod | undefined;
};

export const DtoEntitlementResponse$zodSchema: z.ZodType<
  DtoEntitlementResponse
> = z.object({
  addon: z.lazy(() => DtoAddonResponse$zodSchema).optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  display_order: z.int().optional(),
  end_date: z.string().optional(),
  entity_id: z.string().optional(),
  entity_type: EntitlementEntityType$zodSchema.optional(),
  environment_id: z.string().optional(),
  feature: DtoFeatureResponse$zodSchema.optional(),
  feature_id: z.string().optional(),
  feature_type: FeatureType$zodSchema.optional(),
  id: z.string().optional(),
  is_enabled: z.boolean().optional(),
  is_soft_limit: z.boolean().optional(),
  parent_entitlement_id: z.string().optional(),
  plan: z.lazy(() => DtoPlanResponse$zodSchema).optional(),
  plan_id: z.string().optional(),
  start_date: z.string().optional(),
  static_value: z.string().optional(),
  status: Status$zodSchema.optional(),
  tenant_id: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
  usage_limit: z.int().optional(),
  usage_reset_period: EntitlementUsageResetPeriod$zodSchema.optional(),
});
