/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoEntitlementSource,
  DtoEntitlementSource$zodSchema,
} from "./dtoentitlementsource.js";
import {
  DtoFeatureResponse,
  DtoFeatureResponse$zodSchema,
} from "./dtofeatureresponse.js";

export type DtoFeatureUsageSummary = {
  current_usage?: string | undefined;
  feature?: DtoFeatureResponse | undefined;
  is_enabled?: boolean | undefined;
  is_soft_limit?: boolean | undefined;
  is_unlimited?: boolean | undefined;
  next_usage_reset_at?: string | undefined;
  sources?: Array<DtoEntitlementSource> | undefined;
  total_limit?: number | undefined;
  usage_percent?: string | undefined;
};

export const DtoFeatureUsageSummary$zodSchema: z.ZodType<
  DtoFeatureUsageSummary
> = z.object({
  current_usage: z.string().optional(),
  feature: DtoFeatureResponse$zodSchema.optional(),
  is_enabled: z.boolean().optional(),
  is_soft_limit: z.boolean().optional(),
  is_unlimited: z.boolean().optional(),
  next_usage_reset_at: z.string().optional(),
  sources: z.array(DtoEntitlementSource$zodSchema).optional(),
  total_limit: z.int().optional(),
  usage_percent: z.string().optional(),
});
