/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoMeterResponse,
  DtoMeterResponse$zodSchema,
} from "./dtometerresponse.js";
import {
  TypesAlertSettings,
  TypesAlertSettings$zodSchema,
} from "./typesalertsettings.js";
import {
  TypesFeatureType,
  TypesFeatureType$zodSchema,
} from "./typesfeaturetype.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";

export type DtoFeatureResponse = {
  alert_settings?: TypesAlertSettings | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  description?: string | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  meter?: DtoMeterResponse | undefined;
  meter_id?: string | undefined;
  name?: string | undefined;
  status?: TypesStatus | undefined;
  tenant_id?: string | undefined;
  type?: TypesFeatureType | undefined;
  unit_plural?: string | undefined;
  unit_singular?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const DtoFeatureResponse$zodSchema: z.ZodType<DtoFeatureResponse> = z
  .object({
    alert_settings: TypesAlertSettings$zodSchema.optional(),
    created_at: z.string().optional(),
    created_by: z.string().optional(),
    description: z.string().optional(),
    environment_id: z.string().optional(),
    id: z.string().optional(),
    lookup_key: z.string().optional(),
    metadata: z.record(z.string(), z.string()).optional(),
    meter: DtoMeterResponse$zodSchema.optional(),
    meter_id: z.string().optional(),
    name: z.string().optional(),
    status: TypesStatus$zodSchema.optional(),
    tenant_id: z.string().optional(),
    type: TypesFeatureType$zodSchema.optional(),
    unit_plural: z.string().optional(),
    unit_singular: z.string().optional(),
    updated_at: z.string().optional(),
    updated_by: z.string().optional(),
  });
