/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoSubscriptionScheduleResponse,
  DtoSubscriptionScheduleResponse$zodSchema,
} from "./dtosubscriptionscheduleresponse.js";

/**
 * List of pending schedules for a subscription
 */
export type DtoGetPendingSchedulesResponse = {
  count?: number | undefined;
  schedules?: Array<DtoSubscriptionScheduleResponse> | undefined;
};

export const DtoGetPendingSchedulesResponse$zodSchema: z.ZodType<
  DtoGetPendingSchedulesResponse
> = z.object({
  count: z.int().optional(),
  schedules: z.array(DtoSubscriptionScheduleResponse$zodSchema).optional(),
}).describe("List of pending schedules for a subscription");
