/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCostAnalyticItem,
  DtoCostAnalyticItem$zodSchema,
} from "./dtocostanalyticitem.js";

export type DtoGetDetailedCostAnalyticsResponse = {
  cost_analytics?: Array<DtoCostAnalyticItem> | undefined;
  currency?: string | undefined;
  end_time?: string | undefined;
  margin?: string | undefined;
  margin_percent?: string | undefined;
  roi?: string | undefined;
  roi_percent?: string | undefined;
  start_time?: string | undefined;
  total_cost?: string | undefined;
  total_revenue?: string | undefined;
};

export const DtoGetDetailedCostAnalyticsResponse$zodSchema: z.ZodType<
  DtoGetDetailedCostAnalyticsResponse
> = z.object({
  cost_analytics: z.array(DtoCostAnalyticItem$zodSchema).optional(),
  currency: z.string().optional(),
  end_time: z.string().optional(),
  margin: z.string().optional(),
  margin_percent: z.string().optional(),
  roi: z.string().optional(),
  roi_percent: z.string().optional(),
  start_time: z.string().optional(),
  total_cost: z.string().optional(),
  total_revenue: z.string().optional(),
});
