/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoSubscriptionUsageByMetersResponse,
  DtoSubscriptionUsageByMetersResponse$zodSchema,
} from "./dtosubscriptionusagebymetersresponse.js";

export type DtoGetUsageBySubscriptionResponse = {
  amount?: number | undefined;
  charges?: Array<DtoSubscriptionUsageByMetersResponse> | undefined;
  commitment_amount?: number | undefined;
  commitment_utilized?: number | undefined;
  currency?: string | undefined;
  display_amount?: string | undefined;
  end_time?: string | undefined;
  has_overage?: boolean | undefined;
  overage_amount?: number | undefined;
  overage_factor?: number | undefined;
  start_time?: string | undefined;
};

export const DtoGetUsageBySubscriptionResponse$zodSchema: z.ZodType<
  DtoGetUsageBySubscriptionResponse
> = z.object({
  amount: z.number().optional(),
  charges: z.array(DtoSubscriptionUsageByMetersResponse$zodSchema).optional(),
  commitment_amount: z.number().optional(),
  commitment_utilized: z.number().optional(),
  currency: z.string().optional(),
  display_amount: z.string().optional(),
  end_time: z.string().optional(),
  has_overage: z.boolean().optional(),
  overage_amount: z.number().optional(),
  overage_factor: z.number().optional(),
  start_time: z.string().optional(),
});
