/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoDebugTracker,
  DtoDebugTracker$zodSchema,
} from "./dtodebugtracker.js";
import { DtoEvent, DtoEvent$zodSchema } from "./dtoevent.js";
import {
  DtoFeatureUsageInfo,
  DtoFeatureUsageInfo$zodSchema,
} from "./dtofeatureusageinfo.js";
import {
  EventProcessingStatusType,
  EventProcessingStatusType$zodSchema,
} from "./eventprocessingstatustype.js";

export type DtoGetEventByIDResponse = {
  debug_tracker?: DtoDebugTracker | undefined;
  event?: DtoEvent | undefined;
  processed_events?: Array<DtoFeatureUsageInfo> | undefined;
  status?: EventProcessingStatusType | undefined;
};

export const DtoGetEventByIDResponse$zodSchema: z.ZodType<
  DtoGetEventByIDResponse
> = z.object({
  debug_tracker: DtoDebugTracker$zodSchema.optional(),
  event: DtoEvent$zodSchema.optional(),
  processed_events: z.array(DtoFeatureUsageInfo$zodSchema).optional(),
  status: EventProcessingStatusType$zodSchema.optional(),
});
