/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { WindowSize, WindowSize$zodSchema } from "./windowsize.js";

export type DtoGetUsageByMeterRequest = {
  billing_anchor?: string | undefined;
  bucket_size?: WindowSize | undefined;
  customer_id?: string | undefined;
  end_time?: string | undefined;
  external_customer_id?: string | undefined;
  filters?: { [k: string]: Array<string> } | undefined;
  meter_id: string;
  start_time?: string | undefined;
  window_size?: WindowSize | undefined;
};

export const DtoGetUsageByMeterRequest$zodSchema: z.ZodType<
  DtoGetUsageByMeterRequest
> = z.object({
  billing_anchor: z.string().optional(),
  bucket_size: WindowSize$zodSchema.optional(),
  customer_id: z.string().optional(),
  end_time: z.string().optional(),
  external_customer_id: z.string().optional(),
  filters: z.record(z.string(), z.array(z.string())).optional(),
  meter_id: z.string(),
  start_time: z.string().optional(),
  window_size: WindowSize$zodSchema.optional(),
});
