/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { DtoUsageResult, DtoUsageResult$zodSchema } from "./dtousageresult.js";
import {
  TypesAggregationType,
  TypesAggregationType$zodSchema,
} from "./typesaggregationtype.js";

export type DtoGetUsageResponse = {
  event_name?: string | undefined;
  results?: Array<DtoUsageResult> | undefined;
  type?: TypesAggregationType | undefined;
  value?: number | undefined;
};

export const DtoGetUsageResponse$zodSchema: z.ZodType<DtoGetUsageResponse> = z
  .object({
    event_name: z.string().optional(),
    results: z.array(DtoUsageResult$zodSchema).optional(),
    type: TypesAggregationType$zodSchema.optional(),
    value: z.number().optional(),
  });
