/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AggregationType,
  AggregationType$zodSchema,
} from "./aggregationtype.js";
import { WindowSize, WindowSize$zodSchema } from "./windowsize.js";

export type DtoGetUsageRequest = {
  aggregation_type: AggregationType;
  billing_anchor?: string | undefined;
  bucket_size?: WindowSize | undefined;
  customer_id?: string | undefined;
  end_time?: string | undefined;
  event_name: string;
  external_customer_id?: string | undefined;
  filters?: { [k: string]: Array<string> } | undefined;
  group_by_property?: string | undefined;
  multiplier?: string | undefined;
  property_name?: string | undefined;
  start_time?: string | undefined;
  window_size?: WindowSize | undefined;
};

export const DtoGetUsageRequest$zodSchema: z.ZodType<DtoGetUsageRequest> = z
  .object({
    aggregation_type: AggregationType$zodSchema,
    billing_anchor: z.string().optional(),
    bucket_size: WindowSize$zodSchema.optional(),
    customer_id: z.string().optional(),
    end_time: z.string().optional(),
    event_name: z.string(),
    external_customer_id: z.string().optional(),
    filters: z.record(z.string(), z.array(z.string())).optional(),
    group_by_property: z.string().optional(),
    multiplier: z.string().optional(),
    property_name: z.string().optional(),
    start_time: z.string().optional(),
    window_size: WindowSize$zodSchema.optional(),
  });
