/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesWindowSize,
  TypesWindowSize$zodSchema,
} from "./typeswindowsize.js";

export type DtoGetUsageAnalyticsRequest = {
  end_time?: string | undefined;
  expand?: Array<string> | undefined;
  external_customer_id: string;
  feature_ids?: Array<string> | undefined;
  group_by?: Array<string> | undefined;
  property_filters?: { [k: string]: Array<string> } | undefined;
  sources?: Array<string> | undefined;
  start_time?: string | undefined;
  window_size?: TypesWindowSize | undefined;
};

export const DtoGetUsageAnalyticsRequest$zodSchema: z.ZodType<
  DtoGetUsageAnalyticsRequest
> = z.object({
  end_time: z.string().optional(),
  expand: z.array(z.string()).optional(),
  external_customer_id: z.string(),
  feature_ids: z.array(z.string()).optional(),
  group_by: z.array(z.string()).optional(),
  property_filters: z.record(z.string(), z.array(z.string())).optional(),
  sources: z.array(z.string()).optional(),
  start_time: z.string().optional(),
  window_size: TypesWindowSize$zodSchema.optional(),
});
