/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoGetUsageBySubscriptionRequest = {
  end_time?: string | undefined;
  lifetime_usage?: boolean | undefined;
  start_time?: string | undefined;
  subscription_id: string;
};

export const DtoGetUsageBySubscriptionRequest$zodSchema: z.ZodType<
  DtoGetUsageBySubscriptionRequest
> = z.object({
  end_time: z.string().optional(),
  lifetime_usage: z.boolean().optional(),
  start_time: z.string().optional(),
  subscription_id: z.string(),
});
