/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * provider is the integration provider name (e.g., "stripe", "razorpay")
 */
export const Provider = {
  Stripe: "stripe",
  Razorpay: "razorpay",
  Paypal: "paypal",
} as const;
/**
 * provider is the integration provider name (e.g., "stripe", "razorpay")
 */
export type Provider = ClosedEnum<typeof Provider>;

export const Provider$zodSchema = z.enum([
  "stripe",
  "razorpay",
  "paypal",
]).describe(
  "provider is the integration provider name (e.g., \"stripe\", \"razorpay\")",
);

/**
 * Integration entity mapping for external provider systems
 */
export type DtoIntegrationEntityMapping = { id: string; provider: Provider };

export const DtoIntegrationEntityMapping$zodSchema: z.ZodType<
  DtoIntegrationEntityMapping
> = z.object({
  id: z.string(),
  provider: Provider$zodSchema,
}).describe("Integration entity mapping for external provider systems");
