/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoInvoiceLineItemPreview = {
  amount?: string | undefined;
  description?: string | undefined;
  is_proration?: boolean | undefined;
  period_end?: string | undefined;
  period_start?: string | undefined;
  quantity?: string | undefined;
  unit_price?: string | undefined;
};

export const DtoInvoiceLineItemPreview$zodSchema: z.ZodType<
  DtoInvoiceLineItemPreview
> = z.object({
  amount: z.string().optional(),
  description: z.string().optional(),
  is_proration: z.boolean().optional(),
  period_end: z.string().optional(),
  period_start: z.string().optional(),
  quantity: z.string().optional(),
  unit_price: z.string().optional(),
});
