/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoSourceUsageItem,
  DtoSourceUsageItem$zodSchema,
} from "./dtosourceusageitem.js";
import {
  DtoUsageBreakdownItem,
  DtoUsageBreakdownItem$zodSchema,
} from "./dtousagebreakdownitem.js";
import {
  TypesCommitmentInfo,
  TypesCommitmentInfo$zodSchema,
} from "./typescommitmentinfo.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";

export type DtoInvoiceLineItemResponse = {
  amount?: string | undefined;
  commitment_info?: TypesCommitmentInfo | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  currency?: string | undefined;
  customer_id?: string | undefined;
  display_name?: string | undefined;
  entity_id?: string | undefined;
  entity_type?: string | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  invoice_id?: string | undefined;
  invoice_level_discount?: string | undefined;
  line_item_discount?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  meter_display_name?: string | undefined;
  meter_id?: string | undefined;
  period_end?: string | undefined;
  period_start?: string | undefined;
  plan_display_name?: string | undefined;
  prepaid_credits_applied?: string | undefined;
  price_id?: string | undefined;
  price_type?: string | undefined;
  price_unit?: string | undefined;
  price_unit_amount?: string | undefined;
  price_unit_id?: string | undefined;
  quantity?: string | undefined;
  status?: TypesStatus | undefined;
  subscription_id?: string | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
  usage_analytics?: Array<DtoSourceUsageItem> | undefined;
  usage_breakdown?: Array<DtoUsageBreakdownItem> | undefined;
};

export const DtoInvoiceLineItemResponse$zodSchema: z.ZodType<
  DtoInvoiceLineItemResponse
> = z.object({
  amount: z.string().optional(),
  commitment_info: TypesCommitmentInfo$zodSchema.optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  currency: z.string().optional(),
  customer_id: z.string().optional(),
  display_name: z.string().optional(),
  entity_id: z.string().optional(),
  entity_type: z.string().optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  invoice_id: z.string().optional(),
  invoice_level_discount: z.string().optional(),
  line_item_discount: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  meter_display_name: z.string().optional(),
  meter_id: z.string().optional(),
  period_end: z.string().optional(),
  period_start: z.string().optional(),
  plan_display_name: z.string().optional(),
  prepaid_credits_applied: z.string().optional(),
  price_id: z.string().optional(),
  price_type: z.string().optional(),
  price_unit: z.string().optional(),
  price_unit_amount: z.string().optional(),
  price_unit_id: z.string().optional(),
  quantity: z.string().optional(),
  status: TypesStatus$zodSchema.optional(),
  subscription_id: z.string().optional(),
  tenant_id: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
  usage_analytics: z.array(DtoSourceUsageItem$zodSchema).optional(),
  usage_breakdown: z.array(DtoUsageBreakdownItem$zodSchema).optional(),
});
