/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoInvoiceLineItemPreview,
  DtoInvoiceLineItemPreview$zodSchema,
} from "./dtoinvoicelineitempreview.js";

export type DtoInvoicePreview = {
  currency?: string | undefined;
  due_date?: string | undefined;
  line_items?: Array<DtoInvoiceLineItemPreview> | undefined;
  subtotal?: string | undefined;
  tax_amount?: string | undefined;
  total?: string | undefined;
};

export const DtoInvoicePreview$zodSchema: z.ZodType<DtoInvoicePreview> = z
  .object({
    currency: z.string().optional(),
    due_date: z.string().optional(),
    line_items: z.array(DtoInvoiceLineItemPreview$zodSchema).optional(),
    subtotal: z.string().optional(),
    tax_amount: z.string().optional(),
    total: z.string().optional(),
  });
