/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoInvoiceLineItemCoupon = {
  coupon_association_id?: string | undefined;
  coupon_id: string;
  line_item_id: string;
};

export const DtoInvoiceLineItemCoupon$zodSchema: z.ZodType<
  DtoInvoiceLineItemCoupon
> = z.object({
  coupon_association_id: z.string().optional(),
  coupon_id: z.string(),
  line_item_id: z.string(),
});
