/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoPlanResponse,
  DtoPlanResponse$zodSchema,
} from "./dtoplanresponse.js";
import {
  PaginationResponse,
  PaginationResponse$zodSchema,
} from "./paginationresponse.js";

export type DtoListPlansResponse = {
  items?: Array<DtoPlanResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

export const DtoListPlansResponse$zodSchema: z.ZodType<DtoListPlansResponse> = z
  .object({
    items: z.array(DtoPlanResponse$zodSchema).optional(),
    pagination: PaginationResponse$zodSchema.optional(),
  });
