/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoSubscriptionPauseResponse,
  DtoSubscriptionPauseResponse$zodSchema,
} from "./dtosubscriptionpauseresponse.js";

/**
 * Response object for listing subscription pauses with total count
 */
export type DtoListSubscriptionPausesResponse = {
  items?: Array<DtoSubscriptionPauseResponse> | undefined;
  total?: number | undefined;
};

export const DtoListSubscriptionPausesResponse$zodSchema: z.ZodType<
  DtoListSubscriptionPausesResponse
> = z.object({
  items: z.array(DtoSubscriptionPauseResponse$zodSchema).optional(),
  total: z.int().optional(),
}).describe("Response object for listing subscription pauses with total count");
