/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoPriceResponse,
  DtoPriceResponse$zodSchema,
} from "./dtopriceresponse.js";
import {
  PaginationResponse,
  PaginationResponse$zodSchema,
} from "./paginationresponse.js";

export type DtoListPricesResponse = {
  items?: Array<DtoPriceResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

export const DtoListPricesResponse$zodSchema: z.ZodType<DtoListPricesResponse> =
  z.object({
    items: z.array(DtoPriceResponse$zodSchema).optional(),
    pagination: PaginationResponse$zodSchema.optional(),
  });
