/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoGroupResponse,
  DtoGroupResponse$zodSchema,
} from "./dtogroupresponse.js";
import {
  TypesPaginationResponse,
  TypesPaginationResponse$zodSchema,
} from "./typespaginationresponse.js";

export type DtoListGroupsResponse = {
  items?: Array<DtoGroupResponse> | undefined;
  pagination?: TypesPaginationResponse | undefined;
};

export const DtoListGroupsResponse$zodSchema: z.ZodType<DtoListGroupsResponse> =
  z.object({
    items: z.array(DtoGroupResponse$zodSchema).optional(),
    pagination: TypesPaginationResponse$zodSchema.optional(),
  });
