/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DTOWorkflowExecutionDTO,
  DTOWorkflowExecutionDTO$zodSchema,
} from "./dtoworkflowexecutiondto.js";
import {
  TypesPaginationResponse,
  TypesPaginationResponse$zodSchema,
} from "./typespaginationresponse.js";

export type DtoListWorkflowsResponse = {
  items?: Array<DTOWorkflowExecutionDTO> | undefined;
  pagination?: TypesPaginationResponse | undefined;
};

export const DtoListWorkflowsResponse$zodSchema: z.ZodType<
  DtoListWorkflowsResponse
> = z.object({
  items: z.array(DTOWorkflowExecutionDTO$zodSchema).optional(),
  pagination: TypesPaginationResponse$zodSchema.optional(),
});
