/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoFeatureResponse,
  DtoFeatureResponse$zodSchema,
} from "./dtofeatureresponse.js";
import {
  TypesPaginationResponse,
  TypesPaginationResponse$zodSchema,
} from "./typespaginationresponse.js";

export type DtoListFeaturesResponse = {
  items?: Array<DtoFeatureResponse> | undefined;
  pagination?: TypesPaginationResponse | undefined;
};

export const DtoListFeaturesResponse$zodSchema: z.ZodType<
  DtoListFeaturesResponse
> = z.object({
  items: z.array(DtoFeatureResponse$zodSchema).optional(),
  pagination: TypesPaginationResponse$zodSchema.optional(),
});
