/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCustomerResponse,
  DtoCustomerResponse$zodSchema,
} from "./dtocustomerresponse.js";
import {
  TypesPaginationResponse,
  TypesPaginationResponse$zodSchema,
} from "./typespaginationresponse.js";

/**
 * Response object for listing customers with pagination
 */
export type DtoListCustomersResponse = {
  items?: Array<DtoCustomerResponse> | undefined;
  pagination?: TypesPaginationResponse | undefined;
};

export const DtoListCustomersResponse$zodSchema: z.ZodType<
  DtoListCustomersResponse
> = z.object({
  items: z.array(DtoCustomerResponse$zodSchema).optional(),
  pagination: TypesPaginationResponse$zodSchema.optional(),
}).describe("Response object for listing customers with pagination");
