/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoLinkedIntegrationsResponse = {
  providers?: Array<string> | undefined;
};

export const DtoLinkedIntegrationsResponse$zodSchema: z.ZodType<
  DtoLinkedIntegrationsResponse
> = z.object({
  providers: z.array(z.string()).optional(),
});
