/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoPaymentResponse,
  DtoPaymentResponse$zodSchema,
} from "./dtopaymentresponse.js";
import {
  TypesPaginationResponse,
  TypesPaginationResponse$zodSchema,
} from "./typespaginationresponse.js";

export type DtoListPaymentsResponse = {
  items?: Array<DtoPaymentResponse> | undefined;
  pagination?: TypesPaginationResponse | undefined;
};

export const DtoListPaymentsResponse$zodSchema: z.ZodType<
  DtoListPaymentsResponse
> = z.object({
  items: z.array(DtoPaymentResponse$zodSchema).optional(),
  pagination: TypesPaginationResponse$zodSchema.optional(),
});
