/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCreditGrantApplicationResponse,
  DtoCreditGrantApplicationResponse$zodSchema,
} from "./dtocreditgrantapplicationresponse.js";
import {
  TypesPaginationResponse,
  TypesPaginationResponse$zodSchema,
} from "./typespaginationresponse.js";

export type DtoListCreditGrantApplicationsResponse = {
  items?: Array<DtoCreditGrantApplicationResponse> | undefined;
  pagination?: TypesPaginationResponse | undefined;
};

export const DtoListCreditGrantApplicationsResponse$zodSchema: z.ZodType<
  DtoListCreditGrantApplicationsResponse
> = z.object({
  items: z.array(DtoCreditGrantApplicationResponse$zodSchema).optional(),
  pagination: TypesPaginationResponse$zodSchema.optional(),
});
