/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCreditGrantResponse,
  DtoCreditGrantResponse$zodSchema,
} from "./dtocreditgrantresponse.js";
import {
  TypesPaginationResponse,
  TypesPaginationResponse$zodSchema,
} from "./typespaginationresponse.js";

export type DtoListCreditGrantsResponse = {
  items?: Array<DtoCreditGrantResponse> | undefined;
  pagination?: TypesPaginationResponse | undefined;
};

export const DtoListCreditGrantsResponse$zodSchema: z.ZodType<
  DtoListCreditGrantsResponse
> = z.object({
  items: z.array(DtoCreditGrantResponse$zodSchema).optional(),
  pagination: TypesPaginationResponse$zodSchema.optional(),
});
