/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoEntitlementResponse,
  DtoEntitlementResponse$zodSchema,
} from "./dtoentitlementresponse.js";
import {
  TypesPaginationResponse,
  TypesPaginationResponse$zodSchema,
} from "./typespaginationresponse.js";

export type DtoListEntitlementsResponse = {
  items?: Array<DtoEntitlementResponse> | undefined;
  pagination?: TypesPaginationResponse | undefined;
};

export const DtoListEntitlementsResponse$zodSchema: z.ZodType<
  DtoListEntitlementsResponse
> = z.object({
  items: z.array(DtoEntitlementResponse$zodSchema).optional(),
  pagination: TypesPaginationResponse$zodSchema.optional(),
});
