/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesBillingPeriod,
  TypesBillingPeriod$zodSchema,
} from "./typesbillingperiod.js";
import {
  TypesCommitmentType,
  TypesCommitmentType$zodSchema,
} from "./typescommitmenttype.js";

export type DtoLineItemCommitmentConfig = {
  commitment_amount?: number | undefined;
  commitment_duration?: TypesBillingPeriod | undefined;
  commitment_quantity?: number | undefined;
  commitment_type?: TypesCommitmentType | undefined;
  enable_true_up?: boolean | undefined;
  is_window_commitment?: boolean | undefined;
  overage_factor?: number | undefined;
};

export const DtoLineItemCommitmentConfig$zodSchema: z.ZodType<
  DtoLineItemCommitmentConfig
> = z.object({
  commitment_amount: z.number().optional(),
  commitment_duration: TypesBillingPeriod$zodSchema.optional(),
  commitment_quantity: z.number().optional(),
  commitment_type: TypesCommitmentType$zodSchema.optional(),
  enable_true_up: z.boolean().optional(),
  is_window_commitment: z.boolean().optional(),
  overage_factor: z.number().optional(),
});
