/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  MeterAggregation,
  MeterAggregation$zodSchema,
} from "./meteraggregation.js";
import { MeterFilter, MeterFilter$zodSchema } from "./meterfilter.js";
import {
  TypesResetUsage,
  TypesResetUsage$zodSchema,
} from "./typesresetusage.js";

export type DtoMeterResponse = {
  aggregation?: MeterAggregation | undefined;
  created_at?: string | undefined;
  event_name?: string | undefined;
  filters?: Array<MeterFilter> | undefined;
  id?: string | undefined;
  name?: string | undefined;
  reset_usage?: TypesResetUsage | undefined;
  status?: string | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
};

export const DtoMeterResponse$zodSchema: z.ZodType<DtoMeterResponse> = z.object(
  {
    aggregation: MeterAggregation$zodSchema.optional(),
    created_at: z.string().optional(),
    event_name: z.string().optional(),
    filters: z.array(MeterFilter$zodSchema).optional(),
    id: z.string().optional(),
    name: z.string().optional(),
    reset_usage: TypesResetUsage$zodSchema.optional(),
    status: z.string().optional(),
    tenant_id: z.string().optional(),
    updated_at: z.string().optional(),
  },
);
