/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoPlanSummary = {
  description?: string | undefined;
  id?: string | undefined;
  lookup_key?: string | undefined;
  name?: string | undefined;
};

export const DtoPlanSummary$zodSchema: z.ZodType<DtoPlanSummary> = z.object({
  description: z.string().optional(),
  id: z.string().optional(),
  lookup_key: z.string().optional(),
  name: z.string().optional(),
});
