/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { TypesPauseMode, TypesPauseMode$zodSchema } from "./typespausemode.js";

/**
 * Request object for pausing an active subscription with various pause modes and options
 */
export type DtoPauseSubscriptionRequest = {
  dry_run?: boolean | undefined;
  metadata?: { [k: string]: string } | undefined;
  pause_days?: number | undefined;
  pause_end?: string | undefined;
  pause_mode: TypesPauseMode;
  pause_start?: string | undefined;
  reason?: string | undefined;
};

export const DtoPauseSubscriptionRequest$zodSchema: z.ZodType<
  DtoPauseSubscriptionRequest
> = z.object({
  dry_run: z.boolean().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  pause_days: z.int().optional(),
  pause_end: z.string().optional(),
  pause_mode: TypesPauseMode$zodSchema,
  pause_start: z.string().optional(),
  reason: z.string().optional(),
}).describe(
  "Request object for pausing an active subscription with various pause modes and options",
);
