/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoPaymentAttemptResponse,
  DtoPaymentAttemptResponse$zodSchema,
} from "./dtopaymentattemptresponse.js";
import {
  TypesPaymentDestinationType,
  TypesPaymentDestinationType$zodSchema,
} from "./typespaymentdestinationtype.js";
import {
  TypesPaymentMethodType,
  TypesPaymentMethodType$zodSchema,
} from "./typespaymentmethodtype.js";
import {
  TypesPaymentStatus,
  TypesPaymentStatus$zodSchema,
} from "./typespaymentstatus.js";

export type DtoPaymentResponse = {
  amount?: string | undefined;
  attempts?: Array<DtoPaymentAttemptResponse> | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  currency?: string | undefined;
  destination_id?: string | undefined;
  destination_type?: TypesPaymentDestinationType | undefined;
  error_message?: string | undefined;
  failed_at?: string | undefined;
  gateway_metadata?: { [k: string]: string } | undefined;
  gateway_payment_id?: string | undefined;
  gateway_tracking_id?: string | undefined;
  id?: string | undefined;
  idempotency_key?: string | undefined;
  invoice_number?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  payment_gateway?: string | undefined;
  payment_method_id?: string | undefined;
  payment_method_type?: TypesPaymentMethodType | undefined;
  payment_status?: TypesPaymentStatus | undefined;
  payment_url?: string | undefined;
  refunded_at?: string | undefined;
  save_card_and_make_default?: boolean | undefined;
  succeeded_at?: string | undefined;
  tenant_id?: string | undefined;
  track_attempts?: boolean | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const DtoPaymentResponse$zodSchema: z.ZodType<DtoPaymentResponse> = z
  .object({
    amount: z.string().optional(),
    attempts: z.array(DtoPaymentAttemptResponse$zodSchema).optional(),
    created_at: z.string().optional(),
    created_by: z.string().optional(),
    currency: z.string().optional(),
    destination_id: z.string().optional(),
    destination_type: TypesPaymentDestinationType$zodSchema.optional(),
    error_message: z.string().optional(),
    failed_at: z.string().optional(),
    gateway_metadata: z.record(z.string(), z.string()).optional(),
    gateway_payment_id: z.string().optional(),
    gateway_tracking_id: z.string().optional(),
    id: z.string().optional(),
    idempotency_key: z.string().optional(),
    invoice_number: z.string().optional(),
    metadata: z.record(z.string(), z.string()).optional(),
    payment_gateway: z.string().optional(),
    payment_method_id: z.string().optional(),
    payment_method_type: TypesPaymentMethodType$zodSchema.optional(),
    payment_status: TypesPaymentStatus$zodSchema.optional(),
    payment_url: z.string().optional(),
    refunded_at: z.string().optional(),
    save_card_and_make_default: z.boolean().optional(),
    succeeded_at: z.string().optional(),
    tenant_id: z.string().optional(),
    track_attempts: z.boolean().optional(),
    updated_at: z.string().optional(),
    updated_by: z.string().optional(),
  });
