/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCreatePriceTier,
  DtoCreatePriceTier$zodSchema,
} from "./dtocreatepricetier.js";

export type DtoPriceUnitConfig = {
  amount?: string | undefined;
  price_unit: string;
  price_unit_tiers?: Array<DtoCreatePriceTier> | undefined;
};

export const DtoPriceUnitConfig$zodSchema: z.ZodType<DtoPriceUnitConfig> = z
  .object({
    amount: z.string().optional(),
    price_unit: z.string(),
    price_unit_tiers: z.array(DtoCreatePriceTier$zodSchema).optional(),
  });
