/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesResumeMode,
  TypesResumeMode$zodSchema,
} from "./typesresumemode.js";

/**
 * Request object for resuming a paused subscription
 */
export type DtoResumeSubscriptionRequest = {
  dry_run?: boolean | undefined;
  metadata?: { [k: string]: string } | undefined;
  resume_mode: TypesResumeMode;
};

export const DtoResumeSubscriptionRequest$zodSchema: z.ZodType<
  DtoResumeSubscriptionRequest
> = z.object({
  dry_run: z.boolean().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  resume_mode: TypesResumeMode$zodSchema,
}).describe("Request object for resuming a paused subscription");
