/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoAggregatedFeature,
  DtoAggregatedFeature$zodSchema,
} from "./dtoaggregatedfeature.js";

export type DtoSubscriptionEntitlementsResponse = {
  features?: Array<DtoAggregatedFeature> | undefined;
  plan_id?: string | undefined;
  subscription_id?: string | undefined;
};

export const DtoSubscriptionEntitlementsResponse$zodSchema: z.ZodType<
  DtoSubscriptionEntitlementsResponse
> = z.object({
  features: z.array(DtoAggregatedFeature$zodSchema).optional(),
  plan_id: z.string().optional(),
  subscription_id: z.string().optional(),
});
