/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoPriceResponse,
  DtoPriceResponse$zodSchema,
} from "./dtopriceresponse.js";
import {
  TypesBillingPeriod,
  TypesBillingPeriod$zodSchema,
} from "./typesbillingperiod.js";
import {
  TypesCommitmentType,
  TypesCommitmentType$zodSchema,
} from "./typescommitmenttype.js";
import {
  TypesInvoiceCadence,
  TypesInvoiceCadence$zodSchema,
} from "./typesinvoicecadence.js";
import { TypesPriceType, TypesPriceType$zodSchema } from "./typespricetype.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";
import {
  TypesSubscriptionLineItemEntityType,
  TypesSubscriptionLineItemEntityType$zodSchema,
} from "./typessubscriptionlineitementitytype.js";

export type DtoSubscriptionLineItemResponse = {
  billing_period?: TypesBillingPeriod | undefined;
  billing_period_count?: number | undefined;
  commitment_amount?: string | undefined;
  commitment_duration?: TypesBillingPeriod | undefined;
  commitment_overage_factor?: string | undefined;
  commitment_quantity?: string | undefined;
  commitment_true_up_enabled?: boolean | undefined;
  commitment_type?: TypesCommitmentType | undefined;
  commitment_windowed?: boolean | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  currency?: string | undefined;
  customer_id?: string | undefined;
  display_name?: string | undefined;
  end_date?: string | undefined;
  entity_id?: string | undefined;
  entity_type?: TypesSubscriptionLineItemEntityType | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  invoice_cadence?: TypesInvoiceCadence | undefined;
  metadata?: { [k: string]: string } | undefined;
  meter_display_name?: string | undefined;
  meter_id?: string | undefined;
  plan_display_name?: string | undefined;
  price?: DtoPriceResponse | undefined;
  price_id?: string | undefined;
  price_type?: TypesPriceType | undefined;
  price_unit?: string | undefined;
  price_unit_id?: string | undefined;
  quantity?: string | undefined;
  start_date?: string | undefined;
  status?: TypesStatus | undefined;
  subscription_id?: string | undefined;
  subscription_phase_id?: string | undefined;
  tenant_id?: string | undefined;
  trial_period?: number | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const DtoSubscriptionLineItemResponse$zodSchema: z.ZodType<
  DtoSubscriptionLineItemResponse
> = z.object({
  billing_period: TypesBillingPeriod$zodSchema.optional(),
  billing_period_count: z.int().optional(),
  commitment_amount: z.string().optional(),
  commitment_duration: TypesBillingPeriod$zodSchema.optional(),
  commitment_overage_factor: z.string().optional(),
  commitment_quantity: z.string().optional(),
  commitment_true_up_enabled: z.boolean().optional(),
  commitment_type: TypesCommitmentType$zodSchema.optional(),
  commitment_windowed: z.boolean().optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  currency: z.string().optional(),
  customer_id: z.string().optional(),
  display_name: z.string().optional(),
  end_date: z.string().optional(),
  entity_id: z.string().optional(),
  entity_type: TypesSubscriptionLineItemEntityType$zodSchema.optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  invoice_cadence: TypesInvoiceCadence$zodSchema.optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  meter_display_name: z.string().optional(),
  meter_id: z.string().optional(),
  plan_display_name: z.string().optional(),
  price: DtoPriceResponse$zodSchema.optional(),
  price_id: z.string().optional(),
  price_type: TypesPriceType$zodSchema.optional(),
  price_unit: z.string().optional(),
  price_unit_id: z.string().optional(),
  quantity: z.string().optional(),
  start_date: z.string().optional(),
  status: TypesStatus$zodSchema.optional(),
  subscription_id: z.string().optional(),
  subscription_phase_id: z.string().optional(),
  tenant_id: z.string().optional(),
  trial_period: z.int().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
});
