/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Status, Status$zodSchema } from "./status.js";

export type DtoSubscriptionPhaseResponse = {
  created_at?: string | undefined;
  created_by?: string | undefined;
  end_date?: string | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  start_date?: string | undefined;
  status?: Status | undefined;
  subscription_id?: string | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const DtoSubscriptionPhaseResponse$zodSchema: z.ZodType<
  DtoSubscriptionPhaseResponse
> = z.object({
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  end_date: z.string().optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  start_date: z.string().optional(),
  status: Status$zodSchema.optional(),
  subscription_id: z.string().optional(),
  tenant_id: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
});
