/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoBillingCycleInfo,
  DtoBillingCycleInfo$zodSchema,
} from "./dtobillingcycleinfo.js";
import {
  DtoInvoicePreview,
  DtoInvoicePreview$zodSchema,
} from "./dtoinvoicepreview.js";
import { DtoPlanSummary, DtoPlanSummary$zodSchema } from "./dtoplansummary.js";
import {
  DtoProrationDetails,
  DtoProrationDetails$zodSchema,
} from "./dtoprorationdetails.js";
import {
  TypesSubscriptionChangeType,
  TypesSubscriptionChangeType$zodSchema,
} from "./typessubscriptionchangetype.js";

/**
 * Response showing the financial impact of a subscription plan change
 */
export type DtoSubscriptionChangePreviewResponse = {
  change_type?: TypesSubscriptionChangeType | undefined;
  current_plan?: DtoPlanSummary | undefined;
  effective_date?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  new_billing_cycle?: DtoBillingCycleInfo | undefined;
  next_invoice_preview?: DtoInvoicePreview | undefined;
  proration_details?: DtoProrationDetails | undefined;
  subscription_id?: string | undefined;
  target_plan?: DtoPlanSummary | undefined;
  warnings?: Array<string> | undefined;
};

export const DtoSubscriptionChangePreviewResponse$zodSchema: z.ZodType<
  DtoSubscriptionChangePreviewResponse
> = z.object({
  change_type: TypesSubscriptionChangeType$zodSchema.optional(),
  current_plan: DtoPlanSummary$zodSchema.optional(),
  effective_date: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  new_billing_cycle: DtoBillingCycleInfo$zodSchema.optional(),
  next_invoice_preview: DtoInvoicePreview$zodSchema.optional(),
  proration_details: DtoProrationDetails$zodSchema.optional(),
  subscription_id: z.string().optional(),
  target_plan: DtoPlanSummary$zodSchema.optional(),
  warnings: z.array(z.string()).optional(),
}).describe(
  "Response showing the financial impact of a subscription plan change",
);
