/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PricePrice, PricePrice$zodSchema } from "./priceprice.js";

export type DtoSubscriptionUsageByMetersResponse = {
  amount?: number | undefined;
  currency?: string | undefined;
  display_amount?: string | undefined;
  filter_values?: { [k: string]: Array<string> } | undefined;
  is_overage?: boolean | undefined;
  meter_display_name?: string | undefined;
  meter_id?: string | undefined;
  overage_factor?: number | undefined;
  price?: PricePrice | undefined;
  quantity?: number | undefined;
};

export const DtoSubscriptionUsageByMetersResponse$zodSchema: z.ZodType<
  DtoSubscriptionUsageByMetersResponse
> = z.object({
  amount: z.number().optional(),
  currency: z.string().optional(),
  display_amount: z.string().optional(),
  filter_values: z.record(z.string(), z.array(z.string())).optional(),
  is_overage: z.boolean().optional(),
  meter_display_name: z.string().optional(),
  meter_id: z.string().optional(),
  overage_factor: z.number().optional(),
  price: PricePrice$zodSchema.optional(),
  quantity: z.number().optional(),
});
