/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCouponAssociationResponse,
  DtoCouponAssociationResponse$zodSchema,
} from "./dtocouponassociationresponse.js";
import {
  DtoCreditGrantResponse,
  DtoCreditGrantResponse$zodSchema,
} from "./dtocreditgrantresponse.js";
import {
  DtoCustomerResponse,
  DtoCustomerResponse$zodSchema,
} from "./dtocustomerresponse.js";
import {
  DtoInvoiceResponse,
  DtoInvoiceResponse$zodSchema,
} from "./dtoinvoiceresponse.js";
import {
  DtoPlanResponse,
  DtoPlanResponse$zodSchema,
} from "./dtoplanresponse.js";
import {
  DtoSubscriptionPhaseResponse,
  DtoSubscriptionPhaseResponse$zodSchema,
} from "./dtosubscriptionphaseresponse.js";
import {
  SubscriptionSubscriptionLineItem,
  SubscriptionSubscriptionLineItem$zodSchema,
} from "./subscriptionsubscriptionlineitem.js";
import {
  SubscriptionSubscriptionPause,
  SubscriptionSubscriptionPause$zodSchema,
} from "./subscriptionsubscriptionpause.js";
import {
  TypesBillingCadence,
  TypesBillingCadence$zodSchema,
} from "./typesbillingcadence.js";
import {
  TypesBillingCycle,
  TypesBillingCycle$zodSchema,
} from "./typesbillingcycle.js";
import {
  TypesBillingPeriod,
  TypesBillingPeriod$zodSchema,
} from "./typesbillingperiod.js";
import {
  TypesPauseStatus,
  TypesPauseStatus$zodSchema,
} from "./typespausestatus.js";
import {
  TypesPaymentTerms,
  TypesPaymentTerms$zodSchema,
} from "./typespaymentterms.js";
import {
  TypesProrationBehavior,
  TypesProrationBehavior$zodSchema,
} from "./typesprorationbehavior.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";
import {
  TypesSubscriptionStatus,
  TypesSubscriptionStatus$zodSchema,
} from "./typessubscriptionstatus.js";

export type DtoSubscriptionResponse = {
  active_pause_id?: string | undefined;
  billing_anchor?: string | undefined;
  billing_cadence?: TypesBillingCadence | undefined;
  billing_cycle?: TypesBillingCycle | undefined;
  billing_period?: TypesBillingPeriod | undefined;
  billing_period_count?: number | undefined;
  cancel_at?: string | undefined;
  cancel_at_period_end?: boolean | undefined;
  cancelled_at?: string | undefined;
  collection_method?: string | undefined;
  commitment_amount?: string | undefined;
  commitment_duration?: TypesBillingPeriod | undefined;
  coupon_associations?: Array<DtoCouponAssociationResponse> | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  credit_grants?: Array<DtoCreditGrantResponse> | undefined;
  currency?: string | undefined;
  current_period_end?: string | undefined;
  current_period_start?: string | undefined;
  customer?: DtoCustomerResponse | undefined;
  customer_id?: string | undefined;
  customer_timezone?: string | undefined;
  enable_true_up?: boolean | undefined;
  end_date?: string | undefined;
  environment_id?: string | undefined;
  gateway_payment_method_id?: string | undefined;
  id?: string | undefined;
  invoicing_customer_id?: string | undefined;
  latest_invoice?: DtoInvoiceResponse | undefined;
  line_items?: Array<SubscriptionSubscriptionLineItem> | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  overage_factor?: string | undefined;
  parent_subscription_id?: string | undefined;
  pause_status?: TypesPauseStatus | undefined;
  pauses?: Array<SubscriptionSubscriptionPause> | undefined;
  payment_behavior?: string | undefined;
  payment_terms?: TypesPaymentTerms | undefined;
  phases?: Array<DtoSubscriptionPhaseResponse> | undefined;
  plan?: DtoPlanResponse | undefined;
  plan_id?: string | undefined;
  proration_behavior?: TypesProrationBehavior | undefined;
  start_date?: string | undefined;
  status?: TypesStatus | undefined;
  subscription_status?: TypesSubscriptionStatus | undefined;
  tenant_id?: string | undefined;
  trial_end?: string | undefined;
  trial_start?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
  version?: number | undefined;
};

export const DtoSubscriptionResponse$zodSchema: z.ZodType<
  DtoSubscriptionResponse
> = z.object({
  active_pause_id: z.string().optional(),
  billing_anchor: z.string().optional(),
  billing_cadence: TypesBillingCadence$zodSchema.optional(),
  billing_cycle: TypesBillingCycle$zodSchema.optional(),
  billing_period: TypesBillingPeriod$zodSchema.optional(),
  billing_period_count: z.int().optional(),
  cancel_at: z.string().optional(),
  cancel_at_period_end: z.boolean().optional(),
  cancelled_at: z.string().optional(),
  collection_method: z.string().optional(),
  commitment_amount: z.string().optional(),
  commitment_duration: TypesBillingPeriod$zodSchema.optional(),
  coupon_associations: z.array(DtoCouponAssociationResponse$zodSchema)
    .optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  credit_grants: z.array(DtoCreditGrantResponse$zodSchema).optional(),
  currency: z.string().optional(),
  current_period_end: z.string().optional(),
  current_period_start: z.string().optional(),
  customer: DtoCustomerResponse$zodSchema.optional(),
  customer_id: z.string().optional(),
  customer_timezone: z.string().optional(),
  enable_true_up: z.boolean().optional(),
  end_date: z.string().optional(),
  environment_id: z.string().optional(),
  gateway_payment_method_id: z.string().optional(),
  id: z.string().optional(),
  invoicing_customer_id: z.string().optional(),
  latest_invoice: z.lazy(() => DtoInvoiceResponse$zodSchema).optional(),
  line_items: z.array(SubscriptionSubscriptionLineItem$zodSchema).optional(),
  lookup_key: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  overage_factor: z.string().optional(),
  parent_subscription_id: z.string().optional(),
  pause_status: TypesPauseStatus$zodSchema.optional(),
  pauses: z.array(SubscriptionSubscriptionPause$zodSchema).optional(),
  payment_behavior: z.string().optional(),
  payment_terms: TypesPaymentTerms$zodSchema.optional(),
  phases: z.array(DtoSubscriptionPhaseResponse$zodSchema).optional(),
  plan: DtoPlanResponse$zodSchema.optional(),
  plan_id: z.string().optional(),
  proration_behavior: TypesProrationBehavior$zodSchema.optional(),
  start_date: z.string().optional(),
  status: TypesStatus$zodSchema.optional(),
  subscription_status: TypesSubscriptionStatus$zodSchema.optional(),
  tenant_id: z.string().optional(),
  trial_end: z.string().optional(),
  trial_start: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
  version: z.int().optional(),
});
