/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCreditGrantResponse,
  DtoCreditGrantResponse$zodSchema,
} from "./dtocreditgrantresponse.js";
import {
  DtoInvoiceResponse,
  DtoInvoiceResponse$zodSchema,
} from "./dtoinvoiceresponse.js";
import {
  DtoProrationDetails,
  DtoProrationDetails$zodSchema,
} from "./dtoprorationdetails.js";
import {
  DtoSubscriptionSummary,
  DtoSubscriptionSummary$zodSchema,
} from "./dtosubscriptionsummary.js";
import {
  TypesSubscriptionChangeType,
  TypesSubscriptionChangeType$zodSchema,
} from "./typessubscriptionchangetype.js";

/**
 * Response after successfully executing a subscription plan change
 */
export type DtoSubscriptionChangeExecuteResponse = {
  change_type?: TypesSubscriptionChangeType | undefined;
  credit_grants?: Array<DtoCreditGrantResponse> | undefined;
  effective_date?: string | undefined;
  invoice?: DtoInvoiceResponse | undefined;
  is_scheduled?: boolean | undefined;
  metadata?: { [k: string]: string } | undefined;
  new_subscription?: DtoSubscriptionSummary | undefined;
  old_subscription?: DtoSubscriptionSummary | undefined;
  proration_applied?: DtoProrationDetails | undefined;
  schedule_id?: string | undefined;
  scheduled_at?: string | undefined;
};

export const DtoSubscriptionChangeExecuteResponse$zodSchema: z.ZodType<
  DtoSubscriptionChangeExecuteResponse
> = z.object({
  change_type: TypesSubscriptionChangeType$zodSchema.optional(),
  credit_grants: z.array(DtoCreditGrantResponse$zodSchema).optional(),
  effective_date: z.string().optional(),
  invoice: DtoInvoiceResponse$zodSchema.optional(),
  is_scheduled: z.boolean().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  new_subscription: DtoSubscriptionSummary$zodSchema.optional(),
  old_subscription: DtoSubscriptionSummary$zodSchema.optional(),
  proration_applied: DtoProrationDetails$zodSchema.optional(),
  schedule_id: z.string().optional(),
  scheduled_at: z.string().optional(),
}).describe("Response after successfully executing a subscription plan change");
