/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesBillingCadence,
  TypesBillingCadence$zodSchema,
} from "./typesbillingcadence.js";
import {
  TypesBillingCycle,
  TypesBillingCycle$zodSchema,
} from "./typesbillingcycle.js";
import {
  TypesBillingPeriod,
  TypesBillingPeriod$zodSchema,
} from "./typesbillingperiod.js";
import {
  TypesProrationBehavior,
  TypesProrationBehavior$zodSchema,
} from "./typesprorationbehavior.js";
import {
  TypesScheduleType,
  TypesScheduleType$zodSchema,
} from "./typesscheduletype.js";

/**
 * Request object for changing a subscription plan (upgrade/downgrade)
 */
export type DtoSubscriptionChangeRequest = {
  billing_cadence: TypesBillingCadence;
  billing_cycle: TypesBillingCycle;
  billing_period: TypesBillingPeriod;
  billing_period_count?: number | undefined;
  change_at?: TypesScheduleType | undefined;
  metadata?: { [k: string]: string } | undefined;
  proration_behavior: TypesProrationBehavior;
  target_plan_id: string;
};

export const DtoSubscriptionChangeRequest$zodSchema: z.ZodType<
  DtoSubscriptionChangeRequest
> = z.object({
  billing_cadence: TypesBillingCadence$zodSchema,
  billing_cycle: TypesBillingCycle$zodSchema,
  billing_period: TypesBillingPeriod$zodSchema,
  billing_period_count: z.int().optional(),
  change_at: TypesScheduleType$zodSchema.optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  proration_behavior: TypesProrationBehavior$zodSchema,
  target_plan_id: z.string(),
}).describe(
  "Request object for changing a subscription plan (upgrade/downgrade)",
);
