/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DebugTrackerStatus,
  DebugTrackerStatus$zodSchema,
} from "./debugtrackerstatus.js";
import {
  DtoMatchedSubscriptionLineItem,
  DtoMatchedSubscriptionLineItem$zodSchema,
} from "./dtomatchedsubscriptionlineitem.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type DtoSubscriptionLineItemLookupResult = {
  error?: ErrorsErrorResponse | undefined;
  matched_line_items?: Array<DtoMatchedSubscriptionLineItem> | undefined;
  status?: DebugTrackerStatus | undefined;
};

export const DtoSubscriptionLineItemLookupResult$zodSchema: z.ZodType<
  DtoSubscriptionLineItemLookupResult
> = z.object({
  error: ErrorsErrorResponse$zodSchema.optional(),
  matched_line_items: z.array(DtoMatchedSubscriptionLineItem$zodSchema)
    .optional(),
  status: DebugTrackerStatus$zodSchema.optional(),
});
