/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesS3JobConfig,
  TypesS3JobConfig$zodSchema,
} from "./typess3jobconfig.js";
import {
  TypesScheduledTaskEntityType,
  TypesScheduledTaskEntityType$zodSchema,
} from "./typesscheduledtaskentitytype.js";
import {
  TypesScheduledTaskInterval,
  TypesScheduledTaskInterval$zodSchema,
} from "./typesscheduledtaskinterval.js";

export type DtoScheduledTaskResponse = {
  connection_id?: string | undefined;
  created_at?: string | undefined;
  enabled?: boolean | undefined;
  entity_type?: TypesScheduledTaskEntityType | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  interval?: TypesScheduledTaskInterval | undefined;
  job_config?: TypesS3JobConfig | undefined;
  status?: string | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
};

export const DtoScheduledTaskResponse$zodSchema: z.ZodType<
  DtoScheduledTaskResponse
> = z.object({
  connection_id: z.string().optional(),
  created_at: z.string().optional(),
  enabled: z.boolean().optional(),
  entity_type: TypesScheduledTaskEntityType$zodSchema.optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  interval: TypesScheduledTaskInterval$zodSchema.optional(),
  job_config: TypesS3JobConfig$zodSchema.optional(),
  status: z.string().optional(),
  tenant_id: z.string().optional(),
  updated_at: z.string().optional(),
});
