/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesScheduleStatus,
  TypesScheduleStatus$zodSchema,
} from "./typesschedulestatus.js";
import {
  TypesSubscriptionScheduleChangeType,
  TypesSubscriptionScheduleChangeType$zodSchema,
} from "./typessubscriptionschedulechangetype.js";

/**
 * configuration contains type-specific configuration (e.g., target_plan_id for plan changes)
 */
export type Configuration = {};

export const Configuration$zodSchema: z.ZodType<Configuration> = z.object({})
  .describe(
    "configuration contains type-specific configuration (e.g., target_plan_id for plan changes)",
  );

/**
 * execution_result contains type-specific execution result
 */
export type ExecutionResult = {};

export const ExecutionResult$zodSchema: z.ZodType<ExecutionResult> = z.object(
  {},
).describe("execution_result contains type-specific execution result");

/**
 * Full details of a subscription schedule
 */
export type DtoSubscriptionScheduleResponse = {
  can_be_cancelled?: boolean | undefined;
  cancelled_at?: string | undefined;
  configuration?: Configuration | undefined;
  created_at?: string | undefined;
  days_until_execution?: number | undefined;
  error_message?: string | undefined;
  executed_at?: string | undefined;
  execution_result?: ExecutionResult | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  schedule_type?: TypesSubscriptionScheduleChangeType | undefined;
  scheduled_at?: string | undefined;
  status?: TypesScheduleStatus | undefined;
  subscription_id?: string | undefined;
  updated_at?: string | undefined;
};

export const DtoSubscriptionScheduleResponse$zodSchema: z.ZodType<
  DtoSubscriptionScheduleResponse
> = z.object({
  can_be_cancelled: z.boolean().optional(),
  cancelled_at: z.string().optional(),
  configuration: z.lazy(() => Configuration$zodSchema).optional(),
  created_at: z.string().optional(),
  days_until_execution: z.int().optional(),
  error_message: z.string().optional(),
  executed_at: z.string().optional(),
  execution_result: z.lazy(() => ExecutionResult$zodSchema).optional(),
  id: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  schedule_type: TypesSubscriptionScheduleChangeType$zodSchema.optional(),
  scheduled_at: z.string().optional(),
  status: TypesScheduleStatus$zodSchema.optional(),
  subscription_id: z.string().optional(),
  updated_at: z.string().optional(),
}).describe("Full details of a subscription schedule");
