/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesSecretProvider,
  TypesSecretProvider$zodSchema,
} from "./typessecretprovider.js";
import {
  TypesSecretType,
  TypesSecretType$zodSchema,
} from "./typessecrettype.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";
import { TypesUserType, TypesUserType$zodSchema } from "./typesusertype.js";

export type DtoSecretResponse = {
  created_at?: string | undefined;
  display_id?: string | undefined;
  expires_at?: string | undefined;
  id?: string | undefined;
  last_used_at?: string | undefined;
  name?: string | undefined;
  provider?: TypesSecretProvider | undefined;
  roles?: Array<string> | undefined;
  status?: TypesStatus | undefined;
  type?: TypesSecretType | undefined;
  updated_at?: string | undefined;
  user_type?: TypesUserType | undefined;
};

export const DtoSecretResponse$zodSchema: z.ZodType<DtoSecretResponse> = z
  .object({
    created_at: z.string().optional(),
    display_id: z.string().optional(),
    expires_at: z.string().optional(),
    id: z.string().optional(),
    last_used_at: z.string().optional(),
    name: z.string().optional(),
    provider: TypesSecretProvider$zodSchema.optional(),
    roles: z.array(z.string()).optional(),
    status: TypesStatus$zodSchema.optional(),
    type: TypesSecretType$zodSchema.optional(),
    updated_at: z.string().optional(),
    user_type: TypesUserType$zodSchema.optional(),
  });
