/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoWalletResponse,
  DtoWalletResponse$zodSchema,
} from "./dtowalletresponse.js";
import {
  DtoWalletTransactionResponse,
  DtoWalletTransactionResponse$zodSchema,
} from "./dtowallettransactionresponse.js";

export type DtoTopUpWalletResponse = {
  invoice_id?: string | undefined;
  wallet?: DtoWalletResponse | undefined;
  wallet_transaction?: DtoWalletTransactionResponse | undefined;
};

export const DtoTopUpWalletResponse$zodSchema: z.ZodType<
  DtoTopUpWalletResponse
> = z.object({
  invoice_id: z.string().optional(),
  wallet: DtoWalletResponse$zodSchema.optional(),
  wallet_transaction: DtoWalletTransactionResponse$zodSchema.optional(),
});
