/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoTriggerForceRunRequest = {
  end_time?: string | undefined;
  start_time?: string | undefined;
};

export const DtoTriggerForceRunRequest$zodSchema: z.ZodType<
  DtoTriggerForceRunRequest
> = z.object({
  end_time: z.string().optional(),
  start_time: z.string().optional(),
});
