/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoTriggerForceRunResponse = {
  end_time?: string | undefined;
  message?: string | undefined;
  mode?: string | undefined;
  start_time?: string | undefined;
  workflow_id?: string | undefined;
};

export const DtoTriggerForceRunResponse$zodSchema: z.ZodType<
  DtoTriggerForceRunResponse
> = z.object({
  end_time: z.string().optional(),
  message: z.string().optional(),
  mode: z.string().optional(),
  start_time: z.string().optional(),
  workflow_id: z.string().optional(),
});
