/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoTaxRateResponse,
  DtoTaxRateResponse$zodSchema,
} from "./dtotaxrateresponse.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";
import {
  TypesTaxRateEntityType,
  TypesTaxRateEntityType$zodSchema,
} from "./typestaxrateentitytype.js";

export type DtoTaxAssociationResponse = {
  auto_apply?: boolean | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  currency?: string | undefined;
  entity_id?: string | undefined;
  entity_type?: TypesTaxRateEntityType | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  priority?: number | undefined;
  status?: TypesStatus | undefined;
  tax_rate?: DtoTaxRateResponse | undefined;
  tax_rate_id?: string | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const DtoTaxAssociationResponse$zodSchema: z.ZodType<
  DtoTaxAssociationResponse
> = z.object({
  auto_apply: z.boolean().optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  currency: z.string().optional(),
  entity_id: z.string().optional(),
  entity_type: TypesTaxRateEntityType$zodSchema.optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  priority: z.int().optional(),
  status: TypesStatus$zodSchema.optional(),
  tax_rate: DtoTaxRateResponse$zodSchema.optional(),
  tax_rate_id: z.string().optional(),
  tenant_id: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
});
