/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesTransactionReason,
  TypesTransactionReason$zodSchema,
} from "./typestransactionreason.js";

export type DtoTopUpWalletRequest = {
  amount?: string | undefined;
  credits_to_add?: string | undefined;
  description?: string | undefined;
  expiry_date_utc?: string | undefined;
  idempotency_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  priority?: number | undefined;
  transaction_reason: TypesTransactionReason;
};

export const DtoTopUpWalletRequest$zodSchema: z.ZodType<DtoTopUpWalletRequest> =
  z.object({
    amount: z.string().optional(),
    credits_to_add: z.string().optional(),
    description: z.string().optional(),
    expiry_date_utc: z.string().optional(),
    idempotency_key: z.string().optional(),
    metadata: z.record(z.string(), z.string()).optional(),
    priority: z.int().optional(),
    transaction_reason: TypesTransactionReason$zodSchema,
  });
