/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCustomerUsageSummaryResponse,
  DtoCustomerUsageSummaryResponse$zodSchema,
} from "./dtocustomerusagesummaryresponse.js";
import {
  DtoSubscriptionResponse,
  DtoSubscriptionResponse$zodSchema,
} from "./dtosubscriptionresponse.js";

export type DtoTenantBillingUsage = {
  subscriptions?: Array<DtoSubscriptionResponse> | undefined;
  usage?: DtoCustomerUsageSummaryResponse | undefined;
};

export const DtoTenantBillingUsage$zodSchema: z.ZodType<DtoTenantBillingUsage> =
  z.object({
    subscriptions: z.array(DtoSubscriptionResponse$zodSchema).optional(),
    usage: DtoCustomerUsageSummaryResponse$zodSchema.optional(),
  });
