/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoPriceResponse,
  DtoPriceResponse$zodSchema,
} from "./dtopriceresponse.js";
import {
  DtoUsageAnalyticPoint,
  DtoUsageAnalyticPoint$zodSchema,
} from "./dtousageanalyticpoint.js";
import {
  GithubComFlexpriceFlexpriceInternalDomainAddonAddon,
  GithubComFlexpriceFlexpriceInternalDomainAddonAddon$zodSchema,
} from "./githubcomflexpriceflexpriceinternaldomainaddonaddon.js";
import {
  GithubComFlexpriceFlexpriceInternalDomainFeatureFeature,
  GithubComFlexpriceFlexpriceInternalDomainFeatureFeature$zodSchema,
} from "./githubcomflexpriceflexpriceinternaldomainfeaturefeature.js";
import {
  GithubComFlexpriceFlexpriceInternalDomainPlanPlan,
  GithubComFlexpriceFlexpriceInternalDomainPlanPlan$zodSchema,
} from "./githubcomflexpriceflexpriceinternaldomainplanplan.js";
import { MeterMeter, MeterMeter$zodSchema } from "./metermeter.js";
import {
  SubscriptionSubscriptionLineItem,
  SubscriptionSubscriptionLineItem$zodSchema,
} from "./subscriptionsubscriptionlineitem.js";
import {
  TypesAggregationType,
  TypesAggregationType$zodSchema,
} from "./typesaggregationtype.js";
import {
  TypesCommitmentInfo,
  TypesCommitmentInfo$zodSchema,
} from "./typescommitmentinfo.js";
import {
  TypesWindowSize,
  TypesWindowSize$zodSchema,
} from "./typeswindowsize.js";

export type DtoUsageAnalyticItem = {
  add_on_id?: string | undefined;
  addon?: GithubComFlexpriceFlexpriceInternalDomainAddonAddon | undefined;
  aggregation_type?: TypesAggregationType | undefined;
  commitment_info?: TypesCommitmentInfo | undefined;
  currency?: string | undefined;
  event_count?: number | undefined;
  event_name?: string | undefined;
  feature?: GithubComFlexpriceFlexpriceInternalDomainFeatureFeature | undefined;
  feature_id?: string | undefined;
  meter?: MeterMeter | undefined;
  meter_id?: string | undefined;
  name?: string | undefined;
  plan?: GithubComFlexpriceFlexpriceInternalDomainPlanPlan | undefined;
  plan_id?: string | undefined;
  points?: Array<DtoUsageAnalyticPoint> | undefined;
  price?: DtoPriceResponse | undefined;
  price_id?: string | undefined;
  properties?: { [k: string]: string } | undefined;
  source?: string | undefined;
  sources?: Array<string> | undefined;
  sub_line_item_id?: string | undefined;
  subscription_id?: string | undefined;
  subscription_line_item?: SubscriptionSubscriptionLineItem | undefined;
  total_cost?: string | undefined;
  total_usage?: string | undefined;
  unit?: string | undefined;
  unit_plural?: string | undefined;
  window_size?: TypesWindowSize | undefined;
};

export const DtoUsageAnalyticItem$zodSchema: z.ZodType<DtoUsageAnalyticItem> = z
  .object({
    add_on_id: z.string().optional(),
    addon: GithubComFlexpriceFlexpriceInternalDomainAddonAddon$zodSchema
      .optional(),
    aggregation_type: TypesAggregationType$zodSchema.optional(),
    commitment_info: TypesCommitmentInfo$zodSchema.optional(),
    currency: z.string().optional(),
    event_count: z.int().optional(),
    event_name: z.string().optional(),
    feature: GithubComFlexpriceFlexpriceInternalDomainFeatureFeature$zodSchema
      .optional(),
    feature_id: z.string().optional(),
    meter: MeterMeter$zodSchema.optional(),
    meter_id: z.string().optional(),
    name: z.string().optional(),
    plan: GithubComFlexpriceFlexpriceInternalDomainPlanPlan$zodSchema
      .optional(),
    plan_id: z.string().optional(),
    points: z.array(DtoUsageAnalyticPoint$zodSchema).optional(),
    price: DtoPriceResponse$zodSchema.optional(),
    price_id: z.string().optional(),
    properties: z.record(z.string(), z.string()).optional(),
    source: z.string().optional(),
    sources: z.array(z.string()).optional(),
    sub_line_item_id: z.string().optional(),
    subscription_id: z.string().optional(),
    subscription_line_item: SubscriptionSubscriptionLineItem$zodSchema
      .optional(),
    total_cost: z.string().optional(),
    total_usage: z.string().optional(),
    unit: z.string().optional(),
    unit_plural: z.string().optional(),
    window_size: TypesWindowSize$zodSchema.optional(),
  });
