/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoIntegrationEntityMapping,
  DtoIntegrationEntityMapping$zodSchema,
} from "./dtointegrationentitymapping.js";

/**
 * Request object for updating an existing customer. All fields are optional - only provided fields will be updated
 */
export type DtoUpdateCustomerRequest = {
  address_city?: string | undefined;
  address_country?: string | undefined;
  address_line1?: string | undefined;
  address_line2?: string | undefined;
  address_postal_code?: string | undefined;
  address_state?: string | undefined;
  email?: string | undefined;
  external_id?: string | undefined;
  integration_entity_mapping?: Array<DtoIntegrationEntityMapping> | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  parent_customer_external_id?: string | undefined;
  parent_customer_id?: string | undefined;
};

export const DtoUpdateCustomerRequest$zodSchema: z.ZodType<
  DtoUpdateCustomerRequest
> = z.object({
  address_city: z.string().optional(),
  address_country: z.string().optional(),
  address_line1: z.string().optional(),
  address_line2: z.string().optional(),
  address_postal_code: z.string().optional(),
  address_state: z.string().optional(),
  email: z.string().optional(),
  external_id: z.string().optional(),
  integration_entity_mapping: z.array(DtoIntegrationEntityMapping$zodSchema)
    .optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  name: z.string().optional(),
  parent_customer_external_id: z.string().optional(),
  parent_customer_id: z.string().optional(),
}).describe(
  "Request object for updating an existing customer. All fields are optional - only provided fields will be updated",
);
