/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesTaskStatus,
  TypesTaskStatus$zodSchema,
} from "./typestaskstatus.js";

export type DtoUpdateTaskStatusRequest = { task_status: TypesTaskStatus };

export const DtoUpdateTaskStatusRequest$zodSchema: z.ZodType<
  DtoUpdateTaskStatusRequest
> = z.object({
  task_status: TypesTaskStatus$zodSchema,
});
