/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesTaxRateStatus,
  TypesTaxRateStatus$zodSchema,
} from "./typestaxratestatus.js";

export type DtoUpdateTaxRateRequest = {
  code?: string | undefined;
  description?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  tax_rate_status?: TypesTaxRateStatus | undefined;
};

export const DtoUpdateTaxRateRequest$zodSchema: z.ZodType<
  DtoUpdateTaxRateRequest
> = z.object({
  code: z.string().optional(),
  description: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  name: z.string().optional(),
  tax_rate_status: TypesTaxRateStatus$zodSchema.optional(),
});
