/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoUpdateInvoiceRequest = {
  due_date?: string | undefined;
  invoice_pdf_url?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
};

export const DtoUpdateInvoiceRequest$zodSchema: z.ZodType<
  DtoUpdateInvoiceRequest
> = z.object({
  due_date: z.string().optional(),
  invoice_pdf_url: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
});
