/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesAlertSettings,
  TypesAlertSettings$zodSchema,
} from "./typesalertsettings.js";
import { TypesAutoTopup, TypesAutoTopup$zodSchema } from "./typesautotopup.js";
import {
  TypesWalletConfig,
  TypesWalletConfig$zodSchema,
} from "./typeswalletconfig.js";

export type DtoUpdateWalletRequest = {
  alert_settings?: TypesAlertSettings | undefined;
  auto_topup?: TypesAutoTopup | undefined;
  config?: TypesWalletConfig | undefined;
  description?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
};

export const DtoUpdateWalletRequest$zodSchema: z.ZodType<
  DtoUpdateWalletRequest
> = z.object({
  alert_settings: TypesAlertSettings$zodSchema.optional(),
  auto_topup: TypesAutoTopup$zodSchema.optional(),
  config: TypesWalletConfig$zodSchema.optional(),
  description: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  name: z.string().optional(),
});
