/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoUsageResult = {
  value?: number | undefined;
  window_size?: string | undefined;
};

export const DtoUsageResult$zodSchema: z.ZodType<DtoUsageResult> = z.object({
  value: z.number().optional(),
  window_size: z.string().optional(),
});
