/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoUpdateScheduledTaskRequest = { enabled: boolean };

export const DtoUpdateScheduledTaskRequest$zodSchema: z.ZodType<
  DtoUpdateScheduledTaskRequest
> = z.object({
  enabled: z.boolean(),
});
