/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCreatePriceTier,
  DtoCreatePriceTier$zodSchema,
} from "./dtocreatepricetier.js";
import {
  PriceTransformQuantity,
  PriceTransformQuantity$zodSchema,
} from "./pricetransformquantity.js";
import {
  TypesBillingModel,
  TypesBillingModel$zodSchema,
} from "./typesbillingmodel.js";
import {
  TypesBillingPeriod,
  TypesBillingPeriod$zodSchema,
} from "./typesbillingperiod.js";
import {
  TypesBillingTier,
  TypesBillingTier$zodSchema,
} from "./typesbillingtier.js";
import {
  TypesCommitmentType,
  TypesCommitmentType$zodSchema,
} from "./typescommitmenttype.js";

export type DtoUpdateSubscriptionLineItemRequest = {
  amount?: string | undefined;
  billing_model?: TypesBillingModel | undefined;
  commitment_amount?: number | undefined;
  commitment_duration?: TypesBillingPeriod | undefined;
  commitment_overage_factor?: number | undefined;
  commitment_quantity?: number | undefined;
  commitment_true_up_enabled?: boolean | undefined;
  commitment_type?: TypesCommitmentType | undefined;
  commitment_windowed?: boolean | undefined;
  effective_from?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  tier_mode?: TypesBillingTier | undefined;
  tiers?: Array<DtoCreatePriceTier> | undefined;
  transform_quantity?: PriceTransformQuantity | undefined;
};

export const DtoUpdateSubscriptionLineItemRequest$zodSchema: z.ZodType<
  DtoUpdateSubscriptionLineItemRequest
> = z.object({
  amount: z.string().optional(),
  billing_model: TypesBillingModel$zodSchema.optional(),
  commitment_amount: z.number().optional(),
  commitment_duration: TypesBillingPeriod$zodSchema.optional(),
  commitment_overage_factor: z.number().optional(),
  commitment_quantity: z.number().optional(),
  commitment_true_up_enabled: z.boolean().optional(),
  commitment_type: TypesCommitmentType$zodSchema.optional(),
  commitment_windowed: z.boolean().optional(),
  effective_from: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  tier_mode: TypesBillingTier$zodSchema.optional(),
  tiers: z.array(DtoCreatePriceTier$zodSchema).optional(),
  transform_quantity: PriceTransformQuantity$zodSchema.optional(),
});
