/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesPaymentStatus,
  TypesPaymentStatus$zodSchema,
} from "./typespaymentstatus.js";

export type DtoUpdatePaymentStatusRequest = {
  amount?: string | undefined;
  payment_status: TypesPaymentStatus;
};

export const DtoUpdatePaymentStatusRequest$zodSchema: z.ZodType<
  DtoUpdatePaymentStatusRequest
> = z.object({
  amount: z.string().optional(),
  payment_status: TypesPaymentStatus$zodSchema,
});
