/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesSubscriptionStatus,
  TypesSubscriptionStatus$zodSchema,
} from "./typessubscriptionstatus.js";

export type DtoUpdateSubscriptionRequest = {
  cancel_at?: string | undefined;
  cancel_at_period_end?: boolean | undefined;
  parent_subscription_id?: string | undefined;
  status?: TypesSubscriptionStatus | undefined;
};

export const DtoUpdateSubscriptionRequest$zodSchema: z.ZodType<
  DtoUpdateSubscriptionRequest
> = z.object({
  cancel_at: z.string().optional(),
  cancel_at_period_end: z.boolean().optional(),
  parent_subscription_id: z.string().optional(),
  status: TypesSubscriptionStatus$zodSchema.optional(),
});
