/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoTenantBillingDetails,
  DtoTenantBillingDetails$zodSchema,
} from "./dtotenantbillingdetails.js";

export type DtoUpdateTenantRequest = {
  billing_details?: DtoTenantBillingDetails | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
};

export const DtoUpdateTenantRequest$zodSchema: z.ZodType<
  DtoUpdateTenantRequest
> = z.object({
  billing_details: DtoTenantBillingDetails$zodSchema.optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  name: z.string().optional(),
});
