/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoUpdateEnvironmentRequest = {
  name?: string | undefined;
  type?: string | undefined;
};

export const DtoUpdateEnvironmentRequest$zodSchema: z.ZodType<
  DtoUpdateEnvironmentRequest
> = z.object({
  name: z.string().optional(),
  type: z.string().optional(),
});
