/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoUpdatePaymentRequest = {
  error_message?: string | undefined;
  failed_at?: string | undefined;
  gateway_payment_id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  payment_gateway?: string | undefined;
  payment_method_id?: string | undefined;
  payment_status?: string | undefined;
  succeeded_at?: string | undefined;
};

export const DtoUpdatePaymentRequest$zodSchema: z.ZodType<
  DtoUpdatePaymentRequest
> = z.object({
  error_message: z.string().optional(),
  failed_at: z.string().optional(),
  gateway_payment_id: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  payment_gateway: z.string().optional(),
  payment_method_id: z.string().optional(),
  payment_status: z.string().optional(),
  succeeded_at: z.string().optional(),
});
