/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoUpdatePriceUnitRequest = {
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
};

export const DtoUpdatePriceUnitRequest$zodSchema: z.ZodType<
  DtoUpdatePriceUnitRequest
> = z.object({
  metadata: z.record(z.string(), z.string()).optional(),
  name: z.string().optional(),
});
