/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PaymentStatus, PaymentStatus$zodSchema } from "./paymentstatus.js";

export type DtoUpdatePaymentStatusRequest = {
  amount?: string | undefined;
  payment_status: PaymentStatus;
};

export const DtoUpdatePaymentStatusRequest$zodSchema: z.ZodType<
  DtoUpdatePaymentStatusRequest
> = z.object({
  amount: z.string().optional(),
  payment_status: PaymentStatus$zodSchema,
});
