/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DtoUpdateAddonRequest = {
  description?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  name?: string | undefined;
};

export const DtoUpdateAddonRequest$zodSchema: z.ZodType<DtoUpdateAddonRequest> =
  z.object({
    description: z.string().optional(),
    metadata: z.record(z.string(), z.any()).optional(),
    name: z.string().optional(),
  });
