/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesAlertSettings,
  TypesAlertSettings$zodSchema,
} from "./typesalertsettings.js";
import {
  TypesAlertState,
  TypesAlertState$zodSchema,
} from "./typesalertstate.js";
import { TypesAutoTopup, TypesAutoTopup$zodSchema } from "./typesautotopup.js";
import {
  TypesCreditBreakdown,
  TypesCreditBreakdown$zodSchema,
} from "./typescreditbreakdown.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";
import {
  TypesWalletConfig,
  TypesWalletConfig$zodSchema,
} from "./typeswalletconfig.js";
import {
  TypesWalletStatus,
  TypesWalletStatus$zodSchema,
} from "./typeswalletstatus.js";
import {
  TypesWalletType,
  TypesWalletType$zodSchema,
} from "./typeswallettype.js";

export type DtoWalletResponse = {
  alert_settings?: TypesAlertSettings | undefined;
  alert_state?: TypesAlertState | undefined;
  auto_topup?: TypesAutoTopup | undefined;
  balance?: string | undefined;
  config?: TypesWalletConfig | undefined;
  conversion_rate?: string | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  credit_balance?: string | undefined;
  credits_available_breakdown?: TypesCreditBreakdown | undefined;
  currency?: string | undefined;
  customer_id?: string | undefined;
  description?: string | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  status?: TypesStatus | undefined;
  tenant_id?: string | undefined;
  topup_conversion_rate?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
  wallet_status?: TypesWalletStatus | undefined;
  wallet_type?: TypesWalletType | undefined;
};

export const DtoWalletResponse$zodSchema: z.ZodType<DtoWalletResponse> = z
  .object({
    alert_settings: TypesAlertSettings$zodSchema.optional(),
    alert_state: TypesAlertState$zodSchema.optional(),
    auto_topup: TypesAutoTopup$zodSchema.optional(),
    balance: z.string().optional(),
    config: TypesWalletConfig$zodSchema.optional(),
    conversion_rate: z.string().optional(),
    created_at: z.string().optional(),
    created_by: z.string().optional(),
    credit_balance: z.string().optional(),
    credits_available_breakdown: TypesCreditBreakdown$zodSchema.optional(),
    currency: z.string().optional(),
    customer_id: z.string().optional(),
    description: z.string().optional(),
    environment_id: z.string().optional(),
    id: z.string().optional(),
    metadata: z.record(z.string(), z.string()).optional(),
    name: z.string().optional(),
    status: TypesStatus$zodSchema.optional(),
    tenant_id: z.string().optional(),
    topup_conversion_rate: z.string().optional(),
    updated_at: z.string().optional(),
    updated_by: z.string().optional(),
    wallet_status: TypesWalletStatus$zodSchema.optional(),
    wallet_type: TypesWalletType$zodSchema.optional(),
  });
