/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCustomerResponse,
  DtoCustomerResponse$zodSchema,
} from "./dtocustomerresponse.js";
import {
  DtoUserResponse,
  DtoUserResponse$zodSchema,
} from "./dtouserresponse.js";
import {
  DtoWalletResponse,
  DtoWalletResponse$zodSchema,
} from "./dtowalletresponse.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";
import {
  TypesTransactionReason,
  TypesTransactionReason$zodSchema,
} from "./typestransactionreason.js";
import {
  TypesTransactionStatus,
  TypesTransactionStatus$zodSchema,
} from "./typestransactionstatus.js";
import {
  TypesTransactionType,
  TypesTransactionType$zodSchema,
} from "./typestransactiontype.js";
import {
  TypesWalletTxReferenceType,
  TypesWalletTxReferenceType$zodSchema,
} from "./typeswallettxreferencetype.js";

export type DtoWalletTransactionResponse = {
  amount?: string | undefined;
  conversion_rate?: string | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  created_by_user?: DtoUserResponse | undefined;
  credit_amount?: string | undefined;
  credit_balance_after?: string | undefined;
  credit_balance_before?: string | undefined;
  credits_available?: string | undefined;
  currency?: string | undefined;
  customer?: DtoCustomerResponse | undefined;
  customer_id?: string | undefined;
  description?: string | undefined;
  environment_id?: string | undefined;
  expiry_date?: string | undefined;
  id?: string | undefined;
  idempotency_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  priority?: number | undefined;
  reference_id?: string | undefined;
  reference_type?: TypesWalletTxReferenceType | undefined;
  status?: TypesStatus | undefined;
  tenant_id?: string | undefined;
  topup_conversion_rate?: string | undefined;
  transaction_reason?: TypesTransactionReason | undefined;
  transaction_status?: TypesTransactionStatus | undefined;
  type?: TypesTransactionType | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
  wallet?: DtoWalletResponse | undefined;
  wallet_id?: string | undefined;
};

export const DtoWalletTransactionResponse$zodSchema: z.ZodType<
  DtoWalletTransactionResponse
> = z.object({
  amount: z.string().optional(),
  conversion_rate: z.string().optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  created_by_user: DtoUserResponse$zodSchema.optional(),
  credit_amount: z.string().optional(),
  credit_balance_after: z.string().optional(),
  credit_balance_before: z.string().optional(),
  credits_available: z.string().optional(),
  currency: z.string().optional(),
  customer: DtoCustomerResponse$zodSchema.optional(),
  customer_id: z.string().optional(),
  description: z.string().optional(),
  environment_id: z.string().optional(),
  expiry_date: z.string().optional(),
  id: z.string().optional(),
  idempotency_key: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  priority: z.int().optional(),
  reference_id: z.string().optional(),
  reference_type: TypesWalletTxReferenceType$zodSchema.optional(),
  status: TypesStatus$zodSchema.optional(),
  tenant_id: z.string().optional(),
  topup_conversion_rate: z.string().optional(),
  transaction_reason: TypesTransactionReason$zodSchema.optional(),
  transaction_status: TypesTransactionStatus$zodSchema.optional(),
  type: TypesTransactionType$zodSchema.optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
  wallet: DtoWalletResponse$zodSchema.optional(),
  wallet_id: z.string().optional(),
});
