/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsErrorDetail,
  ErrorsErrorDetail$zodSchema,
} from "./errorserrordetail.js";

export type ErrorsErrorResponse = {
  error?: ErrorsErrorDetail | undefined;
  success?: boolean | undefined;
};

export const ErrorsErrorResponse$zodSchema: z.ZodType<ErrorsErrorResponse> = z
  .object({
    error: ErrorsErrorDetail$zodSchema.optional(),
    success: z.boolean().optional(),
  });
