/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoSuccessResponse,
  DtoSuccessResponse$zodSchema,
} from "./dtosuccessresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type FinalizeInvoiceRequest = { id: string };

export const FinalizeInvoiceRequest$zodSchema: z.ZodType<
  FinalizeInvoiceRequest
> = z.object({
  id: z.string().describe("Invoice ID"),
});

export type FinalizeInvoiceResponse = DtoSuccessResponse | ErrorsErrorResponse;

export const FinalizeInvoiceResponse$zodSchema: z.ZodType<
  FinalizeInvoiceResponse
> = z.union([
  DtoSuccessResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
