/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoAddonResponse,
  DtoAddonResponse$zodSchema,
} from "./dtoaddonresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetAddonRequest = { id: string };

export const GetAddonRequest$zodSchema: z.ZodType<GetAddonRequest> = z.object({
  id: z.string().describe("Addon ID"),
});

export type GetAddonResponse = DtoAddonResponse | ErrorsErrorResponse;

export const GetAddonResponse$zodSchema: z.ZodType<GetAddonResponse> = z.union([
  DtoAddonResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
