/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCostsheetResponse,
  DtoCostsheetResponse$zodSchema,
} from "./dtocostsheetresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetActiveCostsheetResponse =
  | DtoCostsheetResponse
  | ErrorsErrorResponse;

export const GetActiveCostsheetResponse$zodSchema: z.ZodType<
  GetActiveCostsheetResponse
> = z.union([
  DtoCostsheetResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
