/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoAddonResponse,
  DtoAddonResponse$zodSchema,
} from "./dtoaddonresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetAddonByLookupKeyRequest = { lookup_key: string };

export const GetAddonByLookupKeyRequest$zodSchema: z.ZodType<
  GetAddonByLookupKeyRequest
> = z.object({
  lookup_key: z.string().describe("Addon Lookup Key"),
});

export type GetAddonByLookupKeyResponse =
  | DtoAddonResponse
  | ErrorsErrorResponse;

export const GetAddonByLookupKeyResponse$zodSchema: z.ZodType<
  GetAddonByLookupKeyResponse
> = z.union([
  DtoAddonResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
