/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListEntitlementsResponse,
  DtoListEntitlementsResponse$zodSchema,
} from "./dtolistentitlementsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetAddonEntitlementsRequest = { id: string };

export const GetAddonEntitlementsRequest$zodSchema: z.ZodType<
  GetAddonEntitlementsRequest
> = z.object({
  id: z.string().describe("Addon ID"),
});

export type GetAddonEntitlementsResponse =
  | DtoListEntitlementsResponse
  | ErrorsErrorResponse;

export const GetAddonEntitlementsResponse$zodSchema: z.ZodType<
  GetAddonEntitlementsResponse
> = z.union([
  DtoListEntitlementsResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
