/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCustomerResponse,
  DtoCustomerResponse$zodSchema,
} from "./dtocustomerresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetCustomerByExternalIdRequest = { external_id: string };

export const GetCustomerByExternalIdRequest$zodSchema: z.ZodType<
  GetCustomerByExternalIdRequest
> = z.object({
  external_id: z.string().describe("Customer External ID"),
});

export type GetCustomerByExternalIdResponse =
  | DtoCustomerResponse
  | ErrorsErrorResponse;

export const GetCustomerByExternalIdResponse$zodSchema: z.ZodType<
  GetCustomerByExternalIdResponse
> = z.union([
  DtoCustomerResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
