/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCouponResponse,
  DtoCouponResponse$zodSchema,
} from "./dtocouponresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetCouponRequest = { id: string };

export const GetCouponRequest$zodSchema: z.ZodType<GetCouponRequest> = z.object(
  {
    id: z.string().describe("Coupon ID"),
  },
);

export type GetCouponResponse = DtoCouponResponse | ErrorsErrorResponse;

export const GetCouponResponse$zodSchema: z.ZodType<GetCouponResponse> = z
  .union([
    DtoCouponResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
