/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoGetCostsheetResponse,
  DtoGetCostsheetResponse$zodSchema,
} from "./dtogetcostsheetresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetCostsheetRequest = { id: string; expand?: string | undefined };

export const GetCostsheetRequest$zodSchema: z.ZodType<GetCostsheetRequest> = z
  .object({
    expand: z.string().describe(
      "Comma-separated list of fields to expand (e.g., 'prices')",
    ).optional(),
    id: z.string().describe("Costsheet ID"),
  });

export type GetCostsheetResponse =
  | DtoGetCostsheetResponse
  | ErrorsErrorResponse;

export const GetCostsheetResponse$zodSchema: z.ZodType<GetCostsheetResponse> = z
  .union([
    DtoGetCostsheetResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
