/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCustomerUsageSummaryResponse,
  DtoCustomerUsageSummaryResponse$zodSchema,
} from "./dtocustomerusagesummaryresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetCustomerUsageSummaryRequest = {
  customer_id?: string | undefined;
  customer_lookup_key?: string | undefined;
  feature_ids?: Array<string> | undefined;
  feature_lookup_keys?: Array<string> | undefined;
  subscription_ids?: Array<string> | undefined;
};

export const GetCustomerUsageSummaryRequest$zodSchema: z.ZodType<
  GetCustomerUsageSummaryRequest
> = z.object({
  customer_id: z.string().optional(),
  customer_lookup_key: z.string().optional(),
  feature_ids: z.array(z.string()).optional(),
  feature_lookup_keys: z.array(z.string()).optional(),
  subscription_ids: z.array(z.string()).optional(),
});

export type GetCustomerUsageSummaryResponse =
  | DtoCustomerUsageSummaryResponse
  | ErrorsErrorResponse;

export const GetCustomerUsageSummaryResponse$zodSchema: z.ZodType<
  GetCustomerUsageSummaryResponse
> = z.union([
  DtoCustomerUsageSummaryResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
