/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoEntitlementResponse,
  DtoEntitlementResponse$zodSchema,
} from "./dtoentitlementresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetEntitlementRequest = { id: string };

export const GetEntitlementRequest$zodSchema: z.ZodType<GetEntitlementRequest> =
  z.object({
    id: z.string().describe("Entitlement ID"),
  });

export type GetEntitlementResponse =
  | DtoEntitlementResponse
  | ErrorsErrorResponse;

export const GetEntitlementResponse$zodSchema: z.ZodType<
  GetEntitlementResponse
> = z.union([
  DtoEntitlementResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
