/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoGetEventByIDResponse,
  DtoGetEventByIDResponse$zodSchema,
} from "./dtogeteventbyidresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetEventRequest = { id: string };

export const GetEventRequest$zodSchema: z.ZodType<GetEventRequest> = z.object({
  id: z.string().describe("Event ID"),
});

export type GetEventResponse = DtoGetEventByIDResponse | ErrorsErrorResponse;

export const GetEventResponse$zodSchema: z.ZodType<GetEventResponse> = z.union([
  DtoGetEventByIDResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
