/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoGetHuggingFaceBillingDataResponse,
  DtoGetHuggingFaceBillingDataResponse$zodSchema,
} from "./dtogethuggingfacebillingdataresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetHuggingfaceInferenceDataResponse =
  | DtoGetHuggingFaceBillingDataResponse
  | ErrorsErrorResponse;

export const GetHuggingfaceInferenceDataResponse$zodSchema: z.ZodType<
  GetHuggingfaceInferenceDataResponse
> = z.union([
  DtoGetHuggingFaceBillingDataResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
