/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoInvoiceResponse,
  DtoInvoiceResponse$zodSchema,
} from "./dtoinvoiceresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetInvoiceRequest = {
  id: string;
  expand_by_source?: boolean | undefined;
  group_by?: Array<string> | undefined;
};

export const GetInvoiceRequest$zodSchema: z.ZodType<GetInvoiceRequest> = z
  .object({
    expand_by_source: z.boolean().describe(
      "Include source-level price breakdown for usage line items (legacy)",
    ).optional(),
    group_by: z.array(z.string()).describe(
      "Group usage breakdown by specified fields (e.g., source, feature_id, properties.org_id)",
    ).optional(),
    id: z.string().describe("Invoice ID"),
  });

export type GetInvoiceResponse = DtoInvoiceResponse | ErrorsErrorResponse;

export const GetInvoiceResponse$zodSchema: z.ZodType<GetInvoiceResponse> = z
  .union([
    DtoInvoiceResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
