/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoSecretResponse,
  DtoSecretResponse$zodSchema,
} from "./dtosecretresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetIntegrationRequest = { provider: string };

export const GetIntegrationRequest$zodSchema: z.ZodType<GetIntegrationRequest> =
  z.object({
    provider: z.string().describe("Integration provider"),
  });

export type GetIntegrationResponse = DtoSecretResponse | ErrorsErrorResponse;

export const GetIntegrationResponse$zodSchema: z.ZodType<
  GetIntegrationResponse
> = z.union([
  DtoSecretResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
