/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../lib/base64.js";

export type GetInvoicePdfRequest = { id: string; url?: boolean | undefined };

export const GetInvoicePdfRequest$zodSchema: z.ZodType<GetInvoicePdfRequest> = z
  .object({
    id: z.string().describe("Invoice ID"),
    url: z.boolean().describe("Return presigned URL from s3 instead of PDF")
      .optional(),
  });

export type GetInvoicePdfResponse = Uint8Array | string | Uint8Array | string;

export const GetInvoicePdfResponse$zodSchema: z.ZodType<GetInvoicePdfResponse> =
  z.union([
    z.string().describe("Base64-encoded binary content").transform(
      b64$.bytesFromBase64,
    ),
    z.string().describe("Base64-encoded binary content").transform(
      b64$.bytesFromBase64,
    ),
  ]);
