/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoPlanResponse,
  DtoPlanResponse$zodSchema,
} from "./dtoplanresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetPlanRequest = { id: string };

export const GetPlanRequest$zodSchema: z.ZodType<GetPlanRequest> = z.object({
  id: z.string().describe("Plan ID"),
});

export type GetPlanResponse = DtoPlanResponse | ErrorsErrorResponse;

export const GetPlanResponse$zodSchema: z.ZodType<GetPlanResponse> = z.union([
  DtoPlanResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
