/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoPriceUnitResponse,
  DtoPriceUnitResponse$zodSchema,
} from "./dtopriceunitresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetPriceUnitRequest = { id: string };

export const GetPriceUnitRequest$zodSchema: z.ZodType<GetPriceUnitRequest> = z
  .object({
    id: z.string().describe("Price unit ID"),
  });

export type GetPriceUnitResponse = DtoPriceUnitResponse | ErrorsErrorResponse;

export const GetPriceUnitResponse$zodSchema: z.ZodType<GetPriceUnitResponse> = z
  .union([
    DtoPriceUnitResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
