/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoPaymentResponse,
  DtoPaymentResponse$zodSchema,
} from "./dtopaymentresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetPaymentRequest = { id: string };

export const GetPaymentRequest$zodSchema: z.ZodType<GetPaymentRequest> = z
  .object({
    id: z.string().describe("Payment ID"),
  });

export type GetPaymentResponse = DtoPaymentResponse | ErrorsErrorResponse;

export const GetPaymentResponse$zodSchema: z.ZodType<GetPaymentResponse> = z
  .union([
    DtoPaymentResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
