/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoPriceResponse,
  DtoPriceResponse$zodSchema,
} from "./dtopriceresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetPriceByLookupKeyRequest = { lookup_key: string };

export const GetPriceByLookupKeyRequest$zodSchema: z.ZodType<
  GetPriceByLookupKeyRequest
> = z.object({
  lookup_key: z.string().describe("Lookup key"),
});

export type GetPriceByLookupKeyResponse =
  | DtoPriceResponse
  | ErrorsErrorResponse;

export const GetPriceByLookupKeyResponse$zodSchema: z.ZodType<
  GetPriceByLookupKeyResponse
> = z.union([
  DtoPriceResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
