/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoPriceResponse,
  DtoPriceResponse$zodSchema,
} from "./dtopriceresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetPriceRequest = { id: string };

export const GetPriceRequest$zodSchema: z.ZodType<GetPriceRequest> = z.object({
  id: z.string().describe("Price ID"),
});

export type GetPriceResponse = DtoPriceResponse | ErrorsErrorResponse;

export const GetPriceResponse$zodSchema: z.ZodType<GetPriceResponse> = z.union([
  DtoPriceResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
