/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoPlanResponse,
  DtoPlanResponse$zodSchema,
} from "./dtoplanresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetPlanEntitlementsRequest = { id: string };

export const GetPlanEntitlementsRequest$zodSchema: z.ZodType<
  GetPlanEntitlementsRequest
> = z.object({
  id: z.string().describe("Plan ID"),
});

export type GetPlanEntitlementsResponse = DtoPlanResponse | ErrorsErrorResponse;

export const GetPlanEntitlementsResponse$zodSchema: z.ZodType<
  GetPlanEntitlementsResponse
> = z.union([
  DtoPlanResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
