/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoSubscriptionEntitlementsResponse,
  DtoSubscriptionEntitlementsResponse$zodSchema,
} from "./dtosubscriptionentitlementsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetSubscriptionEntitlementsRequest = {
  id: string;
  feature_ids?: Array<string> | undefined;
};

export const GetSubscriptionEntitlementsRequest$zodSchema: z.ZodType<
  GetSubscriptionEntitlementsRequest
> = z.object({
  feature_ids: z.array(z.string()).describe("Feature IDs to filter by")
    .optional(),
  id: z.string().describe("Subscription ID"),
});

export type GetSubscriptionEntitlementsResponse =
  | DtoSubscriptionEntitlementsResponse
  | ErrorsErrorResponse;

export const GetSubscriptionEntitlementsResponse$zodSchema: z.ZodType<
  GetSubscriptionEntitlementsResponse
> = z.union([
  DtoSubscriptionEntitlementsResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
