/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  DtoTaxRateResponse,
  DtoTaxRateResponse$zodSchema,
} from "./dtotaxrateresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export const GetTaxRatesOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetTaxRatesOrder = ClosedEnum<typeof GetTaxRatesOrder>;

export const GetTaxRatesOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export const Scope = {
  Internal: "INTERNAL",
  External: "EXTERNAL",
  Onetime: "ONETIME",
} as const;
export type Scope = ClosedEnum<typeof Scope>;

export const Scope$zodSchema = z.enum([
  "INTERNAL",
  "EXTERNAL",
  "ONETIME",
]);

export const GetTaxRatesStatus = {
  Published: "published",
  Deleted: "deleted",
  Archived: "archived",
} as const;
export type GetTaxRatesStatus = ClosedEnum<typeof GetTaxRatesStatus>;

export const GetTaxRatesStatus$zodSchema = z.enum([
  "published",
  "deleted",
  "archived",
]);

export type GetTaxRatesRequest = {
  end_time?: string | undefined;
  expand?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: GetTaxRatesOrder | undefined;
  scope?: Scope | undefined;
  start_time?: string | undefined;
  status?: GetTaxRatesStatus | undefined;
  taxrate_codes?: Array<string> | undefined;
  taxrate_ids?: Array<string> | undefined;
};

export const GetTaxRatesRequest$zodSchema: z.ZodType<GetTaxRatesRequest> = z
  .object({
    end_time: z.string().optional(),
    expand: z.string().optional(),
    limit: z.int().optional(),
    offset: z.int().optional(),
    order: GetTaxRatesOrder$zodSchema.optional(),
    scope: Scope$zodSchema.optional(),
    start_time: z.string().optional(),
    status: GetTaxRatesStatus$zodSchema.optional(),
    taxrate_codes: z.array(z.string()).optional(),
    taxrate_ids: z.array(z.string()).optional(),
  });

export type GetTaxRatesResponse =
  | Array<DtoTaxRateResponse>
  | ErrorsErrorResponse;

export const GetTaxRatesResponse$zodSchema: z.ZodType<GetTaxRatesResponse> = z
  .union([
    z.array(DtoTaxRateResponse$zodSchema).describe("OK"),
    ErrorsErrorResponse$zodSchema,
  ]);
