/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoTaxAssociationResponse,
  DtoTaxAssociationResponse$zodSchema,
} from "./dtotaxassociationresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetTaxAssociationRequest = { id: string };

export const GetTaxAssociationRequest$zodSchema: z.ZodType<
  GetTaxAssociationRequest
> = z.object({
  id: z.string().describe("Tax Config ID"),
});

export type GetTaxAssociationResponse =
  | DtoTaxAssociationResponse
  | ErrorsErrorResponse;

export const GetTaxAssociationResponse$zodSchema: z.ZodType<
  GetTaxAssociationResponse
> = z.union([
  DtoTaxAssociationResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
