/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoWalletBalanceResponse,
  DtoWalletBalanceResponse$zodSchema,
} from "./dtowalletbalanceresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetWalletBalanceRequest = {
  id: string;
  expand?: string | undefined;
};

export const GetWalletBalanceRequest$zodSchema: z.ZodType<
  GetWalletBalanceRequest
> = z.object({
  expand: z.string().describe(
    "Expand fields (e.g., credits_available_breakdown)",
  ).optional(),
  id: z.string().describe("Wallet ID"),
});

export type GetWalletBalanceResponse =
  | DtoWalletBalanceResponse
  | ErrorsErrorResponse;

export const GetWalletBalanceResponse$zodSchema: z.ZodType<
  GetWalletBalanceResponse
> = z.union([
  DtoWalletBalanceResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
