/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoWalletResponse,
  DtoWalletResponse$zodSchema,
} from "./dtowalletresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetWalletsByCustomerIdRequest = { id: string };

export const GetWalletsByCustomerIdRequest$zodSchema: z.ZodType<
  GetWalletsByCustomerIdRequest
> = z.object({
  id: z.string().describe("Customer ID"),
});

export type GetWalletsByCustomerIdResponse =
  | Array<DtoWalletResponse>
  | ErrorsErrorResponse;

export const GetWalletsByCustomerIdResponse$zodSchema: z.ZodType<
  GetWalletsByCustomerIdResponse
> = z.union([
  z.array(DtoWalletResponse$zodSchema).describe("OK"),
  ErrorsErrorResponse$zodSchema,
]);
