/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoWalletResponse,
  DtoWalletResponse$zodSchema,
} from "./dtowalletresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type GetWalletRequest = { id: string };

export const GetWalletRequest$zodSchema: z.ZodType<GetWalletRequest> = z.object(
  {
    id: z.string().describe("Wallet ID"),
  },
);

export type GetWalletResponse = DtoWalletResponse | ErrorsErrorResponse;

export const GetWalletResponse$zodSchema: z.ZodType<GetWalletResponse> = z
  .union([
    DtoWalletResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
