/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type HandleChargebeeWebhookRequest = {
  tenant_id: string;
  environment_id: string;
};

export const HandleChargebeeWebhookRequest$zodSchema: z.ZodType<
  HandleChargebeeWebhookRequest
> = z.object({
  environment_id: z.string().describe("Environment ID"),
  tenant_id: z.string().describe("Tenant ID"),
});

export type HandleChargebeeWebhookResponse =
  | { [k: string]: any }
  | { [k: string]: any }
  | { [k: string]: any }
  | { [k: string]: any };

export const HandleChargebeeWebhookResponse$zodSchema: z.ZodType<
  HandleChargebeeWebhookResponse
> = z.union([
  z.record(z.string(), z.any()).describe("Webhook processed successfully"),
  z.record(z.string(), z.any()).describe("Bad request"),
  z.record(z.string(), z.any()).describe("Unauthorized"),
  z.record(z.string(), z.any()).describe("Internal server error"),
]);
