/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type HandleHubspotWebhookRequest = {
  tenant_id: string;
  environment_id: string;
  xHubSpotSignatureV3: string;
};

export const HandleHubspotWebhookRequest$zodSchema: z.ZodType<
  HandleHubspotWebhookRequest
> = z.object({
  environment_id: z.string().describe("Environment ID"),
  tenant_id: z.string().describe("Tenant ID"),
  xHubSpotSignatureV3: z.string().describe("HubSpot webhook signature"),
});
