/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type HandleNomodWebhookRequest = {
  tenant_id: string;
  environment_id: string;
  xApiKey?: string | undefined;
};

export const HandleNomodWebhookRequest$zodSchema: z.ZodType<
  HandleNomodWebhookRequest
> = z.object({
  environment_id: z.string().describe("Environment ID"),
  tenant_id: z.string().describe("Tenant ID"),
  xApiKey: z.string().describe("Nomod webhook secret (if configured)")
    .optional(),
});

export type HandleNomodWebhookResponse = { [k: string]: any } | {
  [k: string]: any;
};

export const HandleNomodWebhookResponse$zodSchema: z.ZodType<
  HandleNomodWebhookResponse
> = z.union([
  z.record(z.string(), z.any()).describe("Webhook processed successfully"),
  z.record(z.string(), z.any()).describe(
    "Unauthorized - invalid or missing X-API-KEY",
  ),
]);
