/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type HandleQuickbooksWebhookRequest = {
  tenant_id: string;
  environment_id: string;
  intuitSignature?: string | undefined;
};

export const HandleQuickbooksWebhookRequest$zodSchema: z.ZodType<
  HandleQuickbooksWebhookRequest
> = z.object({
  environment_id: z.string().describe("Environment ID"),
  intuitSignature: z.string().describe("QuickBooks webhook signature")
    .optional(),
  tenant_id: z.string().describe("Tenant ID"),
});

export type HandleQuickbooksWebhookResponse =
  | { [k: string]: any }
  | { [k: string]: any }
  | { [k: string]: any }
  | { [k: string]: any };

export const HandleQuickbooksWebhookResponse$zodSchema: z.ZodType<
  HandleQuickbooksWebhookResponse
> = z.union([
  z.record(z.string(), z.any()).describe("Webhook processed successfully"),
  z.record(z.string(), z.any()).describe("Bad request"),
  z.record(z.string(), z.any()).describe("Unauthorized - invalid signature"),
  z.record(z.string(), z.any()).describe("Internal server error"),
]);
