/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type HandleMoyasarWebhookRequest = {
  tenant_id: string;
  environment_id: string;
  xMoyasarSignature?: string | undefined;
};

export const HandleMoyasarWebhookRequest$zodSchema: z.ZodType<
  HandleMoyasarWebhookRequest
> = z.object({
  environment_id: z.string().describe("Environment ID"),
  tenant_id: z.string().describe("Tenant ID"),
  xMoyasarSignature: z.string().describe("Moyasar webhook signature")
    .optional(),
});
