/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type HandleStripeWebhookRequest = {
  tenant_id: string;
  environment_id: string;
  stripeSignature: string;
};

export const HandleStripeWebhookRequest$zodSchema: z.ZodType<
  HandleStripeWebhookRequest
> = z.object({
  environment_id: z.string().describe("Environment ID"),
  stripeSignature: z.string().describe("Stripe webhook signature"),
  tenant_id: z.string().describe("Tenant ID"),
});

export type HandleStripeWebhookResponse = { [k: string]: any } | {
  [k: string]: any;
} | { [k: string]: any };

export const HandleStripeWebhookResponse$zodSchema: z.ZodType<
  HandleStripeWebhookResponse
> = z.union([
  z.record(z.string(), z.any()).describe("Webhook processed successfully"),
  z.record(z.string(), z.any()).describe(
    "Bad request - missing parameters or invalid signature",
  ),
  z.record(z.string(), z.any()).describe("Internal server error"),
]);
