/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  FilterCondition,
  FilterCondition$zodSchema,
} from "./filtercondition.js";
import { InvoiceStatus, InvoiceStatus$zodSchema } from "./invoicestatus.js";
import { InvoiceType, InvoiceType$zodSchema } from "./invoicetype.js";
import { PaymentStatus, PaymentStatus$zodSchema } from "./paymentstatus.js";
import { SortCondition, SortCondition$zodSchema } from "./sortcondition.js";
import { Status, Status$zodSchema } from "./status.js";

export const InvoiceFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type InvoiceFilterOrder = ClosedEnum<typeof InvoiceFilterOrder>;

export const InvoiceFilterOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type InvoiceFilter = {
  amount_due_gt?: number | undefined;
  amount_remaining_gt?: number | undefined;
  customer_id?: string | undefined;
  end_time?: string | undefined;
  expand?: string | undefined;
  external_customer_id?: string | undefined;
  filters?: Array<FilterCondition> | undefined;
  invoice_ids?: Array<string> | undefined;
  invoice_status?: Array<InvoiceStatus> | undefined;
  invoice_type?: InvoiceType | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: InvoiceFilterOrder | undefined;
  payment_status?: Array<PaymentStatus> | undefined;
  period_end_gte?: string | undefined;
  period_end_lte?: string | undefined;
  period_start_gte?: string | undefined;
  period_start_lte?: string | undefined;
  skip_line_items?: boolean | undefined;
  sort?: Array<SortCondition> | undefined;
  start_time?: string | undefined;
  status?: Status | undefined;
  subscription_id?: string | undefined;
};

export const InvoiceFilter$zodSchema: z.ZodType<InvoiceFilter> = z.object({
  amount_due_gt: z.number().optional(),
  amount_remaining_gt: z.number().optional(),
  customer_id: z.string().optional(),
  end_time: z.string().optional(),
  expand: z.string().optional(),
  external_customer_id: z.string().optional(),
  filters: z.array(FilterCondition$zodSchema).optional(),
  invoice_ids: z.array(z.string()).optional(),
  invoice_status: z.array(InvoiceStatus$zodSchema).optional(),
  invoice_type: InvoiceType$zodSchema.optional(),
  limit: z.int().optional(),
  offset: z.int().optional(),
  order: InvoiceFilterOrder$zodSchema.optional(),
  payment_status: z.array(PaymentStatus$zodSchema).optional(),
  period_end_gte: z.string().optional(),
  period_end_lte: z.string().optional(),
  period_start_gte: z.string().optional(),
  period_start_lte: z.string().optional(),
  skip_line_items: z.boolean().optional(),
  sort: z.array(SortCondition$zodSchema).optional(),
  start_time: z.string().optional(),
  status: Status$zodSchema.optional(),
  subscription_id: z.string().optional(),
});
