/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListTaxAssociationsResponse,
  DtoListTaxAssociationsResponse$zodSchema,
} from "./dtolisttaxassociationsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type ListTaxAssociationsRequest = {
  entity_type?: string | undefined;
  entity_id?: string | undefined;
  tax_rate_id?: string | undefined;
};

export const ListTaxAssociationsRequest$zodSchema: z.ZodType<
  ListTaxAssociationsRequest
> = z.object({
  entity_id: z.string().describe("Entity ID").optional(),
  entity_type: z.string().describe("Entity Type").optional(),
  tax_rate_id: z.string().describe("Tax Rate ID").optional(),
});

export type ListTaxAssociationsResponse =
  | DtoListTaxAssociationsResponse
  | ErrorsErrorResponse;

export const ListTaxAssociationsResponse$zodSchema: z.ZodType<
  ListTaxAssociationsResponse
> = z.union([
  DtoListTaxAssociationsResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
