/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  DtoListPaymentsResponse,
  DtoListPaymentsResponse$zodSchema,
} from "./dtolistpaymentsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export const ListPaymentsOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type ListPaymentsOrder = ClosedEnum<typeof ListPaymentsOrder>;

export const ListPaymentsOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export const ListPaymentsStatus = {
  Published: "published",
  Deleted: "deleted",
  Archived: "archived",
} as const;
export type ListPaymentsStatus = ClosedEnum<typeof ListPaymentsStatus>;

export const ListPaymentsStatus$zodSchema = z.enum([
  "published",
  "deleted",
  "archived",
]);

export type ListPaymentsRequest = {
  currency?: string | undefined;
  destination_id?: string | undefined;
  destination_type?: string | undefined;
  end_time?: string | undefined;
  expand?: string | undefined;
  gateway_payment_id?: string | undefined;
  gateway_tracking_id?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: ListPaymentsOrder | undefined;
  payment_gateway?: string | undefined;
  payment_ids?: Array<string> | undefined;
  payment_method_type?: string | undefined;
  payment_status?: string | undefined;
  sort?: string | undefined;
  start_time?: string | undefined;
  status?: ListPaymentsStatus | undefined;
};

export const ListPaymentsRequest$zodSchema: z.ZodType<ListPaymentsRequest> = z
  .object({
    currency: z.string().optional(),
    destination_id: z.string().optional(),
    destination_type: z.string().optional(),
    end_time: z.string().optional(),
    expand: z.string().optional(),
    gateway_payment_id: z.string().optional(),
    gateway_tracking_id: z.string().describe(
      "For filtering by gateway tracking ID",
    ).optional(),
    limit: z.int().optional(),
    offset: z.int().optional(),
    order: ListPaymentsOrder$zodSchema.optional(),
    payment_gateway: z.string().optional(),
    payment_ids: z.array(z.string()).optional(),
    payment_method_type: z.string().optional(),
    payment_status: z.string().optional(),
    sort: z.string().optional(),
    start_time: z.string().optional(),
    status: ListPaymentsStatus$zodSchema.optional(),
  });

export type ListPaymentsResponse =
  | DtoListPaymentsResponse
  | ErrorsErrorResponse;

export const ListPaymentsResponse$zodSchema: z.ZodType<ListPaymentsResponse> = z
  .union([
    DtoListPaymentsResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
