/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  DtoListPriceUnitsResponse,
  DtoListPriceUnitsResponse$zodSchema,
} from "./dtolistpriceunitsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

/**
 * Sort order
 */
export const ListPriceUnitsOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * Sort order
 */
export type ListPriceUnitsOrder = ClosedEnum<typeof ListPriceUnitsOrder>;

export const ListPriceUnitsOrder$zodSchema = z.enum([
  "asc",
  "desc",
]).describe("Sort order");

export type ListPriceUnitsRequest = {
  status?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  sort?: string | undefined;
  order?: ListPriceUnitsOrder | undefined;
};

export const ListPriceUnitsRequest$zodSchema: z.ZodType<ListPriceUnitsRequest> =
  z.object({
    limit: z.int().default(50).describe("Limit number of results"),
    offset: z.int().default(0).describe("Offset for pagination"),
    order: ListPriceUnitsOrder$zodSchema.optional(),
    sort: z.string().describe("Sort field").optional(),
    status: z.string().describe("Filter by status").optional(),
  });

export type ListPriceUnitsResponse =
  | DtoListPriceUnitsResponse
  | ErrorsErrorResponse;

export const ListPriceUnitsResponse$zodSchema: z.ZodType<
  ListPriceUnitsResponse
> = z.union([
  DtoListPriceUnitsResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
