/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListSubscriptionPausesResponse,
  DtoListSubscriptionPausesResponse$zodSchema,
} from "./dtolistsubscriptionpausesresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type ListSubscriptionPausesRequest = { id: string };

export const ListSubscriptionPausesRequest$zodSchema: z.ZodType<
  ListSubscriptionPausesRequest
> = z.object({
  id: z.string().describe("Subscription ID"),
});

export type ListSubscriptionPausesResponse =
  | Array<DtoListSubscriptionPausesResponse>
  | ErrorsErrorResponse;

export const ListSubscriptionPausesResponse$zodSchema: z.ZodType<
  ListSubscriptionPausesResponse
> = z.union([
  z.array(DtoListSubscriptionPausesResponse$zodSchema).describe("OK"),
  ErrorsErrorResponse$zodSchema,
]);
