/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoGetEventsResponse,
  DtoGetEventsResponse$zodSchema,
} from "./dtogeteventsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type ListRawEventsResponse = DtoGetEventsResponse | ErrorsErrorResponse;

export const ListRawEventsResponse$zodSchema: z.ZodType<ListRawEventsResponse> =
  z.union([
    DtoGetEventsResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
