/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  MeterAggregation,
  MeterAggregation$zodSchema,
} from "./meteraggregation.js";
import { MeterFilter, MeterFilter$zodSchema } from "./meterfilter.js";
import { ResetUsage, ResetUsage$zodSchema } from "./resetusage.js";
import { Status, Status$zodSchema } from "./status.js";

export type MeterMeter = {
  aggregation?: MeterAggregation | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  environment_id?: string | undefined;
  event_name?: string | undefined;
  filters?: Array<MeterFilter> | undefined;
  id?: string | undefined;
  name?: string | undefined;
  reset_usage?: ResetUsage | undefined;
  status?: Status | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const MeterMeter$zodSchema: z.ZodType<MeterMeter> = z.object({
  aggregation: MeterAggregation$zodSchema.optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  environment_id: z.string().optional(),
  event_name: z.string().optional(),
  filters: z.array(MeterFilter$zodSchema).optional(),
  id: z.string().optional(),
  name: z.string().optional(),
  reset_usage: ResetUsage$zodSchema.optional(),
  status: Status$zodSchema.optional(),
  tenant_id: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
});
