/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type MeterFilter = {
  key?: string | undefined;
  values?: Array<string> | undefined;
};

export const MeterFilter$zodSchema: z.ZodType<MeterFilter> = z.object({
  key: z.string().optional(),
  values: z.array(z.string()).optional(),
});
