/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AggregationType,
  AggregationType$zodSchema,
} from "./aggregationtype.js";
import { WindowSize, WindowSize$zodSchema } from "./windowsize.js";

export type MeterAggregation = {
  bucket_size?: WindowSize | undefined;
  field?: string | undefined;
  group_by?: string | undefined;
  multiplier?: string | undefined;
  type?: AggregationType | undefined;
};

export const MeterAggregation$zodSchema: z.ZodType<MeterAggregation> = z.object(
  {
    bucket_size: WindowSize$zodSchema.optional(),
    field: z.string().optional(),
    group_by: z.string().optional(),
    multiplier: z.string().optional(),
    type: AggregationType$zodSchema.optional(),
  },
);
