/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoPauseSubscriptionRequest,
  DtoPauseSubscriptionRequest$zodSchema,
} from "./dtopausesubscriptionrequest.js";
import {
  DtoSubscriptionPauseResponse,
  DtoSubscriptionPauseResponse$zodSchema,
} from "./dtosubscriptionpauseresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PauseSubscriptionRequest = {
  id: string;
  body: DtoPauseSubscriptionRequest;
};

export const PauseSubscriptionRequest$zodSchema: z.ZodType<
  PauseSubscriptionRequest
> = z.object({
  body: DtoPauseSubscriptionRequest$zodSchema,
  id: z.string().describe("Subscription ID"),
});

export type PauseSubscriptionResponse =
  | DtoSubscriptionPauseResponse
  | ErrorsErrorResponse;

export const PauseSubscriptionResponse$zodSchema: z.ZodType<
  PauseSubscriptionResponse
> = z.union([
  DtoSubscriptionPauseResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
