/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoClonePlanRequest,
  DtoClonePlanRequest$zodSchema,
} from "./dtocloneplanrequest.js";
import {
  DtoPlanResponse,
  DtoPlanResponse$zodSchema,
} from "./dtoplanresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type PostPlansIdCloneRequest = { id: string; body: DtoClonePlanRequest };

export const PostPlansIdCloneRequest$zodSchema: z.ZodType<
  PostPlansIdCloneRequest
> = z.object({
  body: DtoClonePlanRequest$zodSchema,
  id: z.string().describe("Source Plan ID"),
});

export type PostPlansIdCloneResponse = DtoPlanResponse | ErrorsErrorResponse;

export const PostPlansIdCloneResponse$zodSchema: z.ZodType<
  PostPlansIdCloneResponse
> = z.union([
  DtoPlanResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
