/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { TypesRoundType, TypesRoundType$zodSchema } from "./typesroundtype.js";

export type PriceTransformQuantity = {
  divide_by?: number | undefined;
  round?: TypesRoundType | undefined;
};

export const PriceTransformQuantity$zodSchema: z.ZodType<
  PriceTransformQuantity
> = z.object({
  divide_by: z.int().optional(),
  round: TypesRoundType$zodSchema.optional(),
});
