/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PricePriceTier = {
  flat_amount?: string | undefined;
  unit_amount?: string | undefined;
  up_to?: number | undefined;
};

export const PricePriceTier$zodSchema: z.ZodType<PricePriceTier> = z.object({
  flat_amount: z.string().optional(),
  unit_amount: z.string().optional(),
  up_to: z.int().optional(),
});
