/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoPaymentResponse,
  DtoPaymentResponse$zodSchema,
} from "./dtopaymentresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type ProcessPaymentRequest = { id: string };

export const ProcessPaymentRequest$zodSchema: z.ZodType<ProcessPaymentRequest> =
  z.object({
    id: z.string().describe("Payment ID"),
  });

export type ProcessPaymentResponse = DtoPaymentResponse | ErrorsErrorResponse;

export const ProcessPaymentResponse$zodSchema: z.ZodType<
  ProcessPaymentResponse
> = z.union([
  DtoPaymentResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
