/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListPlansResponse,
  DtoListPlansResponse$zodSchema,
} from "./dtolistplansresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type QueryPlanResponse = DtoListPlansResponse | ErrorsErrorResponse;

export const QueryPlanResponse$zodSchema: z.ZodType<QueryPlanResponse> = z
  .union([
    DtoListPlansResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
