/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListGroupsResponse,
  DtoListGroupsResponse$zodSchema,
} from "./dtolistgroupsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type QueryGroupResponse = DtoListGroupsResponse | ErrorsErrorResponse;

export const QueryGroupResponse$zodSchema: z.ZodType<QueryGroupResponse> = z
  .union([
    DtoListGroupsResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
