/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListCouponsResponse,
  DtoListCouponsResponse$zodSchema,
} from "./dtolistcouponsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type QueryCouponResponse = DtoListCouponsResponse | ErrorsErrorResponse;

export const QueryCouponResponse$zodSchema: z.ZodType<QueryCouponResponse> = z
  .union([
    DtoListCouponsResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
