/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListAddonsResponse,
  DtoListAddonsResponse$zodSchema,
} from "./dtolistaddonsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type QueryAddonResponse = DtoListAddonsResponse | ErrorsErrorResponse;

export const QueryAddonResponse$zodSchema: z.ZodType<QueryAddonResponse> = z
  .union([
    DtoListAddonsResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
