/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListCustomersResponse,
  DtoListCustomersResponse$zodSchema,
} from "./dtolistcustomersresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type QueryCustomerResponse =
  | DtoListCustomersResponse
  | ErrorsErrorResponse;

export const QueryCustomerResponse$zodSchema: z.ZodType<QueryCustomerResponse> =
  z.union([
    DtoListCustomersResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
