/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListWalletTransactionsResponse,
  DtoListWalletTransactionsResponse$zodSchema,
} from "./dtolistwallettransactionsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type QueryWalletTransactionResponse =
  | DtoListWalletTransactionsResponse
  | ErrorsErrorResponse;

export const QueryWalletTransactionResponse$zodSchema: z.ZodType<
  QueryWalletTransactionResponse
> = z.union([
  DtoListWalletTransactionsResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
