/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListInvoicesResponse,
  DtoListInvoicesResponse$zodSchema,
} from "./dtolistinvoicesresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type QueryInvoiceResponse =
  | DtoListInvoicesResponse
  | ErrorsErrorResponse;

export const QueryInvoiceResponse$zodSchema: z.ZodType<QueryInvoiceResponse> = z
  .union([
    DtoListInvoicesResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
