/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";
import {
  TypesListResponseDtoWalletResponse,
  TypesListResponseDtoWalletResponse$zodSchema,
} from "./typeslistresponsedtowalletresponse.js";

export type QueryWalletResponse =
  | TypesListResponseDtoWalletResponse
  | ErrorsErrorResponse;

export const QueryWalletResponse$zodSchema: z.ZodType<QueryWalletResponse> = z
  .union([
    TypesListResponseDtoWalletResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
