/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListAlertLogsResponse,
  DtoListAlertLogsResponse$zodSchema,
} from "./dtolistalertlogsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type QueryAlertLogResponse =
  | DtoListAlertLogsResponse
  | ErrorsErrorResponse;

export const QueryAlertLogResponse$zodSchema: z.ZodType<QueryAlertLogResponse> =
  z.union([
    DtoListAlertLogsResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
