/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoListWorkflowsResponse,
  DtoListWorkflowsResponse$zodSchema,
} from "./dtolistworkflowsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type QueryWorkflowResponse =
  | DtoListWorkflowsResponse
  | ErrorsErrorResponse;

export const QueryWorkflowResponse$zodSchema: z.ZodType<QueryWorkflowResponse> =
  z.union([
    DtoListWorkflowsResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
