/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

/**
 * Schedule Update Billing Period Request
 */
export type ScheduleUpdateBillingPeriodRequest = {};

export const ScheduleUpdateBillingPeriodRequest$zodSchema: z.ZodType<
  ScheduleUpdateBillingPeriodRequest
> = z.object({}).describe("Schedule Update Billing Period Request");

/**
 * OK
 */
export type ScheduleUpdateBillingPeriodResponseBody = {};

export const ScheduleUpdateBillingPeriodResponseBody$zodSchema: z.ZodType<
  ScheduleUpdateBillingPeriodResponseBody
> = z.object({}).describe("OK");

export type ScheduleUpdateBillingPeriodResponse =
  | ScheduleUpdateBillingPeriodResponseBody
  | ErrorsErrorResponse;

export const ScheduleUpdateBillingPeriodResponse$zodSchema: z.ZodType<
  ScheduleUpdateBillingPeriodResponse
> = z.union([
  z.lazy(() => ScheduleUpdateBillingPeriodResponseBody$zodSchema),
  ErrorsErrorResponse$zodSchema,
]);
