/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { TypesPauseMode, TypesPauseMode$zodSchema } from "./typespausemode.js";
import {
  TypesPauseStatus,
  TypesPauseStatus$zodSchema,
} from "./typespausestatus.js";
import {
  TypesResumeMode,
  TypesResumeMode$zodSchema,
} from "./typesresumemode.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";

export type SubscriptionSubscriptionPause = {
  created_at?: string | undefined;
  created_by?: string | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  original_period_end?: string | undefined;
  original_period_start?: string | undefined;
  pause_end?: string | undefined;
  pause_mode?: TypesPauseMode | undefined;
  pause_start?: string | undefined;
  pause_status?: TypesPauseStatus | undefined;
  reason?: string | undefined;
  resume_mode?: TypesResumeMode | undefined;
  resumed_at?: string | undefined;
  status?: TypesStatus | undefined;
  subscription_id?: string | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const SubscriptionSubscriptionPause$zodSchema: z.ZodType<
  SubscriptionSubscriptionPause
> = z.object({
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  original_period_end: z.string().optional(),
  original_period_start: z.string().optional(),
  pause_end: z.string().optional(),
  pause_mode: TypesPauseMode$zodSchema.optional(),
  pause_start: z.string().optional(),
  pause_status: TypesPauseStatus$zodSchema.optional(),
  reason: z.string().optional(),
  resume_mode: TypesResumeMode$zodSchema.optional(),
  resumed_at: z.string().optional(),
  status: TypesStatus$zodSchema.optional(),
  subscription_id: z.string().optional(),
  tenant_id: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
});
