/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";
import {
  ModelsTemporalWorkflowResult,
  ModelsTemporalWorkflowResult$zodSchema,
} from "./modelstemporalworkflowresult.js";

export type SyncPlanPricesRequest = { id: string };

export const SyncPlanPricesRequest$zodSchema: z.ZodType<SyncPlanPricesRequest> =
  z.object({
    id: z.string().describe("Plan ID"),
  });

export type SyncPlanPricesResponse =
  | ModelsTemporalWorkflowResult
  | ErrorsErrorResponse;

export const SyncPlanPricesResponse$zodSchema: z.ZodType<
  SyncPlanPricesResponse
> = z.union([
  ModelsTemporalWorkflowResult$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
