/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoTopUpWalletRequest,
  DtoTopUpWalletRequest$zodSchema,
} from "./dtotopupwalletrequest.js";
import {
  DtoTopUpWalletResponse,
  DtoTopUpWalletResponse$zodSchema,
} from "./dtotopupwalletresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type TopUpWalletRequest = { id: string; body: DtoTopUpWalletRequest };

export const TopUpWalletRequest$zodSchema: z.ZodType<TopUpWalletRequest> = z
  .object({
    body: DtoTopUpWalletRequest$zodSchema,
    id: z.string().describe("Wallet ID"),
  });

export type TopUpWalletResponse = DtoTopUpWalletResponse | ErrorsErrorResponse;

export const TopUpWalletResponse$zodSchema: z.ZodType<TopUpWalletResponse> = z
  .union([
    DtoTopUpWalletResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
