/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoSuccessResponse,
  DtoSuccessResponse$zodSchema,
} from "./dtosuccessresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type TriggerInvoiceCommsWebhookRequest = { id: string };

export const TriggerInvoiceCommsWebhookRequest$zodSchema: z.ZodType<
  TriggerInvoiceCommsWebhookRequest
> = z.object({
  id: z.string().describe("Invoice ID"),
});

export type TriggerInvoiceCommsWebhookResponse =
  | DtoSuccessResponse
  | ErrorsErrorResponse;

export const TriggerInvoiceCommsWebhookResponse$zodSchema: z.ZodType<
  TriggerInvoiceCommsWebhookResponse
> = z.union([
  DtoSuccessResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
