/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoTriggerForceRunRequest,
  DtoTriggerForceRunRequest$zodSchema,
} from "./dtotriggerforcerunrequest.js";
import {
  DtoTriggerForceRunResponse,
  DtoTriggerForceRunResponse$zodSchema,
} from "./dtotriggerforcerunresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type TriggerScheduledTaskRunRequest = {
  id: string;
  body?: DtoTriggerForceRunRequest | undefined;
};

export const TriggerScheduledTaskRunRequest$zodSchema: z.ZodType<
  TriggerScheduledTaskRunRequest
> = z.object({
  body: DtoTriggerForceRunRequest$zodSchema.optional(),
  id: z.string().describe("Scheduled Task ID"),
});

export type TriggerScheduledTaskRunResponse =
  | DtoTriggerForceRunResponse
  | ErrorsErrorResponse;

export const TriggerScheduledTaskRunResponse$zodSchema: z.ZodType<
  TriggerScheduledTaskRunResponse
> = z.union([
  DtoTriggerForceRunResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
