/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesProrationBehavior = {
  CreateProrations: "create_prorations",
  None: "none",
} as const;
export type TypesProrationBehavior = ClosedEnum<typeof TypesProrationBehavior>;

export const TypesProrationBehavior$zodSchema = z.enum([
  "create_prorations",
  "none",
]);
