/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  TypesFilterCondition,
  TypesFilterCondition$zodSchema,
} from "./typesfiltercondition.js";
import {
  TypesSortCondition,
  TypesSortCondition$zodSchema,
} from "./typessortcondition.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";
import {
  TypesTransactionReason,
  TypesTransactionReason$zodSchema,
} from "./typestransactionreason.js";
import {
  TypesTransactionStatus,
  TypesTransactionStatus$zodSchema,
} from "./typestransactionstatus.js";
import {
  TypesTransactionType,
  TypesTransactionType$zodSchema,
} from "./typestransactiontype.js";

export const TypesWalletTransactionFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type TypesWalletTransactionFilterOrder = ClosedEnum<
  typeof TypesWalletTransactionFilterOrder
>;

export const TypesWalletTransactionFilterOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type TypesWalletTransactionFilter = {
  created_by?: string | undefined;
  credits_available_gt?: number | undefined;
  end_time?: string | undefined;
  expand?: string | undefined;
  expiry_date_after?: string | undefined;
  expiry_date_before?: string | undefined;
  filters?: Array<TypesFilterCondition> | undefined;
  id?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: TypesWalletTransactionFilterOrder | undefined;
  priority?: number | undefined;
  reference_id?: string | undefined;
  reference_type?: string | undefined;
  sort?: Array<TypesSortCondition> | undefined;
  start_time?: string | undefined;
  status?: TypesStatus | undefined;
  transaction_reason?: TypesTransactionReason | undefined;
  transaction_status?: TypesTransactionStatus | undefined;
  type?: TypesTransactionType | undefined;
};

export const TypesWalletTransactionFilter$zodSchema: z.ZodType<
  TypesWalletTransactionFilter
> = z.object({
  created_by: z.string().optional(),
  credits_available_gt: z.number().optional(),
  end_time: z.string().optional(),
  expand: z.string().optional(),
  expiry_date_after: z.string().optional(),
  expiry_date_before: z.string().optional(),
  filters: z.array(TypesFilterCondition$zodSchema).optional(),
  id: z.string().optional(),
  limit: z.int().optional(),
  offset: z.int().optional(),
  order: TypesWalletTransactionFilterOrder$zodSchema.optional(),
  priority: z.int().optional(),
  reference_id: z.string().optional(),
  reference_type: z.string().optional(),
  sort: z.array(TypesSortCondition$zodSchema).optional(),
  start_time: z.string().optional(),
  status: TypesStatus$zodSchema.optional(),
  transaction_reason: TypesTransactionReason$zodSchema.optional(),
  transaction_status: TypesTransactionStatus$zodSchema.optional(),
  type: TypesTransactionType$zodSchema.optional(),
});
