/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesAlertThreshold,
  TypesAlertThreshold$zodSchema,
} from "./typesalertthreshold.js";

export type TypesAlertSettings = {
  alert_enabled?: boolean | undefined;
  critical?: TypesAlertThreshold | undefined;
  info?: TypesAlertThreshold | undefined;
  warning?: TypesAlertThreshold | undefined;
};

export const TypesAlertSettings$zodSchema: z.ZodType<TypesAlertSettings> = z
  .object({
    alert_enabled: z.boolean().optional(),
    critical: TypesAlertThreshold$zodSchema.optional(),
    info: TypesAlertThreshold$zodSchema.optional(),
    warning: TypesAlertThreshold$zodSchema.optional(),
  });
