/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesPauseStatus = {
  None: "none",
  Active: "active",
  Scheduled: "scheduled",
  Completed: "completed",
  Cancelled: "cancelled",
} as const;
export type TypesPauseStatus = ClosedEnum<typeof TypesPauseStatus>;

export const TypesPauseStatus$zodSchema = z.enum([
  "none",
  "active",
  "scheduled",
  "completed",
  "cancelled",
]);
