/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesBillingPeriod,
  TypesBillingPeriod$zodSchema,
} from "./typesbillingperiod.js";
import {
  TypesCommitmentType,
  TypesCommitmentType$zodSchema,
} from "./typescommitmenttype.js";

export type TypesCommitmentInfo = {
  amount?: string | undefined;
  computed_commitment_utilized_amount?: string | undefined;
  computed_overage_amount?: string | undefined;
  computed_true_up_amount?: string | undefined;
  duration?: TypesBillingPeriod | undefined;
  is_windowed?: boolean | undefined;
  overage_factor?: string | undefined;
  quantity?: string | undefined;
  true_up_enabled?: boolean | undefined;
  type?: TypesCommitmentType | undefined;
};

export const TypesCommitmentInfo$zodSchema: z.ZodType<TypesCommitmentInfo> = z
  .object({
    amount: z.string().optional(),
    computed_commitment_utilized_amount: z.string().optional(),
    computed_overage_amount: z.string().optional(),
    computed_true_up_amount: z.string().optional(),
    duration: TypesBillingPeriod$zodSchema.optional(),
    is_windowed: z.boolean().optional(),
    overage_factor: z.string().optional(),
    quantity: z.string().optional(),
    true_up_enabled: z.boolean().optional(),
    type: TypesCommitmentType$zodSchema.optional(),
  });
