/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  TypesFilterCondition,
  TypesFilterCondition$zodSchema,
} from "./typesfiltercondition.js";
import {
  TypesSortCondition,
  TypesSortCondition$zodSchema,
} from "./typessortcondition.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";

export const TypesCouponFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type TypesCouponFilterOrder = ClosedEnum<typeof TypesCouponFilterOrder>;

export const TypesCouponFilterOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type TypesCouponFilter = {
  coupon_ids?: Array<string> | undefined;
  expand?: string | undefined;
  filters?: Array<TypesFilterCondition> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: TypesCouponFilterOrder | undefined;
  sort?: Array<TypesSortCondition> | undefined;
  status?: TypesStatus | undefined;
};

export const TypesCouponFilter$zodSchema: z.ZodType<TypesCouponFilter> = z
  .object({
    coupon_ids: z.array(z.string()).optional(),
    expand: z.string().optional(),
    filters: z.array(TypesFilterCondition$zodSchema).optional(),
    limit: z.int().optional(),
    offset: z.int().optional(),
    order: TypesCouponFilterOrder$zodSchema.optional(),
    sort: z.array(TypesSortCondition$zodSchema).optional(),
    status: TypesStatus$zodSchema.optional(),
  });
