/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesBillingTier = {
  Volume: "VOLUME",
  Slab: "SLAB",
} as const;
export type TypesBillingTier = ClosedEnum<typeof TypesBillingTier>;

export const TypesBillingTier$zodSchema = z.enum([
  "VOLUME",
  "SLAB",
]);
