/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesFeatureType = {
  Metered: "metered",
  Boolean: "boolean",
  Static: "static",
} as const;
export type TypesFeatureType = ClosedEnum<typeof TypesFeatureType>;

export const TypesFeatureType$zodSchema = z.enum([
  "metered",
  "boolean",
  "static",
]);
