/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesPaymentStatus = {
  Initiated: "INITIATED",
  Pending: "PENDING",
  Processing: "PROCESSING",
  Succeeded: "SUCCEEDED",
  Overpaid: "OVERPAID",
  Failed: "FAILED",
  Refunded: "REFUNDED",
  PartiallyRefunded: "PARTIALLY_REFUNDED",
} as const;
export type TypesPaymentStatus = ClosedEnum<typeof TypesPaymentStatus>;

export const TypesPaymentStatus$zodSchema = z.enum([
  "INITIATED",
  "PENDING",
  "PROCESSING",
  "SUCCEEDED",
  "OVERPAID",
  "FAILED",
  "REFUNDED",
  "PARTIALLY_REFUNDED",
]);
