/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesAddonType = {
  Onetime: "onetime",
  MultipleInstance: "multiple_instance",
} as const;
export type TypesAddonType = ClosedEnum<typeof TypesAddonType>;

export const TypesAddonType$zodSchema = z.enum([
  "onetime",
  "multiple_instance",
]);
