/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesDataType = {
  String: "string",
  Number: "number",
  Date: "date",
  Array: "array",
} as const;
export type TypesDataType = ClosedEnum<typeof TypesDataType>;

export const TypesDataType$zodSchema = z.enum([
  "string",
  "number",
  "date",
  "array",
]);
