/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesSubscriptionStatus = {
  Active: "active",
  Paused: "paused",
  Cancelled: "cancelled",
  Incomplete: "incomplete",
  Trialing: "trialing",
  Draft: "draft",
} as const;
export type TypesSubscriptionStatus = ClosedEnum<
  typeof TypesSubscriptionStatus
>;

export const TypesSubscriptionStatus$zodSchema = z.enum([
  "active",
  "paused",
  "cancelled",
  "incomplete",
  "trialing",
  "draft",
]);
