/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { TypesAddonType, TypesAddonType$zodSchema } from "./typesaddontype.js";
import {
  TypesFilterCondition,
  TypesFilterCondition$zodSchema,
} from "./typesfiltercondition.js";
import {
  TypesSortCondition,
  TypesSortCondition$zodSchema,
} from "./typessortcondition.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";

export const TypesAddonFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type TypesAddonFilterOrder = ClosedEnum<typeof TypesAddonFilterOrder>;

export const TypesAddonFilterOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type TypesAddonFilter = {
  addon_ids?: Array<string> | undefined;
  addon_type?: TypesAddonType | undefined;
  end_time?: string | undefined;
  expand?: string | undefined;
  filters?: Array<TypesFilterCondition> | undefined;
  limit?: number | undefined;
  lookup_keys?: Array<string> | undefined;
  offset?: number | undefined;
  order?: TypesAddonFilterOrder | undefined;
  sort?: Array<TypesSortCondition> | undefined;
  start_time?: string | undefined;
  status?: TypesStatus | undefined;
};

export const TypesAddonFilter$zodSchema: z.ZodType<TypesAddonFilter> = z.object(
  {
    addon_ids: z.array(z.string()).optional(),
    addon_type: TypesAddonType$zodSchema.optional(),
    end_time: z.string().optional(),
    expand: z.string().optional(),
    filters: z.array(TypesFilterCondition$zodSchema).optional(),
    limit: z.int().optional(),
    lookup_keys: z.array(z.string()).optional(),
    offset: z.int().optional(),
    order: TypesAddonFilterOrder$zodSchema.optional(),
    sort: z.array(TypesSortCondition$zodSchema).optional(),
    start_time: z.string().optional(),
    status: TypesStatus$zodSchema.optional(),
  },
);
