/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  TypesEntitlementEntityType,
  TypesEntitlementEntityType$zodSchema,
} from "./typesentitlemententitytype.js";
import {
  TypesFeatureType,
  TypesFeatureType$zodSchema,
} from "./typesfeaturetype.js";
import {
  TypesFilterCondition,
  TypesFilterCondition$zodSchema,
} from "./typesfiltercondition.js";
import {
  TypesSortCondition,
  TypesSortCondition$zodSchema,
} from "./typessortcondition.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";

export const TypesEntitlementFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type TypesEntitlementFilterOrder = ClosedEnum<
  typeof TypesEntitlementFilterOrder
>;

export const TypesEntitlementFilterOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type TypesEntitlementFilter = {
  end_time?: string | undefined;
  entity_ids?: Array<string> | undefined;
  entity_type?: TypesEntitlementEntityType | undefined;
  expand?: string | undefined;
  feature_ids?: Array<string> | undefined;
  feature_type?: TypesFeatureType | undefined;
  filters?: Array<TypesFilterCondition> | undefined;
  is_enabled?: boolean | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: TypesEntitlementFilterOrder | undefined;
  plan_ids?: Array<string> | undefined;
  sort?: Array<TypesSortCondition> | undefined;
  start_time?: string | undefined;
  status?: TypesStatus | undefined;
};

export const TypesEntitlementFilter$zodSchema: z.ZodType<
  TypesEntitlementFilter
> = z.object({
  end_time: z.string().optional(),
  entity_ids: z.array(z.string()).optional(),
  entity_type: TypesEntitlementEntityType$zodSchema.optional(),
  expand: z.string().optional(),
  feature_ids: z.array(z.string()).optional(),
  feature_type: TypesFeatureType$zodSchema.optional(),
  filters: z.array(TypesFilterCondition$zodSchema).optional(),
  is_enabled: z.boolean().optional(),
  limit: z.int().optional(),
  offset: z.int().optional(),
  order: TypesEntitlementFilterOrder$zodSchema.optional(),
  plan_ids: z.array(z.string()).optional(),
  sort: z.array(TypesSortCondition$zodSchema).optional(),
  start_time: z.string().optional(),
  status: TypesStatus$zodSchema.optional(),
});
