/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesInvoiceStatus = {
  Draft: "DRAFT",
  Finalized: "FINALIZED",
  Voided: "VOIDED",
} as const;
export type TypesInvoiceStatus = ClosedEnum<typeof TypesInvoiceStatus>;

export const TypesInvoiceStatus$zodSchema = z.enum([
  "DRAFT",
  "FINALIZED",
  "VOIDED",
]);
