/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  TypesFilterCondition,
  TypesFilterCondition$zodSchema,
} from "./typesfiltercondition.js";
import {
  TypesSortCondition,
  TypesSortCondition$zodSchema,
} from "./typessortcondition.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";

export const TypesCustomerFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type TypesCustomerFilterOrder = ClosedEnum<
  typeof TypesCustomerFilterOrder
>;

export const TypesCustomerFilterOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type TypesCustomerFilter = {
  customer_ids?: Array<string> | undefined;
  email?: string | undefined;
  end_time?: string | undefined;
  expand?: string | undefined;
  external_id?: string | undefined;
  external_ids?: Array<string> | undefined;
  filters?: Array<TypesFilterCondition> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: TypesCustomerFilterOrder | undefined;
  parent_customer_ids?: Array<string> | undefined;
  sort?: Array<TypesSortCondition> | undefined;
  start_time?: string | undefined;
  status?: TypesStatus | undefined;
};

export const TypesCustomerFilter$zodSchema: z.ZodType<TypesCustomerFilter> = z
  .object({
    customer_ids: z.array(z.string()).optional(),
    email: z.string().optional(),
    end_time: z.string().optional(),
    expand: z.string().optional(),
    external_id: z.string().optional(),
    external_ids: z.array(z.string()).optional(),
    filters: z.array(TypesFilterCondition$zodSchema).optional(),
    limit: z.int().optional(),
    offset: z.int().optional(),
    order: TypesCustomerFilterOrder$zodSchema.optional(),
    parent_customer_ids: z.array(z.string()).optional(),
    sort: z.array(TypesSortCondition$zodSchema).optional(),
    start_time: z.string().optional(),
    status: TypesStatus$zodSchema.optional(),
  });
