/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  TypesFilterCondition,
  TypesFilterCondition$zodSchema,
} from "./typesfiltercondition.js";
import {
  TypesSortCondition,
  TypesSortCondition$zodSchema,
} from "./typessortcondition.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";

export const TypesPriceUnitFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type TypesPriceUnitFilterOrder = ClosedEnum<
  typeof TypesPriceUnitFilterOrder
>;

export const TypesPriceUnitFilterOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type TypesPriceUnitFilter = {
  end_time?: string | undefined;
  expand?: string | undefined;
  filters?: Array<TypesFilterCondition> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: TypesPriceUnitFilterOrder | undefined;
  price_unit_ids?: Array<string> | undefined;
  sort?: Array<TypesSortCondition> | undefined;
  start_time?: string | undefined;
  status?: TypesStatus | undefined;
};

export const TypesPriceUnitFilter$zodSchema: z.ZodType<TypesPriceUnitFilter> = z
  .object({
    end_time: z.string().optional(),
    expand: z.string().optional(),
    filters: z.array(TypesFilterCondition$zodSchema).optional(),
    limit: z.int().optional(),
    offset: z.int().optional(),
    order: TypesPriceUnitFilterOrder$zodSchema.optional(),
    price_unit_ids: z.array(z.string()).optional(),
    sort: z.array(TypesSortCondition$zodSchema).optional(),
    start_time: z.string().optional(),
    status: TypesStatus$zodSchema.optional(),
  });
