/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesFileType = {
  Csv: "CSV",
  Json: "JSON",
} as const;
export type TypesFileType = ClosedEnum<typeof TypesFileType>;

export const TypesFileType$zodSchema = z.enum([
  "CSV",
  "JSON",
]);
