/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesCreditGrantScope = {
  Plan: "PLAN",
  Subscription: "SUBSCRIPTION",
} as const;
export type TypesCreditGrantScope = ClosedEnum<typeof TypesCreditGrantScope>;

export const TypesCreditGrantScope$zodSchema = z.enum([
  "PLAN",
  "SUBSCRIPTION",
]);
