/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesSecretType = {
  PrivateKey: "private_key",
  PublishableKey: "publishable_key",
  Integration: "integration",
} as const;
export type TypesSecretType = ClosedEnum<typeof TypesSecretType>;

export const TypesSecretType$zodSchema = z.enum([
  "private_key",
  "publishable_key",
  "integration",
]);
