/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  TypesFilterCondition,
  TypesFilterCondition$zodSchema,
} from "./typesfiltercondition.js";
import {
  TypesSortCondition,
  TypesSortCondition$zodSchema,
} from "./typessortcondition.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";

export const TypesWorkflowExecutionFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type TypesWorkflowExecutionFilterOrder = ClosedEnum<
  typeof TypesWorkflowExecutionFilterOrder
>;

export const TypesWorkflowExecutionFilterOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type TypesWorkflowExecutionFilter = {
  end_time?: string | undefined;
  entity?: string | undefined;
  entity_id?: string | undefined;
  expand?: string | undefined;
  filters?: Array<TypesFilterCondition> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: TypesWorkflowExecutionFilterOrder | undefined;
  sort?: Array<TypesSortCondition> | undefined;
  start_time?: string | undefined;
  status?: TypesStatus | undefined;
  task_queue?: string | undefined;
  workflow_id?: string | undefined;
  workflow_status?: string | undefined;
  workflow_type?: string | undefined;
};

export const TypesWorkflowExecutionFilter$zodSchema: z.ZodType<
  TypesWorkflowExecutionFilter
> = z.object({
  end_time: z.string().optional(),
  entity: z.string().optional(),
  entity_id: z.string().optional(),
  expand: z.string().optional(),
  filters: z.array(TypesFilterCondition$zodSchema).optional(),
  limit: z.int().optional(),
  offset: z.int().optional(),
  order: TypesWorkflowExecutionFilterOrder$zodSchema.optional(),
  sort: z.array(TypesSortCondition$zodSchema).optional(),
  start_time: z.string().optional(),
  status: TypesStatus$zodSchema.optional(),
  task_queue: z.string().optional(),
  workflow_id: z.string().optional(),
  workflow_status: z.string().optional(),
  workflow_type: z.string().optional(),
});
