/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesDebugTrackerStatus = {
  Unprocessed: "unprocessed",
  NotFound: "not_found",
  Found: "found",
  Error: "error",
} as const;
export type TypesDebugTrackerStatus = ClosedEnum<
  typeof TypesDebugTrackerStatus
>;

export const TypesDebugTrackerStatus$zodSchema = z.enum([
  "unprocessed",
  "not_found",
  "found",
  "error",
]);
