/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesBillingCycle = {
  Anniversary: "anniversary",
  Calendar: "calendar",
} as const;
export type TypesBillingCycle = ClosedEnum<typeof TypesBillingCycle>;

export const TypesBillingCycle$zodSchema = z.enum([
  "anniversary",
  "calendar",
]);
