/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesAlertType = {
  LowOngoingBalance: "low_ongoing_balance",
  LowCreditBalance: "low_credit_balance",
  FeatureWalletBalance: "feature_wallet_balance",
} as const;
export type TypesAlertType = ClosedEnum<typeof TypesAlertType>;

export const TypesAlertType$zodSchema = z.enum([
  "low_ongoing_balance",
  "low_credit_balance",
  "feature_wallet_balance",
]);
