/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesInvoiceCadence = {
  Arrear: "ARREAR",
  Advance: "ADVANCE",
} as const;
export type TypesInvoiceCadence = ClosedEnum<typeof TypesInvoiceCadence>;

export const TypesInvoiceCadence$zodSchema = z.enum([
  "ARREAR",
  "ADVANCE",
]);
