/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesSubscriptionChangeType = {
  Upgrade: "upgrade",
  Downgrade: "downgrade",
  Lateral: "lateral",
} as const;
export type TypesSubscriptionChangeType = ClosedEnum<
  typeof TypesSubscriptionChangeType
>;

export const TypesSubscriptionChangeType$zodSchema = z.enum([
  "upgrade",
  "downgrade",
  "lateral",
]);
