/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesInvoiceBilling = {
  InvoiceToParent: "invoice_to_parent",
  InvoiceToSelf: "invoice_to_self",
} as const;
export type TypesInvoiceBilling = ClosedEnum<typeof TypesInvoiceBilling>;

export const TypesInvoiceBilling$zodSchema = z.enum([
  "invoice_to_parent",
  "invoice_to_self",
]);
