/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesWalletStatus = {
  Active: "active",
  Frozen: "frozen",
  Closed: "closed",
} as const;
export type TypesWalletStatus = ClosedEnum<typeof TypesWalletStatus>;

export const TypesWalletStatus$zodSchema = z.enum([
  "active",
  "frozen",
  "closed",
]);
