/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesEventProcessingStatusType = {
  Processed: "processed",
  Processing: "processing",
  Failed: "failed",
} as const;
export type TypesEventProcessingStatusType = ClosedEnum<
  typeof TypesEventProcessingStatusType
>;

export const TypesEventProcessingStatusType$zodSchema = z.enum([
  "processed",
  "processing",
  "failed",
]);
