/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesAlertCondition = {
  Above: "above",
  Below: "below",
} as const;
export type TypesAlertCondition = ClosedEnum<typeof TypesAlertCondition>;

export const TypesAlertCondition$zodSchema = z.enum([
  "above",
  "below",
]);
