/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesWalletType = {
  PrePaid: "PRE_PAID",
  PostPaid: "POST_PAID",
} as const;
export type TypesWalletType = ClosedEnum<typeof TypesWalletType>;

export const TypesWalletType$zodSchema = z.enum([
  "PRE_PAID",
  "POST_PAID",
]);
