/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesScheduleStatus = {
  Pending: "pending",
  Executing: "executing",
  Executed: "executed",
  Cancelled: "cancelled",
  Failed: "failed",
} as const;
export type TypesScheduleStatus = ClosedEnum<typeof TypesScheduleStatus>;

export const TypesScheduleStatus$zodSchema = z.enum([
  "pending",
  "executing",
  "executed",
  "cancelled",
  "failed",
]);
