/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  TypesFilterCondition,
  TypesFilterCondition$zodSchema,
} from "./typesfiltercondition.js";
import {
  TypesSortCondition,
  TypesSortCondition$zodSchema,
} from "./typessortcondition.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";
import { TypesUserType, TypesUserType$zodSchema } from "./typesusertype.js";

export const TypesUserFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type TypesUserFilterOrder = ClosedEnum<typeof TypesUserFilterOrder>;

export const TypesUserFilterOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type TypesUserFilter = {
  end_time?: string | undefined;
  expand?: string | undefined;
  filters?: Array<TypesFilterCondition> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: TypesUserFilterOrder | undefined;
  roles?: Array<string> | undefined;
  sort?: Array<TypesSortCondition> | undefined;
  start_time?: string | undefined;
  status?: TypesStatus | undefined;
  type?: TypesUserType | undefined;
  user_ids?: Array<string> | undefined;
};

export const TypesUserFilter$zodSchema: z.ZodType<TypesUserFilter> = z.object({
  end_time: z.string().optional(),
  expand: z.string().optional(),
  filters: z.array(TypesFilterCondition$zodSchema).optional(),
  limit: z.int().optional(),
  offset: z.int().optional(),
  order: TypesUserFilterOrder$zodSchema.optional(),
  roles: z.array(z.string()).optional(),
  sort: z.array(TypesSortCondition$zodSchema).optional(),
  start_time: z.string().optional(),
  status: TypesStatus$zodSchema.optional(),
  type: TypesUserType$zodSchema.optional(),
  user_ids: z.array(z.string()).optional(),
});
