/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  TypesFilterCondition,
  TypesFilterCondition$zodSchema,
} from "./typesfiltercondition.js";
import {
  TypesSortCondition,
  TypesSortCondition$zodSchema,
} from "./typessortcondition.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";

export const TypesFeatureFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type TypesFeatureFilterOrder = ClosedEnum<
  typeof TypesFeatureFilterOrder
>;

export const TypesFeatureFilterOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type TypesFeatureFilter = {
  end_time?: string | undefined;
  expand?: string | undefined;
  feature_ids?: Array<string> | undefined;
  filters?: Array<TypesFilterCondition> | undefined;
  limit?: number | undefined;
  lookup_key?: string | undefined;
  lookup_keys?: Array<string> | undefined;
  meter_ids?: Array<string> | undefined;
  name_contains?: string | undefined;
  offset?: number | undefined;
  order?: TypesFeatureFilterOrder | undefined;
  sort?: Array<TypesSortCondition> | undefined;
  start_time?: string | undefined;
  status?: TypesStatus | undefined;
};

export const TypesFeatureFilter$zodSchema: z.ZodType<TypesFeatureFilter> = z
  .object({
    end_time: z.string().optional(),
    expand: z.string().optional(),
    feature_ids: z.array(z.string()).optional(),
    filters: z.array(TypesFilterCondition$zodSchema).optional(),
    limit: z.int().optional(),
    lookup_key: z.string().optional(),
    lookup_keys: z.array(z.string()).optional(),
    meter_ids: z.array(z.string()).optional(),
    name_contains: z.string().optional(),
    offset: z.int().optional(),
    order: TypesFeatureFilterOrder$zodSchema.optional(),
    sort: z.array(TypesSortCondition$zodSchema).optional(),
    start_time: z.string().optional(),
    status: TypesStatus$zodSchema.optional(),
  });
