/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesTransactionStatus = {
  Pending: "pending",
  Completed: "completed",
  Failed: "failed",
} as const;
export type TypesTransactionStatus = ClosedEnum<typeof TypesTransactionStatus>;

export const TypesTransactionStatus$zodSchema = z.enum([
  "pending",
  "completed",
  "failed",
]);
