/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TypesCreditBreakdown = {
  free?: string | undefined;
  purchased?: string | undefined;
};

export const TypesCreditBreakdown$zodSchema: z.ZodType<TypesCreditBreakdown> = z
  .object({
    free: z.string().optional(),
    purchased: z.string().optional(),
  });
