/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesEntitlementEntityType = {
  Plan: "PLAN",
  Subscription: "SUBSCRIPTION",
  Addon: "ADDON",
} as const;
export type TypesEntitlementEntityType = ClosedEnum<
  typeof TypesEntitlementEntityType
>;

export const TypesEntitlementEntityType$zodSchema = z.enum([
  "PLAN",
  "SUBSCRIPTION",
  "ADDON",
]);
