/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesCreditNoteReason = {
  Duplicate: "DUPLICATE",
  Fraudulent: "FRAUDULENT",
  OrderChange: "ORDER_CHANGE",
  Unsatisfactory: "UNSATISFACTORY",
  ServiceIssue: "SERVICE_ISSUE",
  BillingError: "BILLING_ERROR",
  SubscriptionCancellation: "SUBSCRIPTION_CANCELLATION",
} as const;
export type TypesCreditNoteReason = ClosedEnum<typeof TypesCreditNoteReason>;

export const TypesCreditNoteReason$zodSchema = z.enum([
  "DUPLICATE",
  "FRAUDULENT",
  "ORDER_CHANGE",
  "UNSATISFACTORY",
  "SERVICE_ISSUE",
  "BILLING_ERROR",
  "SUBSCRIPTION_CANCELLATION",
]);
