/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesStatus = {
  Published: "published",
  Deleted: "deleted",
  Archived: "archived",
} as const;
export type TypesStatus = ClosedEnum<typeof TypesStatus>;

export const TypesStatus$zodSchema = z.enum([
  "published",
  "deleted",
  "archived",
]);
