/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesPriceUnitType = {
  Fiat: "FIAT",
  Custom: "CUSTOM",
} as const;
export type TypesPriceUnitType = ClosedEnum<typeof TypesPriceUnitType>;

export const TypesPriceUnitType$zodSchema = z.enum([
  "FIAT",
  "CUSTOM",
]);
