/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  TypesBillingCadence,
  TypesBillingCadence$zodSchema,
} from "./typesbillingcadence.js";
import {
  TypesBillingPeriod,
  TypesBillingPeriod$zodSchema,
} from "./typesbillingperiod.js";
import {
  TypesFilterCondition,
  TypesFilterCondition$zodSchema,
} from "./typesfiltercondition.js";
import {
  TypesSortCondition,
  TypesSortCondition$zodSchema,
} from "./typessortcondition.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";
import {
  TypesSubscriptionStatus,
  TypesSubscriptionStatus$zodSchema,
} from "./typessubscriptionstatus.js";

export const TypesSubscriptionFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type TypesSubscriptionFilterOrder = ClosedEnum<
  typeof TypesSubscriptionFilterOrder
>;

export const TypesSubscriptionFilterOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type TypesSubscriptionFilter = {
  active_at?: string | undefined;
  billing_cadence?: Array<TypesBillingCadence> | undefined;
  billing_period?: Array<TypesBillingPeriod> | undefined;
  customer_id?: string | undefined;
  end_time?: string | undefined;
  expand?: string | undefined;
  external_customer_id?: string | undefined;
  filters?: Array<TypesFilterCondition> | undefined;
  invoicing_customer_ids?: Array<string> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: TypesSubscriptionFilterOrder | undefined;
  parent_subscription_ids?: Array<string> | undefined;
  plan_id?: string | undefined;
  sort?: Array<TypesSortCondition> | undefined;
  start_time?: string | undefined;
  status?: TypesStatus | undefined;
  subscription_ids?: Array<string> | undefined;
  subscription_status?: Array<TypesSubscriptionStatus> | undefined;
  with_line_items?: boolean | undefined;
};

export const TypesSubscriptionFilter$zodSchema: z.ZodType<
  TypesSubscriptionFilter
> = z.object({
  active_at: z.string().optional(),
  billing_cadence: z.array(TypesBillingCadence$zodSchema).optional(),
  billing_period: z.array(TypesBillingPeriod$zodSchema).optional(),
  customer_id: z.string().optional(),
  end_time: z.string().optional(),
  expand: z.string().optional(),
  external_customer_id: z.string().optional(),
  filters: z.array(TypesFilterCondition$zodSchema).optional(),
  invoicing_customer_ids: z.array(z.string()).optional(),
  limit: z.int().optional(),
  offset: z.int().optional(),
  order: TypesSubscriptionFilterOrder$zodSchema.optional(),
  parent_subscription_ids: z.array(z.string()).optional(),
  plan_id: z.string().optional(),
  sort: z.array(TypesSortCondition$zodSchema).optional(),
  start_time: z.string().optional(),
  status: TypesStatus$zodSchema.optional(),
  subscription_ids: z.array(z.string()).optional(),
  subscription_status: z.array(TypesSubscriptionStatus$zodSchema).optional(),
  with_line_items: z.boolean().optional(),
});
