/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesSubscriptionScheduleChangeType = {
  PlanChange: "plan_change",
  Cancellation: "cancellation",
} as const;
export type TypesSubscriptionScheduleChangeType = ClosedEnum<
  typeof TypesSubscriptionScheduleChangeType
>;

export const TypesSubscriptionScheduleChangeType$zodSchema = z.enum([
  "plan_change",
  "cancellation",
]);
