/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesAlertState = {
  Ok: "ok",
  Info: "info",
  Warning: "warning",
  InAlarm: "in_alarm",
} as const;
export type TypesAlertState = ClosedEnum<typeof TypesAlertState>;

export const TypesAlertState$zodSchema = z.enum([
  "ok",
  "info",
  "warning",
  "in_alarm",
]);
