/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesCreditGrantCadence = {
  Onetime: "ONETIME",
  Recurring: "RECURRING",
} as const;
export type TypesCreditGrantCadence = ClosedEnum<
  typeof TypesCreditGrantCadence
>;

export const TypesCreditGrantCadence$zodSchema = z.enum([
  "ONETIME",
  "RECURRING",
]);
