/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoWalletResponse,
  DtoWalletResponse$zodSchema,
} from "./dtowalletresponse.js";
import {
  TypesPaginationResponse,
  TypesPaginationResponse$zodSchema,
} from "./typespaginationresponse.js";

export type TypesListResponseDtoWalletResponse = {
  items?: Array<DtoWalletResponse> | undefined;
  pagination?: TypesPaginationResponse | undefined;
};

export const TypesListResponseDtoWalletResponse$zodSchema: z.ZodType<
  TypesListResponseDtoWalletResponse
> = z.object({
  items: z.array(DtoWalletResponse$zodSchema).optional(),
  pagination: TypesPaginationResponse$zodSchema.optional(),
});
