/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesScheduleType = {
  Immediate: "immediate",
  EndOfPeriod: "end_of_period",
} as const;
export type TypesScheduleType = ClosedEnum<typeof TypesScheduleType>;

export const TypesScheduleType$zodSchema = z.enum([
  "immediate",
  "end_of_period",
]);
