/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { TypesStatus, TypesStatus$zodSchema } from "./typesstatus.js";

export const TypesQueryFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type TypesQueryFilterOrder = ClosedEnum<typeof TypesQueryFilterOrder>;

export const TypesQueryFilterOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type TypesQueryFilter = {
  expand?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: TypesQueryFilterOrder | undefined;
  sort?: string | undefined;
  status?: TypesStatus | undefined;
};

export const TypesQueryFilter$zodSchema: z.ZodType<TypesQueryFilter> = z.object(
  {
    expand: z.string().optional(),
    limit: z.int().optional(),
    offset: z.int().optional(),
    order: TypesQueryFilterOrder$zodSchema.optional(),
    sort: z.string().optional(),
    status: TypesStatus$zodSchema.optional(),
  },
);
