/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesSortDirection = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type TypesSortDirection = ClosedEnum<typeof TypesSortDirection>;

export const TypesSortDirection$zodSchema = z.enum([
  "asc",
  "desc",
]);
