/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesAlertCondition,
  TypesAlertCondition$zodSchema,
} from "./typesalertcondition.js";

export type TypesAlertThreshold = {
  condition?: TypesAlertCondition | undefined;
  threshold?: number | undefined;
};

export const TypesAlertThreshold$zodSchema: z.ZodType<TypesAlertThreshold> = z
  .object({
    condition: TypesAlertCondition$zodSchema.optional(),
    threshold: z.number().optional(),
  });
