/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesEntitlementUsageResetPeriod = {
  Monthly: "MONTHLY",
  Annual: "ANNUAL",
  Weekly: "WEEKLY",
  Daily: "DAILY",
  Quarterly: "QUARTERLY",
  HalfYearly: "HALF_YEARLY",
  Never: "NEVER",
} as const;
export type TypesEntitlementUsageResetPeriod = ClosedEnum<
  typeof TypesEntitlementUsageResetPeriod
>;

export const TypesEntitlementUsageResetPeriod$zodSchema = z.enum([
  "MONTHLY",
  "ANNUAL",
  "WEEKLY",
  "DAILY",
  "QUARTERLY",
  "HALF_YEARLY",
  "NEVER",
]);
