/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesPaymentDestinationType = {
  Invoice: "INVOICE",
} as const;
export type TypesPaymentDestinationType = ClosedEnum<
  typeof TypesPaymentDestinationType
>;

export const TypesPaymentDestinationType$zodSchema = z.enum([
  "INVOICE",
]);
