/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";
import {
  TypesFailurePointType,
  TypesFailurePointType$zodSchema,
} from "./typesfailurepointtype.js";

export type TypesFailurePoint = {
  error?: ErrorsErrorResponse | undefined;
  failure_point_type?: TypesFailurePointType | undefined;
};

export const TypesFailurePoint$zodSchema: z.ZodType<TypesFailurePoint> = z
  .object({
    error: ErrorsErrorResponse$zodSchema.optional(),
    failure_point_type: TypesFailurePointType$zodSchema.optional(),
  });
