/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesCouponCadence = {
  Once: "once",
  Repeated: "repeated",
  Forever: "forever",
} as const;
export type TypesCouponCadence = ClosedEnum<typeof TypesCouponCadence>;

export const TypesCouponCadence$zodSchema = z.enum([
  "once",
  "repeated",
  "forever",
]);
