/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesTaxRateStatus = {
  Active: "ACTIVE",
  Inactive: "INACTIVE",
} as const;
export type TypesTaxRateStatus = ClosedEnum<typeof TypesTaxRateStatus>;

export const TypesTaxRateStatus$zodSchema = z.enum([
  "ACTIVE",
  "INACTIVE",
]);
