/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesCancelImmediatelyInvoicePolicy = {
  GenerateInvoice: "generate_invoice",
  Skip: "skip",
} as const;
export type TypesCancelImmediatelyInvoicePolicy = ClosedEnum<
  typeof TypesCancelImmediatelyInvoicePolicy
>;

export const TypesCancelImmediatelyInvoicePolicy$zodSchema = z.enum([
  "generate_invoice",
  "skip",
]);
