/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesSortDirection,
  TypesSortDirection$zodSchema,
} from "./typessortdirection.js";

export type TypesSortCondition = {
  direction?: TypesSortDirection | undefined;
  field?: string | undefined;
};

export const TypesSortCondition$zodSchema: z.ZodType<TypesSortCondition> = z
  .object({
    direction: TypesSortDirection$zodSchema.optional(),
    field: z.string().optional(),
  });
