/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesCreditGrantExpiryDurationUnit = {
  Day: "DAY",
  Week: "WEEK",
  Month: "MONTH",
  Year: "YEAR",
} as const;
export type TypesCreditGrantExpiryDurationUnit = ClosedEnum<
  typeof TypesCreditGrantExpiryDurationUnit
>;

export const TypesCreditGrantExpiryDurationUnit$zodSchema = z.enum([
  "DAY",
  "WEEK",
  "MONTH",
  "YEAR",
]);
