/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesTaxRateType = {
  Percentage: "percentage",
  Fixed: "fixed",
} as const;
export type TypesTaxRateType = ClosedEnum<typeof TypesTaxRateType>;

export const TypesTaxRateType$zodSchema = z.enum([
  "percentage",
  "fixed",
]);
