/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesCreditNoteStatus = {
  Draft: "DRAFT",
  Finalized: "FINALIZED",
  Voided: "VOIDED",
} as const;
export type TypesCreditNoteStatus = ClosedEnum<typeof TypesCreditNoteStatus>;

export const TypesCreditNoteStatus$zodSchema = z.enum([
  "DRAFT",
  "FINALIZED",
  "VOIDED",
]);
