/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TypesCommitmentType = {
  Amount: "amount",
  Quantity: "quantity",
} as const;
export type TypesCommitmentType = ClosedEnum<typeof TypesCommitmentType>;

export const TypesCommitmentType$zodSchema = z.enum([
  "amount",
  "quantity",
]);
