/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TypesWalletConfigPriceType,
  TypesWalletConfigPriceType$zodSchema,
} from "./typeswalletconfigpricetype.js";

export type TypesWalletConfig = {
  allowed_price_types?: Array<TypesWalletConfigPriceType> | undefined;
};

export const TypesWalletConfig$zodSchema: z.ZodType<TypesWalletConfig> = z
  .object({
    allowed_price_types: z.array(TypesWalletConfigPriceType$zodSchema)
      .optional(),
  });
