/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoPlanResponse,
  DtoPlanResponse$zodSchema,
} from "./dtoplanresponse.js";
import {
  DtoUpdatePlanRequest,
  DtoUpdatePlanRequest$zodSchema,
} from "./dtoupdateplanrequest.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type UpdatePlanRequest = { id: string; body: DtoUpdatePlanRequest };

export const UpdatePlanRequest$zodSchema: z.ZodType<UpdatePlanRequest> = z
  .object({
    body: DtoUpdatePlanRequest$zodSchema,
    id: z.string().describe("Plan ID"),
  });

export type UpdatePlanResponse = DtoPlanResponse | ErrorsErrorResponse;

export const UpdatePlanResponse$zodSchema: z.ZodType<UpdatePlanResponse> = z
  .union([
    DtoPlanResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
