/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoEntitlementResponse,
  DtoEntitlementResponse$zodSchema,
} from "./dtoentitlementresponse.js";
import {
  DtoUpdateEntitlementRequest,
  DtoUpdateEntitlementRequest$zodSchema,
} from "./dtoupdateentitlementrequest.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type UpdateEntitlementRequest = {
  id: string;
  body: DtoUpdateEntitlementRequest;
};

export const UpdateEntitlementRequest$zodSchema: z.ZodType<
  UpdateEntitlementRequest
> = z.object({
  body: DtoUpdateEntitlementRequest$zodSchema,
  id: z.string().describe("Entitlement ID"),
});

export type UpdateEntitlementResponse =
  | DtoEntitlementResponse
  | ErrorsErrorResponse;

export const UpdateEntitlementResponse$zodSchema: z.ZodType<
  UpdateEntitlementResponse
> = z.union([
  DtoEntitlementResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
