/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoPriceResponse,
  DtoPriceResponse$zodSchema,
} from "./dtopriceresponse.js";
import {
  DtoUpdatePriceRequest,
  DtoUpdatePriceRequest$zodSchema,
} from "./dtoupdatepricerequest.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type UpdatePriceRequest = { id: string; body: DtoUpdatePriceRequest };

export const UpdatePriceRequest$zodSchema: z.ZodType<UpdatePriceRequest> = z
  .object({
    body: DtoUpdatePriceRequest$zodSchema,
    id: z.string().describe("Price ID"),
  });

export type UpdatePriceResponse = DtoPriceResponse | ErrorsErrorResponse;

export const UpdatePriceResponse$zodSchema: z.ZodType<UpdatePriceResponse> = z
  .union([
    DtoPriceResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
