/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoUpdateWalletRequest,
  DtoUpdateWalletRequest$zodSchema,
} from "./dtoupdatewalletrequest.js";
import {
  DtoWalletResponse,
  DtoWalletResponse$zodSchema,
} from "./dtowalletresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type UpdateWalletRequest = { id: string; body: DtoUpdateWalletRequest };

export const UpdateWalletRequest$zodSchema: z.ZodType<UpdateWalletRequest> = z
  .object({
    body: DtoUpdateWalletRequest$zodSchema,
    id: z.string().describe("Wallet ID"),
  });

export type UpdateWalletResponse = DtoWalletResponse | ErrorsErrorResponse;

export const UpdateWalletResponse$zodSchema: z.ZodType<UpdateWalletResponse> = z
  .union([
    DtoWalletResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
