/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoInvoiceResponse,
  DtoInvoiceResponse$zodSchema,
} from "./dtoinvoiceresponse.js";
import {
  DtoUpdateInvoiceRequest,
  DtoUpdateInvoiceRequest$zodSchema,
} from "./dtoupdateinvoicerequest.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type UpdateInvoiceRequest = {
  id: string;
  body: DtoUpdateInvoiceRequest;
};

export const UpdateInvoiceRequest$zodSchema: z.ZodType<UpdateInvoiceRequest> = z
  .object({
    body: DtoUpdateInvoiceRequest$zodSchema,
    id: z.string().describe("Invoice ID"),
  });

export type UpdateInvoiceResponse = DtoInvoiceResponse | ErrorsErrorResponse;

export const UpdateInvoiceResponse$zodSchema: z.ZodType<UpdateInvoiceResponse> =
  z.union([
    DtoInvoiceResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
