/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCouponResponse,
  DtoCouponResponse$zodSchema,
} from "./dtocouponresponse.js";
import {
  DtoUpdateCouponRequest,
  DtoUpdateCouponRequest$zodSchema,
} from "./dtoupdatecouponrequest.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type UpdateCouponRequest = { id: string; body: DtoUpdateCouponRequest };

export const UpdateCouponRequest$zodSchema: z.ZodType<UpdateCouponRequest> = z
  .object({
    body: DtoUpdateCouponRequest$zodSchema,
    id: z.string().describe("Coupon ID"),
  });

export type UpdateCouponResponse = DtoCouponResponse | ErrorsErrorResponse;

export const UpdateCouponResponse$zodSchema: z.ZodType<UpdateCouponResponse> = z
  .union([
    DtoCouponResponse$zodSchema,
    ErrorsErrorResponse$zodSchema,
  ]);
