/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoEnvironmentResponse,
  DtoEnvironmentResponse$zodSchema,
} from "./dtoenvironmentresponse.js";
import {
  DtoUpdateEnvironmentRequest,
  DtoUpdateEnvironmentRequest$zodSchema,
} from "./dtoupdateenvironmentrequest.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type UpdateEnvironmentRequest = {
  id: string;
  body: DtoUpdateEnvironmentRequest;
};

export const UpdateEnvironmentRequest$zodSchema: z.ZodType<
  UpdateEnvironmentRequest
> = z.object({
  body: DtoUpdateEnvironmentRequest$zodSchema,
  id: z.string().describe("Environment ID"),
});

export type UpdateEnvironmentResponse =
  | DtoEnvironmentResponse
  | ErrorsErrorResponse;

export const UpdateEnvironmentResponse$zodSchema: z.ZodType<
  UpdateEnvironmentResponse
> = z.union([
  DtoEnvironmentResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
