/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DtoCreditNoteResponse,
  DtoCreditNoteResponse$zodSchema,
} from "./dtocreditnoteresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$zodSchema,
} from "./errorserrorresponse.js";

export type VoidCreditNoteRequest = { id: string };

export const VoidCreditNoteRequest$zodSchema: z.ZodType<VoidCreditNoteRequest> =
  z.object({
    id: z.string().describe("Credit note ID"),
  });

export type VoidCreditNoteResponse =
  | DtoCreditNoteResponse
  | ErrorsErrorResponse;

export const VoidCreditNoteResponse$zodSchema: z.ZodType<
  VoidCreditNoteResponse
> = z.union([
  DtoCreditNoteResponse$zodSchema,
  ErrorsErrorResponse$zodSchema,
]);
